Repository eclipse-che/che-docs, pull requests merged in 2018-08, with the labels that each got.

#446 Fixed vulnerability issue
  src/main/Gemfile.lock
Labels: kind/bug, status/code-review

#447 Fix license header text
  pom.xml
Labels: kind/bug, status/code-review

#444 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#443 Move to central
  pom.xml
Labels: status/code-review

#439 Update documentation in admin guide for Openshift/Kubernetes
  src/main/pages/overview/single-multi-user.md
  src/main/pages/setup-openshift/admin-guide.md
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: kind/bug, status/code-review

#451 Topic 448
  src/main/pages/setup-openshift/openshift-multi-user.md
Labels: status/code-review

#452 Misc language and mark-up fixes.
  src/main/pages/setup-openshift/openshift-multi-user.md
Labels: kind/bug, status/code-review

#453 Fix broken navigation link.
  src/main/_data/topnav.yml
Labels: kind/docs, status/code-review

#455 Admin note: how to delete user.
  src/main/pages/setup-openshift/admin-guide.md
Labels: kind/task, status/code-review

#458 Create template for 6.10.0 release notes
  src/main/pages/release-notes/release-6.10.0.md
Labels: kind/task, status/code-review

#459 Fix URLs.
  src/main/pages/setup-kubernetes/kubernetes-multi-user.md
Labels: kind/bug, status/code-review

#457 Added documenting of secure servers and JwtProxy as backend for them
  src/main/images/diagrams/servers-cookies-auth.svg
  src/main/pages/workspace-admin/secure-servers.md
  src/main/pages/workspace-admin/servers.md
Labels: kind/task, status/code-review

#461 Add notes about project source parameters
  src/main/pages/workspace-admin/workspace-data-model.md
Labels: kind/bug, status/code-review

#462 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#460 Added notes about Secure Servers
  src/main/pages/release-notes/release-6.10.0.md
Labels: kind/task, status/code-review
