Repository eclipse-che/che-docs, pull requests merged in 2018-12, with the labels that each got.

#617 Fix mark-up syntax for validity.
  src/main/pages/che-6/portable-workspaces/creating-factories.adoc
  src/main/pages/che-6/portable-workspaces/factories-getting-started.adoc
  src/main/pages/che-6/portable-workspaces/factories_json_reference.adoc
  src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
  src/main/pages/che-6/setup-openshift/openshift-admin-guide.adoc
  src/main/pages/che-6/setup-openshift/openshift-multi-user.adoc
  src/main/pages/che-6/user-management/permissions.adoc
  src/main/pages/che-6/user-management/resource-management.adoc
  src/main/pages/che-6/workspace-admin/recipes.adoc
  src/main/pages/che-6/workspace-admin/what-are-workspaces.adoc
  src/main/pages/che-6/workspace-admin/workspace-data-model.adoc
Labels: kind/bug, kind/docs, status/code-review

#625 Adding release notes declaring changes related to CORS
  release-notes/release-6.15.0.md
Labels: kind/enhancement, status/code-review

#626 Add release notes about Jaeger tracing enhancements.
  release-notes/release-6.15.0.md
Labels: kind/task, status/code-review

#628 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#623 mis-spell:worskspace -> workspace
  src/main/pages/che-6/overview/introduction.adoc
Labels: status/code-review

#629 Source versatility
  src/main/_config.yml
  src/main/pages/che-6/portable-workspaces/factories-getting-started.adoc
  src/main/pages/che-6/setup-openshift/openshift-multi-user.adoc
  src/main/pages/che-6/setup-openshift/using-ocp-to-deploy-che.adoc
  src/main/pages/che-6/user-management/user-management.adoc
  src/main/pages/che-6/workspace-admin/what-are-workspaces.adoc
Labels: kind/enhancement, status/code-review

#614 [Wip] This fixes grammar and style for Workspace Admin-> Projects
  src/main/pages/che-6/workspace-admin/projects.adoc
Labels: kind/bug, status/code-review

#631 revise some grammer issues
  src/main/pages/che-6/developer-guide/assemblies.adoc
  src/main/pages/che-6/developer-guide/project-types.adoc
Labels: status/code-review

#630 Update self signed cert docs
  src/main/pages/che-6/setup-openshift/openshift-config.adoc
Labels: kind/enhancement, status/code-review

#636 Added description of per-workspace PVC strategy
  run.sh
  src/main/pages/che-6/setup-kubernetes/kubernetes-admin-guide.adoc
  src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
  src/main/pages/che-6/setup-openshift/openshift-admin-guide.adoc
Labels: kind/enhancement, status/code-review

#638 Fix factory link.
  src/main/pages/che-6/portable-workspaces/factories-getting-started.adoc
Labels: kind/bug, kind/docs, status/code-review

#639 fix loopback alias command
  src/main/pages/che-6/overview/quick-start.adoc
Labels: kind/bug, status/code-review

#651 RELEASE: Set next development version
  pom.xml
Labels: status/code-review
