Repository eclipse-che/che-docs, pull requests merged in 2018-02, with the labels that each got.

#355 Token vs service account
  src/main/pages/setup-openshift/openshift-multi-user.md
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: status/code-review

#358 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#357 Added docs for Che on Kubernetes
  src/main/_data/sidebars/user_sidebar.yml
  src/main/pages/setup-kubernetes/kubernetes-config.md
  src/main/pages/setup-kubernetes/kubernetes-single-user.md
  src/main/pages/setup-openshift/openshift-config.md
Labels: kind/enhancement, status/code-review

#359 Add naming conventions and prop vs env priority
  src/main/pages/developer-guide/properties.md
Labels: kind/enhancement, status/code-review

#361 OSO deployment
  src/main/images/diagrams/ocp_multi_user.png
  src/main/images/keycloak/keycloak_realm.png
  src/main/pages/setup-openshift/openshift-config.md
  src/main/pages/setup-openshift/openshift-multi-user.md
  src/main/pages/setup-openshift/openshift-single-user.md
  src/main/pages/user-management/user-management.md
Labels: status/code-review

#362 Fix the script installation with openshift
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: kind/bug, status/code-review

#364 Update information on properties overriding
  src/main/pages/developer-guide/properties.md
  src/main/pages/setup-docker/docker-config.md
Labels: kind/enhancement, status/code-review

#363 Rename docker daemon url property
  src/main/pages/setup-docker/docker-config.md
Labels: status/code-review
