Repository eclipse-che/che-docs, pull requests merged in 2018-11, with the labels that each got.

#525 I496-user-mngemnt-orig
  src/main/pages/user-management/organizations.adoc
Labels: status/code-review

#534 RHDEVDOCS-875: Reviewed the Single-User: Deployment to Kubernetes sec…
  src/main/pages/setup-kubernetes/kubernetes-single-user.adoc
Labels: status/code-review

#536 RHDEVDOCS-880: Edited the Multi-User: Deploy to Kubernetes section fo…
  src/main/pages/setup-kubernetes/kubernetes-multi-user.adoc
Labels: status/code-review

#533 [WIP] I496 user mngemnt auth
  src/main/pages/user-management/user-management.adoc
Labels: status/code-review

#522 i507- workspace-stacks
  src/main/pages/workspace-admin/stacks.adoc
Labels: status/code-review

#552 Fix minor bullet-point rendering issue in Introduction
  src/main/pages/overview/introduction.adoc
Labels: kind/bug, status/code-review

#557 Update for Che 7; misc fixes.
  README.md
Labels: kind/docs, kind/enhancement, status/code-review

#524 I523 fix jdt.ls
  src/main/pages/user-guide/dependency-management.adoc
  src/main/pages/user-guide/dependency-management.md
  src/main/pages/user-guide/editor_code_assistance.adoc
Labels: kind/bug, status/code-review

#559 Fix lang. and mark-up in WS Agent topic.
  src/main/pages/developer-guide/workspace-agent.adoc
Labels: kind/docs, kind/enhancement, status/code-review

#518 i489-openshift-admin-guide
  src/main/pages/setup-openshift/openshift-admin-guide.adoc
Labels: kind/bug, status/code-review

#561 Update components to avoid potential security vulnerabilities in dependencies
  src/main/Gemfile.lock
Labels: kind/enhancement, status/code-review

#541 i596 user-mngement-resource
  src/main/pages/user-management/resource-management.adoc
Labels: status/code-review

#562 [docker] Update image
  .dockerignore
  Dockerfile
  build-docker-image.sh
Labels: status/code-review

#565 Enhancements on run.sh script
  run.sh
Labels: status/code-review

#532 [WIP] I507 workspace admin -> recipe
  src/main/pages/workspace-admin/recipes.adoc
Labels: status/code-review

#537 [WIP] i496 User-Mngemnt-Permissions.
  src/main/pages/user-management/permissions.adoc
Labels: status/code-review

#549 Add more information about manageSystem permission
  src/main/pages/developer-guide/logging.adoc
  src/main/pages/user-management/permissions.adoc
  src/main/pages/workspace-admin/installers.adoc
Labels: kind/enhancement, status/code-review

#540 I538 workspace admin-> servers
  src/main/pages/workspace-admin/servers.adoc
Labels: status/code-review

#564 Use `millisecond` as the unit for `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT`.
  src/main/pages/user-management/resource-management.adoc
Labels: status/code-review

#586 Fix invalid link (#553).
  src/main/pages/overview/introduction.adoc
Labels: kind/bug, status/code-review

#590 Fix Che Super Privileged Mode env var name
  src/main/pages/user-management/permissions.adoc
Labels: kind/docs, status/code-review

#594 Remove pure kubectl Che deployment instructions
  src/main/pages/setup-kubernetes/kubernetes-single-user.adoc
Labels: kind/task, status/code-review

#595 [WIP]I589 Update Workspace ->Volume Mount
  src/main/pages/workspace-admin/volumes.adoc
Labels: status/code-review

#601 Update pom.xml to use new Docker image for docs building.
  pom.xml
Labels: kind/enhancement, status/code-review

#528 [WIP] RHDEVDOCS:874: Edited the CLI-Reference section for language and asci…
  src/main/css/customstyles.css
  src/main/pages/setup-docker/docker-cli.adoc
Labels: status/code-review

#597 [WIP] I542 configuration kubernetes review
  src/main/pages/setup-kubernetes/kubernetes-config.adoc
Labels: status/code-review

#605 [WIP] workspace admin -> env var
  src/main/pages/workspace-admin/env-variables.adoc
Labels: status/code-review

#608 RHDEVDOCS-891: Reviewed the Workspace Data Model section for language…
  src/main/pages/workspace-admin/workspace-data-model.adoc
Labels: status/code-review

#587 I545 remove rn
  release-notes/rn-template.md
  src/main/pages/release-notes/release-6.0.0.adoc
  src/main/pages/release-notes/release-6.10.0.adoc
  src/main/pages/release-notes/release-6.11.0.adoc
  src/main/pages/release-notes/release-notes-guidelines.adoc
  src/main/pages/release-notes/release-notes.adoc
  src/main/pages/release-notes/rn-template.adoc
Labels: kind/docs, status/code-review

#609 I502 fix openshift
  src/main/_config.yml
  src/main/pages/setup-kubernetes/kubernetes-admin-guide.adoc
  src/main/pages/setup-kubernetes/kubernetes-multi-user.adoc
  src/main/pages/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
  src/main/pages/setup-openshift/kubernetes-admin-guide.adoc
  src/main/pages/setup-openshift/openshift-admin-guide.adoc
Labels: kind/docs, kind/enhancement, status/code-review

#613 Update Release Notes template
  release-notes/rn-template.md
Labels: kind/enhancement, status/code-review
