Repository eclipse-che/che-docs, pull requests merged in 2018-07, with the labels that each got.

#429 Add Z option to docker volume mount to fix SELinux context.
  run.sh
Labels: kind/bug, status/code-review

#419 Instructions on importing community supported stacks and samples
  src/main/pages/workspace-admin/stacks.md
Labels: status/code-review

#431 I430 fix links
  src/main/pages/dev_essentials/guice.md
  src/main/pages/developer-guide/assemblies.md
  src/main/pages/developer-guide/custom-installers.md
  src/main/pages/developer-guide/language-servers.md
  src/main/pages/developer-guide/server-side-extensions.md
  src/main/pages/setup-docker/docker-single-user.md
  src/main/pages/setup-openshift/admin-guide.md
  src/main/pages/setup-openshift/kubernetes-admin-guide.md
  src/main/pages/spi/spi_overview.md
  src/main/pages/user-guide/commands-ide-macro.md
  src/main/pages/user-management/permissions.md
  src/main/pages/workspace-admin/workspaces-troubleshooting.md
Labels: kind/bug, status/code-review

#432 Lang servers
  src/main/pages/developer-guide/language-servers.md
Labels: status/code-review

#433 Fix bad links
  src/main/pages/developer-guide/language-servers.md
Labels: kind/bug, status/code-review

#436 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#437 This update address PR 434 and fixes wording, grammar and punctuation errors. The change…
  src/main/pages/setup-openshift/openshift-config.md
Labels: kind/bug, status/code-review

#438 Removed outdated section about recipe permissions
  src/main/pages/user-management/permissions.md
Labels: kind/task, status/code-review

#442 Add missing var definition.
  src/main/_config.yml
Labels: kind/enhancement, status/code-review
