Repository eclipse-che/che-docs, pull requests merged in 2018-10, with the labels that each got.

#504 Update CODEOWNERS
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review

#499 che #11350: Adding docs for ephemeral workspace configuration via 'emptyDir' volumes
  src/main/pages/setup-openshift/openshift-admin-guide.adoc
  src/main/pages/workspace-admin/volumes.adoc
Labels: status/code-review

#469 Create page about Che Databases
  src/main/pages/developer-guide/databases.adoc
Labels: kind/docs, status/code-review

#505 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#501 Fix invalid link.
  src/main/pages/setup-docker/docker-multi-user.adoc
Labels: kind/bug, status/code-review

#492 I478 underscores
  README.md
  src/main/pages/setup-docker/docker-config.adoc
  src/main/pages/setup-docker/docker-single-user.adoc
  src/main/pages/setup-openshift/kubernetes-admin-guide.adoc
  src/main/pages/setup-openshift/openshift-admin-guide.adoc
  src/main/pages/setup-openshift/openshift-config.adoc
  src/main/pages/user-management/authentication.adoc
  src/main/pages/workspace-admin/recipes.adoc
  src/main/pages/workspace-admin/secure-servers.adoc
  src/main/pages/workspace-admin/stacks.adoc
Labels: kind/bug, status/code-review

#468 Update Quick Start topic based on PR#465.
  src/main/pages/overview/quick-start.adoc
Labels: kind/enhancement, status/code-review

#404 Updated docs for jdt.ls integration
  src/main/pages/overview/introduction.adoc
  src/main/pages/user-guide/dependency-management.md
  src/main/pages/user-guide/editor_code_assistance.adoc
Labels: kind/enhancement, status/code-review

#519 [WIP] Topic workspace overview
  src/main/pages/workspace-admin/what-are-workspaces.adoc
Labels: status/code-review

#527 Update config and add necessary CSS for Font Awesome icons to work.
  src/main/_config.yml
  src/main/_includes/head.html
  src/main/css/asciidoc.css
  src/main/pages/setup-openshift/openshift-admin-guide.adoc
Labels: kind/docs, status/code-review

#530 Fixed image link
  src/main/pages/user-management/authentication.adoc
Labels: kind/bug, status/code-review

#531 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#539 Add notes about WS agent debug enabling
  src/main/pages/developer-guide/workspace-agent.adoc
Labels: kind/task, status/code-review

#513 RHDEVDOCS-869: Reviewed the Multi-User: Install on Docker section for…
  src/main/pages/setup-docker/docker-multi-user.adoc
Labels: status/code-review

#547 Append / to url, otherwise Che returns a 302
  src/main/pages/developer-guide/rest-api.adoc
Labels: status/code-review

#517 i476-overview-supported-infra
  src/main/pages/overview/infra-support.adoc
Labels: kind/bug, status/code-review
