Repository eclipse-che/che-docs, pull requests merged in 2018-06, with the labels that each got.

#410 Add a note about Factories from URL
  src/main/pages/portable-workspaces/chedir-getting-started.md
  src/main/pages/portable-workspaces/creating-factories.md
Labels: kind/enhancement, status/code-review

#407 Stack sharing instructions
  src/main/images/workspaces/stack_permissions.png
  src/main/pages/workspace-admin/stacks.md
Labels: status/code-review

#400 Make key generation docs clearer
  src/main/pages/user-guide/version-control.md
Labels: status/code-review

#417 Self signed certs docs improvements
  src/main/images/workspaces/ca_secret.png
  src/main/images/workspaces/cert_env.png
  src/main/images/workspaces/chrome_cert.png
  src/main/images/workspaces/chrome_cert_export.png
  src/main/pages/setup-openshift/openshift-config.md
Labels: status/code-review

#420 Fix typos
  src/main/pages/setup-openshift/admin-guide.md
  src/main/pages/setup-openshift/openshift-multi-user.md
Labels: kind/bug, status/code-review

#418 Improved machine authentication article
  src/main/pages/user-management/authentication.md
Labels: kind/docs, status/code-review

#421 Improved machine auth diagram
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/images/diagrams/machine_auth_flow.png
Labels: kind/docs, status/code-review

#422 Fix typos in machine authentication diagram
  src/main/images/diagrams/machine_auth_flow.png
Labels: kind/docs, status/code-review

#423 Open id doc
  src/main/pages/user-management/authentication.md
Labels: kind/docs, status/code-review

#415 Update kubernetes-multi-user helm deployment docs with info on deploy…
  src/main/pages/setup-kubernetes/kubernetes-multi-user.md
Labels: kind/enhancement, status/code-review

#426 RELEASE: Set next development version
  pom.xml
Labels: status/code-review
