Repository eclipse-che/che-docs, pull requests merged in 2018-03, with the labels that each got.

#365 Fixed typos in Kubernetes docs
  src/main/pages/setup-kubernetes/kubernetes-single-user.md
Labels: kind/bug, status/code-review

#366 Added note about how to enable ingress controller on minikube
  src/main/pages/setup-kubernetes/kubernetes-single-user.md
Labels: kind/enhancement, status/code-review

#368 Fix links in che-in-che
  src/main/pages/developer-guide/che-in-che-quickstart.md
Labels: kind/bug, status/code-review

#369 Added information how to configure logback with environment variables
  src/main/pages/setup-docker/docker-config.md
Labels: kind/enhancement, status/code-review

#370 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#374 OpenShift version update
  src/main/pages/setup-openshift/openshift-config.md
  src/main/pages/setup-openshift/openshift-multi-user.md
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: kind/bug, status/code-review

#376 che #9062: Adding info about env var for setting workspace pod termination grace period for Kubernetes / OpenShift infrastructures
  src/main/pages/setup-kubernetes/kubernetes-config.md
  src/main/pages/setup-openshift/openshift-config.md
Labels: status/code-review

#379 Updated links to scripts
  src/main/pages/setup-openshift/openshift-multi-user.md
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: kind/enhancement, status/code-review

#378 Fix #377 Update che addon remove steps for minishift.
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: kind/bug, status/code-review

#375 Add documentation for alternate OIDC providers
  src/main/pages/setup-openshift/openshift-config.md
Labels: kind/enhancement, status/code-review

#381 link to install minishift
  src/main/pages/setup-openshift/openshift-multi-user.md
  src/main/pages/setup-openshift/openshift-single-user.md
Labels: kind/enhancement, status/code-review

#382 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#384 [WIP] Rewrite docs about logging
  src/main/_data/sidebars/user_sidebar.yml
  src/main/pages/developer-guide/assemblies.md
  src/main/pages/developer-guide/logging.md
  src/main/pages/setup-docker/docker-config.md
  src/main/pages/setup-kubernetes/kubernetes-config.md
  src/main/pages/setup-openshift/openshift-config.md
Labels: status/code-review
