Repository eclipse-che/che-docs, pull requests merged in 2018-04, with the labels that each got.

#386 Docs cleanup
  src/main/pages/developer-guide/framework-overview.md
  src/main/pages/developer-guide/ide-extensions-js.md
  src/main/pages/developer-guide/server-side-extension.md
  src/main/pages/setup-kubernetes/kubernetes-config.md
  src/main/pages/setup-kubernetes/kubernetes-single-user.md
  src/main/pages/setup-openshift/openshift-config.md
Labels: status/code-review

#387 Remove JS docs from sidebar
  src/main/_data/sidebars/user_sidebar.yml
  src/main/pages/developer-guide/language_servers.md
Labels: status/code-review

#390 Update documentation related to machine auth
  src/main/images/diagrams/machine_auth_flow.png
  src/main/pages/user-management/authentication.md
Labels: kind/enhancement, status/code-review

#395 rh-che-557: Adding docs for configuring K8s / OpenShift unrecoverable…
  src/main/pages/setup-kubernetes/kubernetes-config.md
Labels: kind/docs, status/code-review

#392 Fix doc for che-dir
  src/main/pages/portable-workspaces/chedir-installation.md
Labels: kind/bug, status/code-review

#396 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#401 Add notes about API url environment variables in workspace containers
  src/main/pages/setup-docker/docker-config.md
Labels: kind/enhancement, status/code-review
