Repository eclipse-che/che-docs, pull requests merged in 2019-01, with the labels that each got.

#650 Modify link tag to LSP SPEC
  src/main/pages/che-6/developer-guide/language-servers.adoc
Labels: status/code-review

#643 Add docs and release notes for 6.16 about CORS changes
  release-notes/release-6.16.0.md
  src/main/pages/che-6/developer-guide/cors.adoc
Labels: kind/task, status/code-review

#662 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#640 Helm dependency update now required before installing to kubernetes
  src/main/pages/che-6/setup-kubernetes/kubernetes-multi-user.adoc
  src/main/pages/che-6/setup-kubernetes/kubernetes-single-user.adoc
Labels: kind/docs, status/code-review

#635 Added release notes for self-signed certificates
  release-notes/rn-6.16.0.md
Labels: kind/enhancement, status/code-review

#658 Add release notes for the che_workspace_failure_total and che_workspace_status metrics.
  release-notes/release-6.17.0.md
Labels: kind/task, status/code-review

#641 Add release notes about prometheus and grafana in the Helm chart.
  release-notes/release-6.16.0.md
Labels: kind/docs, status/code-review

#649 Add release notes for the /activity endpoint changes.
  release-notes/release-6.16.0.md
Labels: kind/task, status/code-review

#667 Update release notes for formatting, content, add 6.17.0 release note
  release-notes/release-6.15.0.md
  release-notes/release-6.16.0.md
  release-notes/release-6.17.0.md
  release-notes/rn-6.16.0.md
Labels: kind/enhancement, status/code-review

#672 Add pass-through macro to variabnle.
  src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
  src/main/pages/che-6/setup-openshift/openshift-admin-guide.adoc
Labels: kind/bug, kind/docs, status/code-review
