Repository eclipse-che/che-docs, pull requests merged in 2019-03, with the labels that each got.

#687 Consistency in filenames, formatting for release notes
  release-notes/release-6.18.0.md
  release-notes/release-6.18.md
  release-notes/release-6.19.0.md
Labels: status/code-review

#652 Added section about auto-stopping workspaces without pods
  src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
Labels: kind/enhancement, status/code-review

#693 Add initial set of Che 7 guides + user story templates.
  src/main/pages/che-7/developer-guide/assembly_configuring-workspaces.adoc
  src/main/pages/che-7/developer-guide/assembly_creating-workspaces.adoc
  src/main/pages/che-7/developer-guide/assembly_extending-che.adoc
  src/main/pages/che-7/developer-guide/con_understanding-che-extensibility.adoc
  src/main/pages/che-7/developer-guide/con_understanding-workspaces.adoc
  src/main/pages/che-7/developer-guide/proc_creating-a-workspace-by-importing-source-code-of-your-project.adoc
  src/main/pages/che-7/developer-guide/proc_creating-a-workspace-from-a-code-sample.adoc
  src/main/pages/che-7/developer-guide/proc_creating-a-workspace-from-a-recipe.adoc
  src/main/pages/che-7/developer-guide/proc_creating-a-workspace-using-multi-machine-environments.adoc
  src/main/pages/che-7/developer-guide/proc_defining-recipes.adoc
  src/main/pages/che-7/developer-guide/proc_defining-volumes-docker-volumes-pvcs-and-pvs.adoc
  src/main/pages/che-7/developer-guide/proc_defining-workspace-runtime-environments.adoc
  src/main/pages/che-7/developer-guide/proc_packaging-che-plugins.adoc
  src/main/pages/che-7/developer-guide/proc_packaging-theia-plugins.adoc
  src/main/pages/che-7/developer-guide/proc_packaging-visual-studio-code-extensions.adoc
  src/main/pages/che-7/developer-guide/proc_supporting-che-plugin-types-with-plugin-brokers.adoc
  src/main/pages/che-7/developer-guide/proc_working-with-che-plugin-registries.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-eclipse-che-quick-start.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#699 Populate sidebar for Che 7 docs.
  run.sh
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-6/setup-kubernetes/kubernetes-admin-guide.adoc
  src/main/pages/che-6/setup-openshift/openshift-admin-guide.adoc
  src/main/pages/che-6/setup-openshift/openshift-multi-user.adoc
  src/main/pages/che-6/user-management/permissions.adoc
  src/main/pages/che-7/administration-guide/assembly_administration-tasks.adoc
  src/main/pages/che-7/administration-guide/assembly_securing-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_api-reference.adoc
  src/main/pages/che-7/end-user-guide/assembly_developing-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/assembly_extending-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_extensibility-reference.adoc
  src/main/pages/che-7/end-user-guide/assembly_making-a-workspace-portable-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_publishing-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-developer-environments-workspaces.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-plug-in.adoc
  src/main/pages/che-7/end-user-guide/con_che-extension-points.adoc
  src/main/pages/che-7/hands-on-guidance/assembly_contributor-tasks.adoc
  src/main/pages/che-7/hands-on-guidance/assembly_end-user-tasks.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/assembly_che-installation-overview.adoc
  src/main/pages/che-7/installation-guide/assembly_che-installation-prerequisites.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#701 Add CSS for responsive video embeds.
  src/main/css/customstyles.css
Labels: Che-6, Che-7, kind/docs, kind/enhancement, status/code-review
