Repository eclipse-che/che-docs, pull requests merged in 2019-09, with the labels that each got.

#792 I14262: Reviewed the Overview > Che architecture sections.
  src/main/pages/che-7/overview/assembly_che-workspace-controller.adoc
  src/main/pages/che-7/overview/assembly_che-workspaces-architecture.adoc
  src/main/pages/che-7/overview/con_che-devfile-registry.adoc
  src/main/pages/che-7/overview/con_che-editor-plug-in.adoc
  src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
  src/main/pages/che-7/overview/con_che-postgresql.adoc
  src/main/pages/che-7/overview/con_che-user-runtimes.adoc
  src/main/pages/che-7/overview/con_che-workspace-creation-flow.adoc
  src/main/pages/che-7/overview/con_che-workspace-jwt-proxy.adoc
  src/main/pages/che-7/overview/con_workspaces-namespaces-configuration.adoc
Labels: kind/task, status/code-review

#805 RELEASE: Set next '7.2.0-SNAPSHOT' development version
  pom.xml
Labels: kind/task, status/code-review

#807 Clarify when the next channel is updated for chectl updates
  src/main/pages/che-7/overview/proc_upgrading-the-chectl-management-tool.adoc
Labels: status/code-review

#809 Updatin 7.0 to 7.1
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: status/code-review

#808 Provide devfile for ready to edit workspace for che-docs
  devfile.yaml
Labels: kind/enhancement, status/code-review

#810 docs(docker): Avoid to use latest for CHE 6 cli as it's only for 6.19.x and no longer for 7.x
  src/main/_config.yml
  src/main/pages/che-6/overview/quick-start.adoc
  src/main/pages/che-6/setup-docker/docker-config.adoc
  src/main/pages/che-6/setup-docker/docker-multi-user.adoc
  src/main/pages/che-6/setup-docker/docker-single-user.adoc
Labels: kind/bug, status/code-review

#811 Fix quick start redirects.
  src/main/pages/che-6/overview/quick-start.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#806 Verifications after chectl installation
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
Labels: status/code-review

#800 Improving 'Registering to Hosted Che' procedure doc
  src/main/pages/che-7/overview/proc_registering-to-hosted-che.adoc
Labels: status/code-review

#819 Add Fabrice as code owner of che-docs repo
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review

#818 Che extensibility reference
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/contributor-guide/assembly_che-extensibility-reference.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/contributor-guide/ref_debug-adapter-protocol.adoc
  src/main/pages/che-7/contributor-guide/ref_language-server-protocol.adoc
Labels: status/code-review

#817 Add Viewing plug-in broker logs
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-plug-in-broker-logs.adoc
Labels: kind/enhancement, status/code-review

#813 Add Che4z content
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/extensions/che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-product-accessibility-features.adoc
  src/main/pages/che-7/extensions/che4z-release-information.adoc
  src/main/pages/che-7/extensions/che4z-using-explorer-for-zos.adoc
Labels: kind/enhancement, status/code-review

#795 Fix navig menu link
  src/main/_data/sidebars/che_7_docs.yml
Labels: Che-7, kind/bug, kind/docs, status/code-review

#780 i779: Reviewed the Contributor guide for language and formatting.
  src/main/pages/che-7/contributor-guide/assembly_testing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-registries.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-into-a-workspace.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-debugger.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_sharing-your-che-theia-plug-in-with-a-factory.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
Labels: status/code-review

#790 i14262: Edited the 'intro to che, installing chectl, & running che lo…
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/overview/assembly_hosted-che.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_configuring-dns-on-azure.adoc
  src/main/pages/che-7/overview/proc_contributing-to-github-projects-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_creating-a-workspace-from-template-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
  src/main/pages/che-7/overview/proc_importing-projects-from-github-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-dns-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_installing-ingress-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_registering-to-hosted-che.adoc
  src/main/pages/che-7/overview/proc_upgrading-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/ref_about-hosted-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/task, status/code-review

#799 I14380: Fixed a couple of things in the 'proc_configuring-a-workspace…
  src/main/pages/che-7/end-user-guide/proc_configuring-a-workspace-using-a-devfile.adoc
Labels: kind/bug, status/code-review

#816 Added configMap concept module to the Che 7 docs
  src/main/pages/che-6/setup-kubernetes/kubernetes-config.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
Labels: kind/enhancement, status/code-review

#803 Unified prerequisities for End-user-guide + additional fixes
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-projects-to-your-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-a-new-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  src/main/pages/che-7/end-user-guide/proc_exporting-a-workspace-with-a-che-factory.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_importing-a-vs-code-extension-in-the-che-theia-editor.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-open-button.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-run-button.adoc
  src/main/pages/che-7/end-user-guide/proc_running-and-debugging.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-new-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-workspace-with-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_using-and-customizing-a-workspace-template-stack.adoc
Labels: kind/bug, status/code-review

#820 Name change
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/extensions/che4z-release-information.adoc
  src/main/pages/che-7/extensions/che4z-using-explorer-for-zos.adoc
Labels: status/code-review

#797 Add the missing dockerimage component endpoint attributes to the devfile reference
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#821 Fix a typo in the cookiesAuthEnabled parameter
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/bug, status/code-review

#822 Fix https deploy doc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-azure.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: kind/bug, status/code-review

#824 Add table of contents to release information
  src/main/pages/che-7/extensions/che4z-release-information.adoc
Labels: status/code-review

#828 Do Not Strip / From url for Search
  src/main/search.json
Labels: status/code-review

#829 Prepend site.baseurl in search.json
  src/main/search.json
Labels: status/code-review

#831 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#826 Add documentation for token exchange
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
Labels: kind/enhancement, status/code-review

#832 Add number of workspaces panel, users row, number of users panel
  src/main/images/monitoring/monitoring-che-che-server-dashboard-users-panel.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-workspace-panel.png
  src/main/pages/che-7/administration-guide/proc_viewing-che-metrics-on-grafana-dashboards.adoc
Labels: status/code-review
