Repository eclipse-che/che-docs, pull requests merged in 2019-08, with the labels that each got.

#769 Added the 'Running Che on MS Azure' to the Installation Guide for Che 7.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/installation/adding-a-record-set.png
  src/main/images/installation/che-user-dashboard.png
  src/main/images/installation/completing-the-creation-of-the-zone.png
  src/main/images/installation/dns-zone-in-microsoft-azure.png
  src/main/images/installation/entering-the-name-fo-the-domain.png
  src/main/images/installation/example-of-an-added-dns-zone.png
  src/main/images/installation/list-of-created-zones-and-NS.png
  src/main/images/installation/new-dns-challenge-added.png
  src/main/images/installation/record-set-button.png
  src/main/images/installation/selecting-the-resource-group.png
  src/main/images/installation/wildcard-certificates-for-keycloak-che.png
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_running-eclipse-che-on-microsoft-azure.adoc
  src/main/pages/che-7/overview/proc_configuring-dns-on-azure.adoc
  src/main/pages/che-7/overview/proc_creating-the-secret.adoc
  src/main/pages/che-7/overview/proc_enabling-the-tls-dns-challenge.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-ingress-on-azure.adoc
  src/main/pages/che-7/overview/proc_preparing-the-azure-environment-for-installing-che.adoc
Labels: kind/enhancement, status/code-review

#770 Installing multi-user Che with TLS on Google Cloud Platform
  src/main/images/installation/che-user-dashboard-gcp.png
  src/main/images/installation/cloud-dns-zone-on-gcp.png
  src/main/images/installation/creating-dns-zone-on-gcp.png
  src/main/images/installation/dns-challenge-gcp.png
  src/main/images/installation/dns-settings-gcp.png
  src/main/images/installation/keycloak-and-che-with-valid-wildcard-certs.gif
  src/main/images/installation/registrar-setup-gcp.png
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-microsoft-azure.adoc
  src/main/pages/che-7/overview/assembly_preparing-google-cloud-platform-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_configuring-dns-on-azure.adoc
  src/main/pages/che-7/overview/proc_creating-a-google-kubernetes-engine-instance.adoc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-azure.adoc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_enabling-the-tls-dns-challenge-on-azure.adoc
  src/main/pages/che-7/overview/proc_enabling-the-tls-dns-challenge-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-dns-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_installing-ingress-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_preparing-azure-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: status/code-review

#772 Update theia-endpoint-runtime image
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: kind/enhancement, status/code-review

#784 Add Che 7.0 KI
  src/main/_data/sidebars/che_docs_home.yml
  src/main/_data/topnav.yml
  src/main/index.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: Che-7, kind/docs, kind/task, status/code-review

#781 14198: Incorporated Sun's feedback in the 'Deploying Che on AWS' sect…
  src/main/images/installation/aws-lauch-instance.png
  src/main/images/installation/aws-summary-iam-role.png
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: status/code-review

#787 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#746 Add documantation how to add support for a new language
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-language.adoc
Labels: kind/docs, status/code-review

#774 Adding support for a new language - Sidebar menu
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-language.adoc
Labels: kind/enhancement, status/code-review

#773 Fixed duplication image and removed unnecessary image links
  src/main/images/workspaces/che-6-workspace-configuration.png
  src/main/images/workspaces/defining-the-workspace-editor.png
  src/main/images/workspaces/workspace_configuration_che_6.png
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
Labels: kind/bug, status/code-review

#788 Installing chectl as quickstart chapter
  src/main/_config-war.yml
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_customizing-the-devfile-and-plug-in-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_modifying-the-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-keycloak-logs.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-new-devfile.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-keycloak-server-logs.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-postgresql-server-logs.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-debugger.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_hosted-che.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/con_high-level-che-architecture.adoc
  src/main/pages/che-7/overview/proc_creating-a-worskpace-from-the-user-dashboard.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_upgrading-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/ref_about-hosted-che.adoc
Labels: status/code-review

#786 update installing chectl
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
Labels: kind/enhancement, status/code-review

#785 Fix formatting of yaml files related to TLS certificates
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
Labels: kind/bug, status/code-review

#783 Added the review for the Che 7 End-user guide once again.
  src/main/pages/che-7/end-user-guide/assembly_adding-che-plug-in-registry-vs-code-extension-to-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_defining-custom-commands-for-che-theia.adoc
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_making-a-workspace-portable-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_remotely-accessing-workspaces.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-alternative-ides-in-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-developer-environments-workspaces.adoc
  src/main/pages/che-7/end-user-guide/assembly_version-control.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-concept-in-detail.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-lifecycle.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-task-types.adoc
  src/main/pages/che-7/end-user-guide/con_embedded-and-remote-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  src/main/pages/che-7/end-user-guide/proc_editing-a-task-and-a-launch-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_importing-a-vs-code-extension-in-the-che-theia-editor.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/end-user-guide/proc_running-and-debugging.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-workspace-with-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-devfile-for-your-project.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: kind/enhancement, status/code-review

#789 fix navigation error for importing-a-kubernetes-application-into-a-wo…
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
Labels: kind/bug, status/code-review

#782 Fix heading levels and reorganize "Creating a workspace from code sample"
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/proc_developing-che-monitoring-metrics.adoc
  src/main/pages/che-7/administration-guide/proc_removing-user-data.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-operator-logs.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-language.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/assembly_remotely-accessing-workspaces.adoc
  src/main/pages/che-7/end-user-guide/assembly_running-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-developer-environments-workspaces.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-concept-in-detail.adoc
  src/main/pages/che-7/end-user-guide/con_embedded-and-remote-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-a-new-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-open-button.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-run-button.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-new-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_navigating-che-using-the-dashboard.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_navigating-che-using-the-dashboard-on-minishift.adoc
  src/main/pages/che-7/overview/proc_navigating-che-using-the-dashboard-on-ocp-and-openstack.adoc
  src/main/pages/che-7/overview/proc_navigating-che-using-the-dashboard.adoc
  src/main/pages/che-7/overview/proc_using-the-ide.adoc
Labels: kind/bug, status/code-review

#794 che #14308 Adding 'IMPORTANT' note to the main Che 6 workspace page with a refence to the 'Converting a Che 6 workspace to a Che 7 devfile' documentation
  src/main/pages/che-6/workspace-admin/what-are-workspaces.adoc
Labels: kind/bug, status/code-review

#793 Add links to sample devfiles
  src/main/pages/che-7/end-user-guide/proc_writing-a-devfile-for-your-project.adoc
Labels: kind/enhancement, status/code-review

#791 Add configuration file for linkchecker
  linkcheckerrc
Labels: kind/enhancement, status/code-review

#796 Updating docs for Che 6 configuration to Che 7 devfile migration.
  src/main/images/workspaces/add-custom-project.png
  src/main/images/workspaces/remove-default-project.png
  src/main/images/workspaces/update-devfile-configuration.png
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
Labels: Che-7, kind/task, status/code-review
