Repository eclipse-che/che-docs, pull requests merged in 2019-02, with the labels that each got.

#669 Add initial item proposals for 6.18 release notes
  release-notes/release-6.18.md
Labels: kind/enhancement, status/code-review

#676 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#680 Add release notes about fix to workspace idling detection.
  release-notes/release-6.19.md
Labels: status/code-review

#648 Add a short mention of the monitorSystem permission in the docs.
  src/main/pages/che-6/user-management/permissions.adoc
Labels: kind/task, status/code-review

#675 Add release notes about mountSources.
  release-notes/release-6.18.md
Labels: kind/enhancement, status/code-review

#678 Removing renegade number
  src/main/pages/che-6/overview/quick-start.adoc
Labels: status/code-review

#666 Release notes for CHE_DEBUG_SUSPEND support on k8s and openshift
  release-notes/rn-6.18.0.md
Labels: kind/bug, status/code-review

#686 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#674 Update PVC acronym expansion I missed previously
  release-notes/release-6.18.md
Labels: kind/enhancement, status/code-review

#683 Polish release note related to workspace idling heuristics
  release-notes/release-6.19.md
Labels: status/code-review

#679 Fix dead links in Quick Start page
  src/main/pages/che-6/overview/quick-start.adoc
Labels: kind/bug, status/code-review

#684 Clarify user benefit of `mountSources` attribute for `che-plugin.yaml`
  release-notes/release-6.18.md
Labels: status/code-review
