Repository eclipse-che/che-docs, pull requests merged in 2019-10, with the labels that each got.

#825 installation guide - namespace per user strategy
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: kind/task, status/code-review

#834 Added a minimal Kubernetes version requairment
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_deploying-che-on-kubernetes-on-aws.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_creating-a-google-kubernetes-engine-instance.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: kind/enhancement, status/code-review

#823 Update metrics
  src/main/images/monitoring/monitoring-che-che-server-dashboard-tomcat-panel.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-traces-panel.png
  src/main/pages/che-7/administration-guide/proc_viewing-che-metrics-on-grafana-dashboards.adoc
Labels: kind/enhancement, status/code-review

#835 Explain grafana dashboard provider
  src/main/pages/che-7/administration-guide/proc_viewing-che-metrics-on-grafana-dashboards.adoc
Labels: kind/enhancement, status/code-review

#838 Explain the overrideCheProperties field
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
Labels: status/code-review

#836 Remove TOC and add Apache license
  src/main/pages/che-7/extensions/che4z-release-information.adoc
  src/main/pages/che-7/extensions/che4z-using-explorer-for-zos.adoc
Labels: status/code-review

#812 i14495: Added an admonition to run multiple workspaces in the 'How th…
  src/main/pages/che-6/setup-kubernetes/kubernetes-or-openshift-admin-guide.adoc
Labels: kind/enhancement, status/code-review

#841 I1283 and i1324 cleaning creating repairing devfile section
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_making-a-workspace-portable-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-developer-environments-workspaces.adoc
  src/main/pages/che-7/end-user-guide/con_a-minimal-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_what-is-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-workspace-with-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-devfile-for-your-project.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-samples.adoc
Labels: kind/enhancement, status/code-review

#845 Che 7 Overviews - Revamped
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_securing-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-ide-basics.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/overview/assembly_che-architecture.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
Labels: status/code-review

#844 Fix apiVersion
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
Labels: Che-7, kind/task, status/code-review

#846 fix link in proc_including-the-plug-in-binaries-in-the-registry-image
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
Labels: kind/bug, status/code-review

#847 fix links in proc_creating-a-workspace-by-importing-source-code-of-a-…
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
Labels: kind/bug, status/code-review

#850 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#853 I1354 modularization of configuring workspace exposure strategies
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/con_security-considerations.adoc
  src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-workspace-exposure-strategies-using-the-helm-chart-and-the-operator.adoc
Labels: status/code-review

#854 fixing asciidoctor build errors
  src/main/pages/che-7/end-user-guide/proc_exporting-a-workspace-with-a-che-factory.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review

#856 Minor lang. and formatting fixes.
  src/main/pages/che-7/end-user-guide/assembly_che-theia-troubleshooting.adoc
Labels: kind/bug, status/code-review, target/branch

#852 Add Che-Theia troubleshooting page
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_che-theia-ide-basics.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-troubleshooting.adoc
Labels: Che-7, kind/docs, status/code-review

#857 Modularize Running Che Locally
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_using-codeready-containers-to-set-up-openshift-4.adoc
  src/main/pages/che-7/overview/proc_using-docker-desktop-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/proc_using-minishift-to-set-up-openshift-3.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: status/code-review

#858 add :context: in assemblies
  src/main/pages/che-7/administration-guide/assembly_authenticating-to-the-che-server.adoc
  src/main/pages/che-7/administration-guide/assembly_authenticating-users.adoc
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/assembly_troubleshooting-for-che-administrators.adoc
  src/main/pages/che-7/contributor-guide/assembly_che-api-reference.adoc
  src/main/pages/che-7/contributor-guide/assembly_developing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/assembly_publishing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/assembly_testing-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-ide-basics.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-troubleshooting.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/assembly_defining-custom-commands-for-che-theia.adoc
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_making-a-workspace-portable-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-alternative-ides-in-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_version-control.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
  src/main/pages/che-7/overview/assembly_che-architecture.adoc
  src/main/pages/che-7/overview/assembly_deploying-che-on-kubernetes-on-aws.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
Labels: kind/enhancement, status/code-review

#859 fix CodeReady Containers product documentation URL
  src/main/pages/che-7/overview/proc_using-codeready-containers-to-set-up-openshift-4.adoc
Labels: kind/bug, status/code-review

#860 Lang. and formatting fixes.
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review, target/branch

#842 Add projects section into devfile spec document
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: Che-7, kind/task, status/code-review

#863 Adding [subs="+attributes"] in shell sessions mentionning chectl
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_upgrading-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: kind/enhancement, status/code-review

#866 Fix typos: OpenShift
  src/main/pages/che-7/administration-guide/proc_viewing-che-metrics-on-grafana-dashboards.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
Labels: kind/bug, status/code-review

#861 Update the version Control section with the latest changes
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
Labels: kind/task, status/code-review

#855 update namespace strategies with new CHE_INFRA_KUBERNETES_NAMESPACE v…
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: kind/enhancement, status/code-review

#839 Preview URL documentation
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#870 Update monitoring docs
  src/main/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-1.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-2.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-3.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-4.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-5.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-jsonrpc-panel.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-1.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-2.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-3.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-4.png
  src/main/images/monitoring/monitoring-che-che-server-dashboard-traces-panel.png
  src/main/pages/che-7/administration-guide/proc_viewing-che-metrics-on-grafana-dashboards.adoc
Labels: kind/task, status/code-review

#869 Modularize installing on openshift 4
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
  src/main/pages/che-7/overview/proc_creating-the-che-project-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-registering-as-a-new-user.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-using-oauth.adoc
  src/main/pages/che-7/overview/proc_viewing-che-operator-logs-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
Labels: status/code-review

#871 Avoid 2 xref in the same paragraph
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
Labels: status/code-review

#878 Fixes on installing che on openshift 4
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
Labels: kind/bug, status/code-review

#883 Clarify how to view logs using CLI on OpenShift 4
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_viewing-che-operator-logs-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
Labels: status/code-review

#887 Explain that at least one user using OAuth is needed
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_using-codeready-containers-to-set-up-openshift-4.adoc
Labels: status/code-review

#888 Describe how to find deployment errors in OpenShift web console
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
Labels: status/code-review

#894 New doc: Upgrading from Che 6 to Che 7 on OpenShift 4 using the Operator
  src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-from-che-6-to-che-7-on-openshift-4-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_finishing-the-upgrade-from-che-6-to-che-7-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-from-che-6-to-che-7-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
Labels: status/code-review
