Repository eclipse-che/che-docs, pull requests merged in 2019-12, with the labels that each got.

#899 Explain the interaction of namespace and PVC strategies in more detail.
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: status/code-review

#952 Add devfile parameters override procedure
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
Labels: kind/enhancement, status/code-review

#955 Fix namespace selection for upgrade.
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#957 Added missing subs="attributes" and ifevals.
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
Labels: kind/enhancement, status/code-review

#960 Added Stacks vs Devfiles - Concept
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_disambiguation-between-stacks-and-devfiles.adoc
Labels: kind/enhancement, status/code-review

#961 Fetch content from master to 7.3.x branch
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_disambiguation-between-stacks-and-devfiles.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
Labels: status/code-review, target/branch

#959 Describe known issue with StorageClass configuration
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/task, status/code-review

#958 Update che7 doc referencing the old workspace definition
  src/main/images/extensibility/adding-plug-ins-in-dashboard.png
  src/main/images/extensibility/adding-plug-ins-in-workspace-configuration.png
  src/main/images/extensibility/adding-plug-ins-in-workspace-devfile.png
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-registries.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-into-a-workspace.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_sharing-your-che-theia-plug-in-with-a-factory.adoc
Labels: kind/task, status/code-review

#964 By default, a user can start only one workspace at a time
  src/main/pages/che-7/end-user-guide/con_che-theia-task-types.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_editing-a-task-and-a-launch-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
  src/main/pages/che-7/end-user-guide/proc_running-and-debugging.adoc
  src/main/pages/che-7/end-user-guide/proc_using-and-customizing-a-workspace-template-stack.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/assembly_che-installation-overview.adoc
  src/main/pages/che-7/installation-guide/assembly_che-installation-prerequisites.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-on-different-kubernetes-distributions.adoc
  src/main/pages/che-7/installation-guide/assembly_troubleshooting-che-installation.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-with-openshift-oauth.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-email-notifications.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-private-docker-registries.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-workspace-memory-settings.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-https-mode.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-without-keycloak.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/installation-guide/ref_che-configuration-reference-table.adoc
  src/main/pages/che-7/installation-guide/ref_identity.adoc
  src/main/pages/che-7/installation-guide/ref_networking.adoc
  src/main/pages/che-7/installation-guide/ref_storage.adoc
Labels: status/code-review

#965 Ifdef super-priv mode to limit to Che.
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#968 Fix a typo
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
Labels: kind/bug, status/code-review

#970 Fix typo in advanced config section
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
Labels: kind/bug, status/code-review

#971 Fix for downstream
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
Labels: kind/bug, status/code-review

#966 Add info how to tune memory limits and env vars for components
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#972 New attributes
  src/main/_config.yml
Labels: status/code-review

#973 upgrade ruby dependencies
  src/main/Gemfile.lock
Labels: status/code-review

#975 Fix link for swagger
  .gitignore
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
  src/main/pages/che-7/administration-guide/proc_using-swagger-or-rest-clients-to-execute-queries.adoc
  src/main/pages/che-7/contributor-guide/assembly_che-api-reference.adoc
  src/main/pages/che-7/contributor-guide/ref_access-to-swagger.adoc
  src/main/pages/che-7/contributor-guide/ref_factory-api.adoc
  src/main/pages/che-7/contributor-guide/ref_ide-macros.adoc
  src/main/pages/che-7/contributor-guide/ref_permissions-api.adoc
  src/main/pages/che-7/contributor-guide/ref_resources-api.adoc
  src/main/pages/che-7/contributor-guide/ref_workspace-api.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
Labels: kind/bug, status/code-review

#977 Update Eclipse Che4z overview with two new extensions
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
Labels: status/code-review

#978 Installing Jaeger tracing tool -files
  src/main/pages/che-7/administration-guide/assembly_installing-the-jaeger-tracing-tool.adoc
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
Labels: status/code-review

#980 Adding OCP atribute and one markup fix
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
Labels: kind/bug, status/code-review

#982 Typo fixing, enhancing the procedure steps, applying better markup
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
Labels: kind/bug, status/code-review

#985 Broken xref fix
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
Labels: kind/bug, status/code-review

#987 feat(docker-image): Use of quay.io repository
  build-docker-image.sh
  run.sh
Labels: status/code-review

#989 WIP CRW-574 fix docs re: adding...
  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
Labels: kind/bug, status/code-review

#988 Fix defaults for the devfile
  devfile.yaml
Labels: kind/bug, status/code-review

#991 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#992 CRW-574 fix docs re: adding plugins/devfiles...
  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
Labels: kind/bug, status/code-review

#994 fix build errors and update content
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-registries.adoc
Labels: kind/bug, status/code-review

#990 Adapt Monitoring Che for downstream usage
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
Labels: status/code-review

#995 Screenshots prefix applied
  src/main/images/workspaces/{prod-id-short}-run-from-recent-workspaces.png
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
Labels: kind/bug, status/code-review

#993 upstream/downstream agostic example for Creating secure servers
  src/main/pages/che-7/administration-guide/proc_creating-secure-servers.adoc
Labels: status/code-review

#996 Screenshot fix
  src/main/images/workspaces/che-run-from-recent-workspaces.png
Labels: kind/bug, status/code-review

#997 screeshot Fix
  src/main/images/workspaces/che-select-workpace.png
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
Labels: kind/bug, status/code-review

#983 build-docker-image also with podman
  build-docker-image.sh
  run.sh
Labels: status/code-review

#998 rework building a custom registry image
  src/main/pages/che-7/administration-guide/assembly_building-and-running-a-custom-registry-image.adoc
  src/main/pages/che-7/administration-guide/assembly_building-the-images-of-the-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_cloning-the-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_deploying-the-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_modifying-the-registries.adoc
  src/main/pages/che-7/administration-guide/examples/che-build-the-devfile-registry.sh
  src/main/pages/che-7/administration-guide/examples/che-build-the-plug-in-registry.sh
  src/main/pages/che-7/administration-guide/examples/che-clone-the-devfile-registry-repository.sh
  src/main/pages/che-7/administration-guide/examples/che-clone-the-plug-in-registry-repository.sh
  src/main/pages/che-7/administration-guide/examples/che-devfile-meta.yml
  src/main/pages/che-7/administration-guide/examples/crw-build-the-devfile-registry.sh
  src/main/pages/che-7/administration-guide/examples/crw-build-the-plug-in-registry.sh
  src/main/pages/che-7/administration-guide/examples/crw-clone-the-devfile-registry-repository.sh
  src/main/pages/che-7/administration-guide/examples/crw-clone-the-plug-in-registry-repository.sh
  src/main/pages/che-7/administration-guide/proc_adding-a-new-devfile.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-new-plug-in.adoc
  src/main/pages/che-7/administration-guide/proc_building-a-custom-devfile-registry.adoc
  src/main/pages/che-7/administration-guide/proc_building-a-custom-plug-in-registry.adoc
  src/main/pages/che-7/administration-guide/proc_building-the-images-of-the-devfile-registry.adoc
  src/main/pages/che-7/administration-guide/proc_building-the-images-of-the-plug-in-registry.adoc
  src/main/pages/che-7/administration-guide/proc_cloning-the-devfile-registry.adoc
  src/main/pages/che-7/administration-guide/proc_cloning-the-plug-in-registry.adoc
Labels: status/code-review

#963 refresh ref_che-theia-plug-in-metadata with updated content
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: status/code-review

#1001 Update git SSL docs
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
Labels: kind/enhancement, status/code-review

#1002 use latest container image for devfile
  devfile.yaml
Labels: status/code-review

#1000 Clarifications in monitoring chapter
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-and-exposing-che-metrics.adoc
  src/main/pages/che-7/administration-guide/proc_extending-che-monitoring-metrics.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-metrics-on-grafana-dashboards.adoc
  src/main/pages/che-7/administration-guide/ref_grafana-dashboards-for-che.adoc
Labels: status/code-review

#1005 Add missed headers
  src/main/pages/che-7/administration-guide/examples/che-build-the-devfile-registry.sh
  src/main/pages/che-7/administration-guide/examples/che-build-the-plug-in-registry.sh
  src/main/pages/che-7/administration-guide/examples/che-clone-the-devfile-registry-repository.sh
  src/main/pages/che-7/administration-guide/examples/che-clone-the-plug-in-registry-repository.sh
  src/main/pages/che-7/administration-guide/examples/crw-build-the-devfile-registry.sh
  src/main/pages/che-7/administration-guide/examples/crw-build-the-plug-in-registry.sh
  src/main/pages/che-7/administration-guide/examples/crw-clone-the-devfile-registry-repository.sh
  src/main/pages/che-7/administration-guide/examples/crw-clone-the-plug-in-registry-repository.sh
Labels: kind/enhancement, status/code-review
