Repository eclipse-che/che-docs, pull requests merged in 2019-11, with the labels that each got.

#895 Update che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#893 Add a known issue to che 7.3.0 detailing that users should not instal…
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/bug, status/code-review

#891 minikube in LXC instructions
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: kind/feature, status/code-review

#881 Maximum one xref per paragraph.
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-registering-as-a-new-user.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-using-oauth.adoc
Labels: status/code-review

#897 Update che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#892 generate name docs
  src/main/pages/che-7/end-user-guide/assembly_making-a-workspace-portable-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_a-minimal-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-workspace-names.adoc
Labels: kind/task, status/code-review

#886 Modify run.sh to work with podman
  run.sh
Labels: status/code-review

#868 Add docs for airgap/offline deployment of Che
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
Labels: kind/task, status/code-review

#833 FIXED the wrong link to Plugin registry, which is a duplicate to Devf…
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
  src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
Labels: kind/bug, status/code-review

#902 RELEASE: Set next development version
  pom.xml
Labels: status/code-review

#900 files for odp suport
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/installation/edit-source-code-button-che-odp.png
  src/main/images/installation/red-hat-application-menu-che-odp.png
  src/main/pages/che-7/overview/assembly_accessing-che-from-openshift-developer-perspective.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/con_openshift-developer-perspective-integration-with-che.adoc
  src/main/pages/che-7/overview/proc_accessing-che-from-red-hat-applications-menu.adoc
  src/main/pages/che-7/overview/proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc
Labels: status/code-review

#905 Language fixes, style changes
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/contributor-guide/assembly_branding-che-theia.adoc
  src/main/pages/che-7/contributor-guide/assembly_branding-your-che-theia.adoc
Labels: kind/bug, status/code-review, target/branch

#843 Branding your Che-theia
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/branding/about-dark.png
  src/main/images/branding/about-light.png
  src/main/images/branding/welcome-dark.png
  src/main/images/branding/welcome-light.png
  src/main/pages/che-7/contributor-guide/assembly_branding-che-theia.adoc
Labels: kind/enhancement, status/code-review

#906 Minor lang. fixes in Keycloak logs viewing.
  src/main/pages/che-7/administration-guide/proc_viewing-keycloak-server-logs.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#907 Restructure, modularize, add overview of steps.
  src/main/pages/che-7/contributor-guide/assembly_branding-che-theia.adoc
  src/main/pages/che-7/contributor-guide/proc_building-a-che-theia-container-image-with-custom-branding.adoc
  src/main/pages/che-7/contributor-guide/proc_defining-custom-branding-values-for-che-theia.adoc
  src/main/pages/che-7/contributor-guide/proc_testing-che-theia-with-custom-branding.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#908 Eclipse Che4z GA documentation update
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-product-accessibility-features.adoc
  src/main/pages/che-7/extensions/che4z-release-information.adoc
  src/main/pages/che-7/extensions/che4z-using-explorer-for-zos.adoc
Labels: status/code-review

#911 fix reference to {context} in a link
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-concept-in-detail.adoc
Labels: kind/bug, status/code-review

#912 Add config file for embedded docs build.
  run.sh
  src/main/_config-war.yml
  src/main/_config-web.yml
Labels: Che-7, kind/bug, kind/docs, status/code-review

#914 che #15192 Fixing wrong example for che custom properties
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
Labels: kind/bug, status/code-review

#915 Escape { for non-attributes words
  .gitignore
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
  src/main/pages/che-7/administration-guide/con_super-privileged-mode.adoc
  src/main/pages/che-7/administration-guide/ref_managesystem-permission.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-github-oauth.adoc
  src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-using-the-operator-and-ssl.adoc
Labels: status/code-review

#917 Escape { for non-attributes words (again)
  src/main/pages/che-7/administration-guide/proc_listing-che-permissions.adoc
Labels: status/code-review

#916 [13886] Reference module for che configmaps fields
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
Labels: kind/task, status/code-review

#918 Words replacements
  src/main/pages/che-7/administration-guide/assembly_customizing-the-devfile-and-plug-in-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_deploying-the-registries.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-new-plug-in.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_building-the-images-of-the-plug-in-registry.adoc
  src/main/pages/che-7/administration-guide/proc_checking-omnisharp-theia-plug-in-language-server-features.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-openshift.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-debugger.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_importing-a-vs-code-extension-in-the-che-theia-editor.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/assembly_updating-che.adoc
  src/main/pages/che-7/installation-guide/proc_finishing-the-upgrade-from-che-6-to-che-7-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-from-che-6-to-che-7-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/con_che-editor-plug-in.adoc
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-for-installing-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: status/code-review

#920 Add AsciiDoc attributes for 'prod'.
  src/main/_config.yml
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#923 Fix the script applying attributes substitutions
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-a-visual-studio-code-extension-in-che.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/ref_objects-supported-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-from-che-6-to-che-7-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
  tools/substitutions.sed
Labels: kind/bug, status/code-review

#924 fix compilation errors
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: kind/bug, status/code-review, target/branch

#901 Migrate info about PVCs strategies from Che 6 Docs
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: kind/task, status/code-review

#913 Nov13
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#928 [Doc} Che7 - Che4z Product version corrected
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#934 Che4z install guide improvements
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#933 Fix a vs. an exceptions
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/installation-guide/proc_finishing-the-upgrade-from-che-6-to-che-7-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: kind/bug, status/code-review

#937 Remove section about installing vscode extension in running workspace
  src/main/pages/che-7/end-user-guide/assembly_using-a-visual-studio-code-extension-in-che.adoc
Labels: status/code-review

#935 Add section about env field for k8s/os component in devfile
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#939 Structure, lang. fixes.
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-with-self-sign-git-https.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
Labels: kind/bug, status/code-review, target/branch

#938 Update che4z-release-information.adoc
  src/main/pages/che-7/extensions/che4z-release-information.adoc
Labels: status/code-review

#940 Update che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#941 Update che4z-release-information.adoc
  src/main/pages/che-7/extensions/che4z-release-information.adoc
Labels: status/code-review

#931 Upgrade che with cli
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che-on-openshift-4-using-the-openshift-web-console.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-from-che-6-to-che-7-on-openshift-4-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_finishing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-3-using-the-cli-management-tool.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-4-using-the-cli-management-tool.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-for-installing-che.adoc
Labels: status/code-review

#929 Uninstalling the Che instance
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/uninstall/che-delete-che-cluster.png
  src/main/images/uninstall/che-uninstall-operator.png
  src/main/pages/che-7/administration-guide/assembly_removing-user-data.adoc
  src/main/pages/che-7/installation-guide/assembly_uninstalling-che.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-chectl-installation.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
Labels: status/code-review

#943 remove a debug statement
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
Labels: status/code-review

#944 Document Route/Ingress accessability in restricted netowrk environments
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
Labels: kind/bug, status/code-review

#945 Add Preview URL preferences documentation
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#946 Improvements.
  src/main/pages/che-7/end-user-guide/assembly_version-control.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_managing-git-configuration-identity.adoc
  src/main/pages/che-7/end-user-guide/proc_managing-gitconfiguration.adoc
Labels: status/code-review, target/branch

#947 fix btn:[]
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
Labels: kind/bug, status/code-review

#927 Add user docs about configuration Git Identity
  src/main/images/git/git-config-identity.png
  src/main/images/git/terminal-git-command.png
  src/main/pages/che-7/end-user-guide/assembly_version-control.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_managing-git-configuration-identity.adoc
Labels: kind/enhancement, status/code-review

#949 Remove unnecessary link.
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
Labels: status/code-review

#936 Git self sign
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
Labels: status/code-review

#948 Describe how to allow user-defined workspace namespaces.
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: status/code-review

#950 Shortening reference to OpenShift
  src/main/pages/che-7/end-user-guide/assembly_navigating-che-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_navigating-che-using-the-dashboard-on-minishift.adoc
  src/main/pages/che-7/end-user-guide/proc_navigating-che-using-the-dashboard-on-openshift.adoc
  src/main/pages/che-7/overview/proc_navigating-che-using-the-dashboard-on-ocp-and-osd.adoc
Labels: status/code-review

#951 RELEASE: Set next development version
  pom.xml
Labels: status/code-review
