Repository eclipse-che/che-docs, pull requests merged in 2020-09, with the labels that each got.

#1509 Replace image from che.openshift.io/factory/resources with image from https://raw.githubusercontent.com/eclipse/che/assets
  README.md
  modules/contributor-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/partials/proc_using-a-badge-to-link-to-workspaces.adoc
Labels: kind/bug, status/code-review

#1511 Replacing attribute for xrefs, fix in attribute
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/proc_enabling-metrics-collection.adoc
Labels: kind/bug, status/code-review

#1510 Cleanup after Antora migration
  CONTRIBUTING.adoc
  CONTRIBUTION.md
  Dockerfile
  README-antora.adoc
  TODO
  build-docker-image.sh
  proc_upgrading-a-local-installation-of-antora.adoc
  tools/antora-migration/README.adoc
  tools/antora-migration/TODO.adoc
  tools/antora-migration/aliases.yaml
  tools/antora-migration/antora-substitutions.sed
  tools/antora-migration/filesmap.sed
  tools/antora-migration/filesmap.yaml
  tools/antora-migration/migrate.sh
  tools/antora-migration/nav.j2
  tools/antora-migration/page.j2
  tools/antora-migration/pagesvars-administration-guide.yaml
  tools/antora-migration/pagesvars-contributor-guide.yaml
  tools/antora-migration/pagesvars-end-user-guide.yaml
  tools/antora-migration/pagesvars-extensions.yaml
  tools/antora-migration/pagesvars-installation-guide.yaml
  tools/antora-migration/pagesvars-overview.yaml
  tools/antora-migration/pagesvars.j2
  tools/antora-migration/pagesvars.yaml
  tools/antora-migration/substitutions-xref-administration-guide.sed
  tools/antora-migration/substitutions-xref-contributor-guide.sed
  tools/antora-migration/substitutions-xref-end-user-guide.sed
  tools/antora-migration/substitutions-xref-extensions.sed
  tools/antora-migration/substitutions-xref-installation-guide.sed
  tools/antora-migration/substitutions-xref-overview.sed
  tools/antora-migration/substitutions-xref.sed
  tools/antora-migration/substitutions.sed
Labels: status/code-review

#1512 Fix xrefs in Tracing Che
  modules/administration-guide/partials/proc_enabling-metrics-collection.adoc
  modules/administration-guide/partials/proc_installing-jaeger-using-cli-on-openshift-4.adoc
  modules/administration-guide/partials/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
Labels: kind/bug, status/code-review

#1513 assembly -> procedure
  modules/end-user-guide/pages/configuring-github-oauth.adoc
  modules/end-user-guide/pages/configuring-openshift-oauth.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/partials/proc_configuring-openshift-oauth.adoc
Labels: status/code-review

#1515 Fix xrefs
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-code-sample.adoc
Labels: kind/bug, status/code-review

#1516 Fix metadata
  modules/overview/partials/assembly_using-the-chectl-management-tool.adoc
Labels: kind/bug, status/code-review

#1517 Add the 'experimental' attribute.
  antora.yml
Labels: kind/bug, kind/docs, status/code-review

#1518 Che contribute badges should use https://www.eclipse.org/che/contribute.svg
  README.md
  modules/contributor-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/partials/proc_using-a-badge-to-link-to-workspaces.adoc
Labels: status/code-review

#1519 Misc. CSS fixes.
  supplemental-ui/css/extra.css
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, status/code-review

#1514 Small modification to the installation proc
  modules/overview/pages/installing-che-on-openshift-4-using-operatorhub.adoc
  modules/overview/partials/assembly_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  modules/overview/partials/proc_creating-a-project-in-openshift-web-console.adoc
  modules/overview/partials/proc_creating-an-instance-of-the-che-operator.adoc
  modules/overview/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  modules/overview/partials/proc_installing-the-che-operator.adoc
Labels: status/code-review

#1523 fix typo
  modules/end-user-guide/partials/proc_mounting-a-git-credential-store-into-a-workspace-container.adoc
Labels: kind/bug, status/code-review

#1526 Fix ID mismatch.
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
Labels: kind/bug, status/code-review

#1527 Fix links in uninstalling
  modules/installation-guide/partials/assembly_uninstalling-che.adoc
Labels: kind/bug, status/code-review

#1529 fix various links
  modules/administration-guide/partials/proc_deploying-image-puller-using-openshift-templates.adoc
  modules/administration-guide/partials/proc_viewing-che-metrics-on-grafana-dashboards.adoc
  modules/contributor-guide/partials/con_che-theia-plug-in-registries.adoc
  modules/contributor-guide/partials/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  modules/contributor-guide/partials/proc_adding-support-for-a-new-debugger.adoc
  modules/contributor-guide/partials/proc_adding-support-for-a-new-language.adoc
  modules/contributor-guide/partials/proc_sharing-your-che-theia-plug-in-with-a-factory.adoc
  modules/end-user-guide/partials/proc_accessing-a-git-repository-via-ssh.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-user-dashboard-get-started.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-user-dashboard.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  modules/end-user-guide/partials/proc_overriding-devfile-values-using-factory-parameters.adoc
  modules/end-user-guide/partials/proc_starting-a-che-workspace-in-debug-mode.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
  modules/extensions/partials/proc_creating-components-with-openshift-connector-in-che.adoc
  modules/extensions/partials/proc_installing-openshift-connector-in-che.adoc
Labels: kind/bug, status/code-review

#1531 Cleanup an old xref
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: status/code-review

#1525 Remove unused CI files. We don't use ant anymore.
  .ci/cico_build.sh
  .ci/cico_build_nightly.sh
  .ci/cico_build_release.sh
  .ci/cico_common.sh
  pom.xml
  tools/environment_docs_gen.sh
Labels: status/code-review

#1533 Attributes for che-server in xrefs
  modules/administration-guide/pages/viewing-che-server-logs.adoc
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/assembly_retrieving-che-logs.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/proc_configuring-prod-short-to-use-external-keycloak.adoc
  modules/administration-guide/partials/proc_enabling-metrics-collection.adoc
  modules/administration-guide/partials/proc_viewing-keycloak-server-logs.adoc
  modules/administration-guide/partials/proc_viewing-postgresql-server-logs.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/installation-guide/partials/assembly_configuring-che-overview.adoc
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
Labels: status/code-review

#1534 Add menu entries for Uninstalling Che
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/uninstalling-che-after-chectl-installation.adoc
  modules/installation-guide/pages/uninstalling-che-after-operatorhub-installation-using-openshift-cli.adoc
  modules/installation-guide/pages/uninstalling-che-after-operatorhub-installation-using-openshift-web-console.adoc
  modules/installation-guide/partials/assembly_uninstalling-che.adoc
Labels: kind/enhancement, status/code-review

#1535 Add lost attributes.
  antora.yml
Labels: kind/enhancement, status/code-review

#1532 EuG usptream batch
  modules/end-user-guide/partials/con_a-minimal-devfile.adoc
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
  modules/end-user-guide/partials/con_what-is-a-devfile.adoc
  modules/end-user-guide/partials/proc_generating-workspace-names.adoc
  modules/end-user-guide/partials/proc_managing-git-configuration-identity.adoc
Labels: status/code-review

#1536 Overview page for Navigating Che
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/navigating-che.adoc
  modules/end-user-guide/partials/assembly_navigating-che.adoc
Labels: status/code-review

#1539 Consistent naming for self-signed-certificates metadata
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/accessing-che-from-openshift-developer-perspective.adoc
  modules/end-user-guide/pages/importing-certificates-to-browsers.adoc
  modules/end-user-guide/pages/importing-self-signed-certificates-to-browsers.adoc
  modules/end-user-guide/partials/assembly_importing-self-signed-certificates-to-browsers.adoc
  modules/end-user-guide/partials/proc_importing-self-signed-certificates-to-browsers.adoc
  modules/installation-guide/partials/assembly_installing-che-on-codeready-containers.adoc
  modules/installation-guide/partials/assembly_installing-che-on-docker-desktop.adoc
  modules/installation-guide/partials/assembly_installing-che-on-kind.adoc
  modules/installation-guide/partials/assembly_installing-che-on-minikube.adoc
  modules/installation-guide/partials/assembly_installing-che-on-minishift.adoc
  modules/installation-guide/partials/proc_adding-self-signed-certs-to-minishift.adoc
  modules/installation-guide/partials/proc_generating-self-signed-tls-certificates.adoc
Labels: status/code-review

#1545 fix xref
  modules/end-user-guide/partials/assembly_navigating-che.adoc
Labels: kind/bug, status/code-review

#1546 Fixing GCP installation procedure
  modules/installation-guide/partials/proc_installing-cert-manager-on-kubernetes.adoc
Labels: kind/bug, status/code-review

#1547 Fix context setting in Navigating Che
  modules/end-user-guide/partials/assembly_navigating-che.adoc
Labels: kind/bug, status/code-review

#1548 Use directly procedure instead of an empty assembly
  modules/end-user-guide/pages/importing-self-signed-certificates-to-browsers.adoc
  modules/end-user-guide/partials/assembly_importing-self-signed-certificates-to-browsers.adoc
  modules/end-user-guide/partials/proc_importing-self-signed-certificates-to-browsers.adoc
Labels: status/code-review

#1549 Fix broken endif::[]
  modules/end-user-guide/partials/proc_accessing-workspaces-remotely-using-kubectl.adoc
Labels: kind/bug, status/code-review

#1550 Update ig
  modules/installation-guide/partials/proc_creating-a-project-in-openshift-web-console.adoc
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  modules/installation-guide/partials/ref_checluster-custom-resource-fields-reference.adoc
Labels: kind/enhancement, status/code-review

#1552 Consistency for che-architecture-overview
  modules/administration-guide/pages/che-architecture-overview.adoc
  modules/administration-guide/partials/con_che-architecture-overview.adoc
  modules/overview/pages/che-architecture.adoc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: status/code-review

#1555 xref to filename should not contain attributes
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/assembly_retrieving-che-logs.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/proc_enabling-metrics-collection.adoc
  modules/administration-guide/partials/proc_viewing-keycloak-server-logs.adoc
  modules/administration-guide/partials/proc_viewing-postgresql-server-logs.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/installation-guide/partials/assembly_configuring-che-overview.adoc
Labels: status/code-review

#1556 AG sanity check Upstream
  modules/administration-guide/partials/assembly_authenticating-users.adoc
  modules/administration-guide/partials/assembly_removing-user-data.adoc
  modules/administration-guide/partials/proc_adding-a-devfile-at-runtime.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-with-keycloak.adoc
Labels: status/code-review

#1528 Reordering chapters in Installation Guide
  modules/end-user-guide/nav.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/advanced-configuration.adoc
  modules/installation-guide/pages/configuring-che.adoc
  modules/installation-guide/pages/configuring-the-che-installation.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
Labels: status/code-review

#1559 Update generated file system-variables.adoc
  modules/installation-guide/examples/system-variables.adoc
Labels: kind/enhancement, status/code-review

#1554 Prevent non-attributes from rendering as attributes.
  modules/administration-guide/partials/con_persistent-volume-configuration.adoc
  modules/administration-guide/partials/proc_adding-a-devfile-at-runtime.adoc
  modules/administration-guide/partials/proc_adding-a-plug-in-at-runtime.adoc
  modules/end-user-guide/partials/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
Labels: status/code-review

#1561 che #17404 Updating Hosted Che terms of service. Adding info about maximum time for a running workspace
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: kind/task, status/code-review

#1562 Prevent fake attributes from rendering.
  modules/administration-guide/partials/proc_adding-a-devfile-at-runtime.adoc
  modules/administration-guide/partials/proc_adding-a-plug-in-at-runtime.adoc
  modules/administration-guide/partials/proc_installing-jaeger-using-cli-on-openshift-4.adoc
  modules/administration-guide/partials/proc_testing-the-vs-code-extension-using-gist.adoc
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_generating-self-signed-certificates.adoc
Labels: status/code-review

#1563 Non attr 2
  modules/administration-guide/partials/assembly_removing-user-data.adoc
  modules/administration-guide/partials/proc_adding-a-plug-in-at-runtime.adoc
  modules/installation-guide/partials/assembly_installing-che.adoc
Labels: status/code-review

#1521 Move configuring workspace exposure strategies page into installation guide
  modules/end-user-guide/nav.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/configuring-workspace-exposure-strategies.adoc
  modules/installation-guide/partials/assembly_configuring-workspace-exposure-strategies.adoc
  modules/installation-guide/partials/con_security-considerations.adoc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: kind/bug, status/code-review

#1565 Provide more specific information for certificate handling
  modules/end-user-guide/partials/proc_importing-certificates-to-browsers.adoc
Labels: status/code-review

#1564 Vitali's feedback
  modules/installation-guide/partials/assembly_configuring-workspace-exposure-strategies.adoc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
Labels: status/code-review

#1415 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/enhancement, status/code-review

#1568 Make Installation Guide more downstream friendly: metadata consistenc…
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/installing-che-in-cloud.adoc
  modules/installation-guide/pages/installing-che-on-openshift-4-using-operatorhub.adoc
  modules/installation-guide/partials/assembly_installing-che-in-cloud.adoc
  modules/installation-guide/partials/assembly_installing-che-on-openshift-4-using-operatorhub.adoc
  modules/installation-guide/partials/assembly_installing-che.adoc
Labels: status/code-review

#1567 Fix typo in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/bug, status/code-review

#1569 Fix an include
  modules/installation-guide/partials/proc_creating-an-instance-of-the-che-operator.adoc
Labels: kind/bug, status/code-review

#1573 The name of the guide in unncessary in this include statement.
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review

#1570 Update version.
  antora.yml
Labels: kind/bug, status/code-review

#1571 Fix wording/readability in adding plugins to workspace
  antora.yml
  modules/end-user-guide/partials/assembly_adding-tools-to-che-after-creating-a-workspace.adoc
  modules/end-user-guide/partials/con_additional-tools-in-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
Labels: kind/bug, status/code-review

#1575 Fix hosted che factory link in contributing guide
  CONTRIBUTING.adoc
Labels: kind/bug, status/code-review

#1576 Add `mergePlugins` to attributes in devfile reference and fix minor issues in doc
  modules/end-user-guide/partials/proc_configuring-the-workspace-and-adding-tooling.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: status/code-review

#1577 chore(github): fix PR template typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/bug, status/code-review

#1578 fix(doc) replace wsmaster by {prod-short} server
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_che-workspace-creation-flow.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-lifecycle.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/system-variables.adoc
Labels: kind/task, status/code-review

#1583 chore(netlify): Allow to deploy each PR to netlify and add result in PR status
  .github/workflows/netlify.yaml
Labels: status/code-review

#1581 Remove leftovers of known-issues.
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/upgrading-che-known-issues.adoc
  modules/installation-guide/pages/upgrading-che.adoc
  modules/installation-guide/partials/ref_upgrading-che-known-issues.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: need-cherry-pick/7.18.x, status/code-review

#1572 [Do not merge] Add installation instructions for gateway single host mode
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: kind/enhancement, status/code-review

#1588 chore(netlify): use another kind of event to get secret from fork
  .github/workflows/netlify.yaml
Labels: status/code-review

#1584 Update steps in IG.
  modules/installation-guide/partials/proc_creating-a-project-in-openshift-web-console.adoc
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  modules/installation-guide/partials/proc_installing-the-che-operator.adoc
Labels: kind/enhancement, status/code-review

#1586 Script for preview in antora container, used by devfile and podman
  .gitignore
  build/.placeholder
  devfile.yaml
  tools/linkchecker.sh
  tools/podmanpreview.sh
  tools/preview.sh
Labels: status/code-review

#1594 Adding Vale vocabulary. Need vale 2.3
  .vale.ini
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
Labels: kind/enhancement, status/code-review

#1587 Fix xref for defining entrypoints in devfile reference
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: kind/bug, need-cherry-pick/7.18.x, status/code-review

#1596 Don't publish devfile 2 specs in che-docs
  antora-playbook.yml
Labels: status/code-review

#1597 fix broken link.
  linkcheckerrc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
Labels: kind/bug, need-cherry-pick/7.18.x, status/code-review

#1585 Adding a new procedure for restricted env. - waiting on review
  antora.yml
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/pulling-images-used-by-che-to-a-private-registry.adoc
  modules/installation-guide/pages/upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  yarn.lock
Labels: kind/enhancement, need-cherry-pick/7.18.x, status/code-review

#1599 adding a new procedure for restricted env - cherry-pick
  antora.yml
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/pulling-images-used-by-che-to-a-private-registry.adoc
  modules/installation-guide/pages/upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  yarn.lock
Labels: kind/enhancement, status/code-review, target/branch

#1601 chore(pr-check): validate links by linkchecker
  .github/workflows/link-checker.yaml
Labels: kind/task, status/code-review

#1600 chore(pr-check): Add vale PR check
  .github/workflows/vale.yaml
Labels: kind/task, status/code-review

#1604 adding note for the installation step
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool.adoc
Labels: kind/enhancement, status/code-review

#1566 Add the prerequisite and format a procedure.
  modules/end-user-guide/partials/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
Labels: kind/enhancement, need-cherry-pick/7.18.x, status/code-review

#1607 Cherry pick
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/upgrading-che-known-issues.adoc
  modules/installation-guide/pages/upgrading-che.adoc
  modules/installation-guide/partials/ref_upgrading-che-known-issues.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: status/code-review, target/branch

#1611 antora-playbook-unbranded.yml
  .gitignore
  antora-playbook-unbranded.yml
  antora.yml
Labels: status/code-review

#1612 Reorganize styles into CheDocs,IBM
  .vale.ini
  .vale/styles/CheDocs/SentenceLength.yml
  .vale/styles/IBM/Annotations.yml
  .vale/styles/IBM/Foreign.yml
  .vale/styles/IBM/HeadingPunctuation.yml
  .vale/styles/IBM/README-proselint.md
  .vale/styles/IBM/README-write-good.md
  .vale/styles/IBM/Slash.yml
  .vale/styles/IBM/Spacing.yml
  .vale/styles/IBM/Spelling.yml
  .vale/styles/IBM/ThereIs.yml
  .vale/styles/IBM/Very.yml
  .vale/styles/IBM/Wordiness.yml
  .vale/styles/IBM/Words.yml
Labels: status/code-review

#1613 Improve installing on Minikube docs
  modules/installation-guide/partials/proc_installing-che-on-minikube-using-chectl.adoc
  modules/installation-guide/partials/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: kind/bug, status/code-review

#1614 Fix Upgrading Che in restricted environment
  antora-playbook.yml
  modules/installation-guide/examples/che-assembly_installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/examples/che-con_understanding-network-connectivity-in-restricted-environments.adoc
  modules/installation-guide/examples/che-proc_building-an-offline-devfile-registry-image.adoc
  modules/installation-guide/examples/che-proc_building-an-offline-plug-in-registry-image.adoc
  modules/installation-guide/examples/che-proc_configuring-che-to-run-in-a-restricted-environment.adoc
  modules/installation-guide/examples/che-proc_preparing-a-private-registry.adoc
  modules/installation-guide/pages/installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/pages/pulling-images-used-by-che-to-a-private-registry.adoc
  modules/installation-guide/pages/upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/assembly_installing-che-in-restricted-environment.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/assembly_upgrading-che.adoc
  modules/installation-guide/partials/con_network-connectivity-in-restricted-environments.adoc
  modules/installation-guide/partials/proc_building-offline-versions-of-the-plug-in-and-devfile-registries.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
Labels: kind/bug, status/code-review

#1615 Small fixes.
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/assembly_che-workspaces-architecture.adoc
  modules/administration-guide/partials/assembly_customizing-the-devfile-and-plug-in-registries.adoc
  modules/administration-guide/partials/assembly_removing-user-data.adoc
  modules/administration-guide/partials/con_che-devfile-registry.adoc
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry.adoc
  modules/administration-guide/partials/proc_viewing-postgresql-server-logs.adoc
  modules/administration-guide/partials/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
Labels: kind/bug, status/code-review

#1616 Fix an external link
  modules/administration-guide/partials/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  modules/installation-guide/partials/con_understanding-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: cherry-picked to 7.18.x, kind/bug, status/code-review

#1610 Add section to configure labels
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/configuring-labels-for-ingresses.adoc
  modules/installation-guide/pages/configuring-labels-for-routes.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_configuring-labels-for-ingresses.adoc
  modules/installation-guide/partials/proc_configuring-labels-for-routes.adoc
Labels: kind/enhancement, status/code-review
