Repository eclipse-che/che-docs, pull requests merged in 2020-10, with the labels that each got.

#1617 docs for single-host devfile endpoins exposure on subdomains
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
Labels: kind/task, status/code-review

#1618 Replace hardcoded instances of identity provider with an attr.
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/ref_checluster-custom-resource-fields-reference.adoc
Labels: status/code-review

#1606 [GDPR] delete all the data related to user account from keycloak
  modules/administration-guide/partials/assembly_removing-user-data.adoc
Labels: kind/enhancement, kind/task, status/code-review

#1603 Configuring Che installation on GCP
  modules/installation-guide/images/installation/gcp-new-nodepool-select-machine-type-standard.png
  modules/installation-guide/images/installation/gcp-new-nodepool.png
  modules/installation-guide/partials/assembly_configuring-che-on-google-cloud-platform.adoc
  modules/installation-guide/partials/assembly_installing-che-on-google-cloud-platform.adoc
  modules/installation-guide/partials/proc_configuring-the-che-operator-checluster-resource-with-kubectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  modules/installation-guide/partials/proc_sizing-google-cloud-node-pools-for-your-eclipse-che-workspaces.adoc
Labels: status/code-review

#1621 Installing Che: link to Hosted Che, alias for quick-starts
  modules/hosted-che/pages/hosted-che.adoc
  modules/installation-guide/pages/installing-che.adoc
  modules/installation-guide/partials/assembly_installing-che.adoc
Labels: status/code-review

#1622 Add a note about the limitation on paths with secure endpoints to the devfile reference
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: status/code-review

#1623 document subdomain plugin endpoint
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: kind/enhancement, status/code-review

#1626 Fix che/issues/#16681: add link to npm section
  modules/end-user-guide/partials/assembly_using-artifact-repositories-in-a-restricted-environment.adoc
Labels: kind/bug, status/code-review

#1625 Update the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status/code-review

#1629 Remove obsolete steps. Fixes eclipse/che/issues/17687
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: kind/bug, status/code-review

#1627 Fixing and udpating the GDPR procedure
  antora-playbook.yml
  modules/administration-guide/pages/removing-user-data.adoc
  modules/administration-guide/partials/assembly_removing-user-data.adoc
  modules/administration-guide/partials/proc_removing-user-data.adoc
Labels: kind/enhancement, status/code-review

#1630 Gdpr cherry pick
  antora-playbook.yml
  modules/administration-guide/pages/removing-user-data.adoc
  modules/administration-guide/partials/assembly_removing-user-data.adoc
  modules/administration-guide/partials/proc_removing-user-data.adoc
Labels: status/code-review, target/branch

#1633 Move "Customizing the registries" to the Contributor guide
  modules/administration-guide/examples/che-build-the-devfile-registry.adoc
  modules/administration-guide/examples/che-clone-the-devfile-registry-repository.adoc
  modules/administration-guide/examples/che-clone-the-plug-in-registry-repository.adoc
  modules/administration-guide/examples/proc_che-including-the-plug-in-binaries-in-the-registry-image.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/building-and-running-a-custom-registry-image.adoc
  modules/administration-guide/pages/customizing-the-devfile-and-plug-in-registries.adoc
  modules/administration-guide/pages/including-the-plug-in-binaries-in-the-registry-image.adoc
  modules/administration-guide/pages/using-a-visual-studio-code-extension-in-che.adoc
  modules/administration-guide/partials/assembly_customizing-the-devfile-and-plug-in-registries.adoc
  modules/administration-guide/partials/assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc
  modules/administration-guide/partials/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  modules/contributor-guide/examples/che-devfile-meta.adoc
  modules/contributor-guide/examples/snip_customizing-the-devfile-registry.adoc
  modules/contributor-guide/examples/snip_customizing-the-plug-in-registry.adoc
  modules/contributor-guide/images/customization/che-deploying-plugin-registry-in-kubernetes.png
  modules/contributor-guide/images/customization/deploying-devfile-registry-in-kubernetes.png
  modules/contributor-guide/nav.adoc
  modules/contributor-guide/pages/building-a-custom-devfile-registry.adoc
  modules/contributor-guide/pages/building-a-custom-plug-in-registry.adoc
  modules/contributor-guide/pages/customizing-the-devfile-and-plug-in-registries.adoc
  modules/contributor-guide/pages/running-custom-registries.adoc
  modules/contributor-guide/pages/testing-a-visual-studio-code-extension-in-che.adoc
  modules/contributor-guide/partials/assembly_building-and-running-a-custom-registry-image.adoc
  modules/contributor-guide/partials/assembly_customizing-the-registries.adoc
  modules/contributor-guide/partials/assembly_deploying-the-registries.adoc
  modules/contributor-guide/partials/assembly_testing-a-visual-studio-code-extension-in-che.adoc
  modules/contributor-guide/partials/assembly_using-a-visual-studio-code-extension-in-che.adoc
  modules/contributor-guide/partials/proc_deploying-registries-in-kubernetes.adoc
  modules/contributor-guide/partials/proc_deploying-registries-in-openshift.adoc
  modules/contributor-guide/partials/proc_testing-the-vs-code-extension-using-gist.adoc
  modules/contributor-guide/partials/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/adding-a-vs-code-extension-to-a-workspace.adoc
  modules/end-user-guide/pages/editing-a-devfile-and-plug-in-at-runtime.adoc
  modules/end-user-guide/pages/publishing-metadata-for-a-vs-code-extension.adoc
  modules/end-user-guide/partials/assembly_adding-a-vs-code-extension-to-a-workspace.adoc
  modules/end-user-guide/partials/assembly_editing-a-devfile-and-plug-in-at-runtime.adoc
  modules/end-user-guide/partials/proc_adding-a-devfile-at-runtime.adoc
  modules/end-user-guide/partials/proc_adding-a-plug-in-at-runtime.adoc
  modules/end-user-guide/partials/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  modules/end-user-guide/partials/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  modules/end-user-guide/partials/proc_publishing-metadata-for-a-vs-code-extension.adoc
  modules/installation-guide/examples/assembly_che-installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/examples/che-proc_building-an-offline-devfile-registry-image.adoc
  modules/installation-guide/examples/che-proc_building-an-offline-plug-in-registry-image.adoc
  modules/installation-guide/examples/con_che-understanding-network-connectivity-in-restricted-environments.adoc
  modules/installation-guide/examples/proc_che-building-a-registry-image.adoc
  modules/installation-guide/examples/proc_che-configuring-che-to-run-in-a-restricted-environment.adoc
  modules/installation-guide/examples/proc_che-preparing-a-private-registry.adoc
  modules/installation-guide/examples/ref_che-supported-platforms-and-installation-methods.adoc
  modules/installation-guide/examples/ref_che-understanding-the-registries.adoc
  modules/installation-guide/examples/snip_che-build-a-registry.adoc
  modules/installation-guide/examples/snip_che-clone-the-registry-repository.adoc
  modules/installation-guide/pages/installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/con_supported-platforms.adoc
Labels: status/code-review

#1634 Fix missing id and broken xref
  modules/end-user-guide/partials/proc_configuring-the-workspace-and-adding-tooling.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: cherry-picked to 7.20.x, kind/bug, status/code-review

#1635 Make sure URLs prod-url attribute are not rendered as links
  antora-playbook.yml
Labels: status/code-review

#1637 Fix links. Unify xrefs into Additional resources section
  modules/administration-guide/partials/assembly_che-workspace-controller.adoc
  modules/administration-guide/partials/con_che-devfile-registry.adoc
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_che-workspace-controller.adoc
Labels: kind/bug, status/code-review

#1639 Mighty Fabricio catch
  modules/administration-guide/examples/che-prepulled-images-table.adoc
Labels: status/code-review

#1641 che #17472 Adding troubleshooting note about the fact that third-party cookies should be explicitly allowed in the incognito mode on Hosted Che
  modules/hosted-che/images/hosted-che/unblock_third_party_cookies.png
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: kind/bug, status/code-review

#1640 Fix duplicate ID, modularize, language fixes
  modules/administration-guide/pages/che-workspace-controller.adoc
  modules/administration-guide/pages/che-workspaces-architecture.adoc
  modules/administration-guide/partials/assembly_understanding-che-workspace-controller.adoc
  modules/administration-guide/partials/assembly_understanding-che-workspaces-architecture.adoc
  modules/administration-guide/partials/con_che-editor-plug-in.adoc
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/administration-guide/partials/con_che-workspaces-architecture.adoc
Labels: kind/bug, status/code-review

#1642 fixup! making wording in Hosted Che docs vale compatible
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: kind/bug, status/code-review

#1619 Fix identity provider section.
  antora-playbook.yml
  antora.yml
  modules/administration-guide/examples/proc_che-managing-users-using-identity-provider.adoc
  modules/administration-guide/examples/proc_che-setting-up-user-federation.adoc
  modules/administration-guide/partials/assembly_authenticating-users.adoc
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/con_authorization-and-user-management.adoc
  modules/administration-guide/partials/con_che-keycloak.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/proc_configuring-che-to-use-external-identity-provider.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-with-identity-provider.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-with-keycloak.adoc
  modules/administration-guide/partials/proc_configuring-identity-provider-tokens.adoc
  modules/administration-guide/partials/proc_configuring-prod-short-to-use-external-keycloak.adoc
  modules/administration-guide/partials/proc_managing-users-using-keycloak.adoc
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, need-cherry-pick/7.18.x, status/code-review

#1645 Remove Let's Encrypt reference.
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.18.x, need-cherry-pick/7.20.x, status/code-review

#1624 Deprecate server:start command
  modules/administration-guide/partials/assembly_collecting-logs-using-chectl.adoc
  modules/administration-guide/partials/con_authentication-modes.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-without-identity-provider.adoc
  modules/end-user-guide/partials/proc_configuring-openshift-oauth.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  modules/installation-guide/partials/proc_installing-che-on-azure-using-the-chectl-command.adoc
  modules/installation-guide/partials/proc_installing-che-on-codeready-containers-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-kind-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubespray-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-minikube-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-minishift-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
  modules/installation-guide/partials/proc_installing-che-using-storage-classes.adoc
Labels: status/code-review

#1628 Ensure users can run more than one workspace
  modules/administration-guide/examples/che-pvc-strategies.adoc
  modules/administration-guide/partials/con_persistent-volume-configuration.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/running-more-than-one-workspace-at-a-time.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
Labels: kind/enhancement, status/code-review

#1644 Add conditionals around URLs that lead to source code of the images.
  modules/administration-guide/partials/con_che-devfile-registry.adoc
  modules/administration-guide/partials/con_che-keycloak.adoc
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/administration-guide/partials/con_che-postgresql.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_che-user-dashboard.adoc
Labels: kind/enhancement, status/code-review

#1643 document pre-created namespaces with labels
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/task, status/code-review

#1652 xref fix
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review

#1636 Add two new sections to the telemetry documentation
  modules/extensions/nav.adoc
  modules/extensions/pages/creating-a-telemetry-plugin.adoc
  modules/extensions/pages/telemetry.adoc
  modules/extensions/pages/the-woopra-telemetry-plugin.adoc
  modules/extensions/partials/assembly_telemetry-overview.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
  modules/extensions/partials/ref_the-woopra-telemetry-plugin.adoc
Labels: status/code-review

#1653 fix <userid> placeholder name
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review

#1647 Refactor python pip config
  modules/end-user-guide/examples/che-python-configure-pip.adoc
  modules/end-user-guide/examples/che-python-use-self-signed-cert.adoc
  modules/end-user-guide/partials/proc_configuring-python-to-use-a-non-standard-registry.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-python-projects.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1649 Extract goproxy config to examples
  modules/end-user-guide/examples/che-go-configure-goproxy.adoc
  modules/end-user-guide/examples/che-go-use-self-signed-cert.adoc
  modules/end-user-guide/partials/proc_configuring-go-to-use-a-non-standard-registry.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-go-projects.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1651 Add note about normalizing usernames if it did not match K8S naming format
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/enhancement, status/code-review

#1655 Update CONTRIBUTING.adoc with docs workflow
  CONTRIBUTING.adoc
Labels: kind/enhancement, status/code-review

#1646 Move Customizing the registries back to the Administration Guide
  antora-playbook.yml
  modules/administration-guide/examples/assembly_che-building-custom-registry-images.adoc
  modules/administration-guide/examples/snip_che-devfile-meta.adoc
  modules/administration-guide/examples/snip_che-plug-in-tree.adoc
  modules/administration-guide/examples/snip_customizing-the-devfile-registry.adoc
  modules/administration-guide/examples/snip_customizing-the-plug-in-registry.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/building-custom-registry-images.adoc
  modules/administration-guide/pages/customizing-the-devfile-and-plug-in-registries.adoc
  modules/administration-guide/pages/running-custom-registries.adoc
  modules/administration-guide/partials/assembly_customizing-the-registries.adoc
  modules/administration-guide/partials/assembly_deploying-the-registries.adoc
  modules/administration-guide/partials/proc_deploying-registries-in-kubernetes.adoc
  modules/administration-guide/partials/proc_deploying-registries-in-openshift.adoc
  modules/contributor-guide/examples/snip_customizing-the-plug-in-registry.adoc
  modules/contributor-guide/nav.adoc
  modules/contributor-guide/pages/building-a-custom-devfile-registry.adoc
  modules/contributor-guide/pages/building-a-custom-plug-in-registry.adoc
  modules/contributor-guide/partials/assembly_building-and-running-a-custom-registry-image.adoc
  modules/contributor-guide/partials/assembly_customizing-the-registries.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/testing-a-visual-studio-code-extension-in-che.adoc
  modules/end-user-guide/partials/assembly_testing-a-visual-studio-code-extension-in-che.adoc
  modules/end-user-guide/partials/assembly_using-a-visual-studio-code-extension-in-che.adoc
  modules/end-user-guide/partials/proc_testing-the-vs-code-extension-using-gist.adoc
  modules/end-user-guide/partials/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  modules/installation-guide/examples/assembly_che-installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/examples/snip_che-building-offline-registry-images.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_building-a-registry-image.adoc
  modules/installation-guide/partials/ref_understanding-the-registries.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1659 update precreating namespaces changes
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review

#1661 Move uninstallation procedure to examples.
  modules/installation-guide/examples/proc_uninstalling-che-after-chectl-installation.adoc
  modules/installation-guide/pages/uninstalling-che-after-chectl-installation.adoc
Labels: status/code-review

#1662 Push to production on production branch
  Jenkinsfile
Labels: status/code-review

#1657 Fix PR generation to the wrong branch during the release
  make-release.sh
Labels: kind/bug, status/code-review

#1666 Add conditionals.
  modules/end-user-guide/partials/assembly_version-control.adoc
Labels: kind/enhancement, status/code-review

#1665 Publish from `master` again. Add a statement in CONTRIBUTING.adoc
  CONTRIBUTING.adoc
  Jenkinsfile
Labels: status/code-review

#1672 Move images
  modules/administration-guide/images/customization/che-deploying-plugin-registry-in-kubernetes.png
  modules/administration-guide/images/customization/deploying-devfile-registry-in-kubernetes.png
Labels: cherry-picked to 7.20.x, status/code-review

#1667 Fixes and updates for exposure strategies
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: kind/bug, kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1673 Fix xref in Installation Guide
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: cherry-picked to 7.20.x, kind/bug, status/code-review

#1674 fix example file name
  modules/installation-guide/examples/proc_che-uninstalling-che-after-chectl-installation.adoc
  modules/installation-guide/pages/uninstalling-che-after-chectl-installation.adoc
Labels: cherry-picked to 7.20.x, kind/bug, status/code-review

#1670 Update GitHub Pull Requests plugin documentation
  modules/end-user-guide/images/git/github-sign-in-notification.png
  modules/end-user-guide/partials/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
Labels: kind/enhancement, status/code-review

#1660 The paths are now allowed on secure endpoints.
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: status/code-review

#1682 Consistency for concepts titles, attributes for container image URLS
  antora-playbook.yml
  modules/administration-guide/partials/con_che-devfile-registry.adoc
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
Labels: cherry-picked to 7.20.x, status/code-review

#1654 document namespace name lenght limitation
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review
