Repository eclipse-che/che-docs, pull requests merged in 2020-04, with the labels that each got.

#1173 Fix context
  src/main/pages/che-7/administration-guide/assembly_configuring-authorization.adoc
  src/main/pages/che-7/administration-guide/assembly_managing-users.adoc
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/assembly_troubleshooting-for-che-administrators.adoc
  src/main/pages/che-7/administration-guide/assembly_using-organizations.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-server-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-workspaces-logs.adoc
  src/main/pages/che-7/administration-guide/con_external-database-setup.adoc
  src/main/pages/che-7/administration-guide/con_persistent-volumes-backups.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-kubernetes-events.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-plug-in-broker-logs.adoc
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1174 Automate deploy to Nexus during release
  .ci/cico_common.sh
Labels: kind/enhancement, status/code-review

#1179 Update the links to the CA Brightside doc in the Eclipse Che4z page
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
Labels: status/code-review

#1178 Restart workspace in debug mode after startup failure
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/troubleshooting/download_logs.png
  src/main/images/troubleshooting/run_workspace_in_debug_mode.png
  src/main/images/troubleshooting/starting_workspace_debug_logs.png
  src/main/images/troubleshooting/try_again_in_debug_mode.png
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-for-che-end-users.adoc
  src/main/pages/che-7/end-user-guide/proc_restarting-a-che-workspace-in-debug-mode-after-start-failure.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-che-workspace-in-debug-mode.adoc
Labels: kind/enhancement, status/code-review

#1187 Jekyll configuration: process only files with a front matter header.
  src/main/_config.yml
Labels: status/code-review

#1186 Backporting fixes
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-server-logs.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/con_che-editor-plug-in.adoc
Labels: kind/bug, status/code-review

#1189 backport fixes for 7.9.x, 2020-04-03
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-openshift.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/con_che-editor-plug-in.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review, target/branch

#1192 Backport fixes for master 2020 04 03
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
Labels: kind/bug, status/code-review

#1193 Fix navigation
  src/main/_data/sidebars/che_7_docs.yml
Labels: kind/bug, status/code-review

#1194 Apply ./tools/substitutions.sh
  src/main/pages/che-7/administration-guide/assembly_calculating-che-resource-requirements.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/administration-guide/con_external-database-setup.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/end-user-guide/assembly_adding-tools-to-che-after-creating-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: status/code-review

#1175 Fix SSL certificates generation steps
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_generating-self-signed-certificates.adoc
Labels: kind/docs, status/code-review

#1195 Update import CA certificate in browser section
  src/main/pages/che-7/contributor-guide/proc_che-usage-with-tls.adoc
Labels: kind/docs, status/code-review

#1197 Che 16366
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/contributor-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
  src/main/pages/che-7/contributor-guide/assembly_setup-che-in-tls-mode-with-self-signed-certificate.adoc
  src/main/pages/che-7/contributor-guide/proc_che-usage-with-tls.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploying-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploying-che-with-self-signed-tls-on-openhift3-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploying-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_generating-self-signed-certificates.adoc
  src/main/pages/che-7/contributor-guide/proc_using-che-with-tls.adoc
Labels: status/code-review

#1191 Fixup due to allowing volumes in kubernetes/openshift components
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#1185 Merge branch 'pr-master-to-7.11.1-SNAPSHOT' of github.com:eclipse/che-docs into pr-master-to-7.11.1-SNAPSHOT Merge branch 'pr-master-to-7.11.1-SNAPSHOT' of github.com:eclipse/che-docs into pr-master-to-7.11.1-SNAPSHOT
  pom.xml
Labels: status/code-review, target/branch

#1198 Add project context eval.
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.9, status/code-review

#1200 Fix prod id short in ids
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  src/main/pages/che-7/contributor-guide/proc_generating-self-signed-certificates.adoc
  src/main/pages/che-7/end-user-guide/assembly_adding-tools-to-che-after-creating-a-workspace.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_installing-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review

#1201 enviromnent_docs_gen.sh improvements
  tools/enviromnent_docs_gen.sh
Labels: status/code-review

#1184 Bump to 7.12.0-SNAPSHOT in master
  pom.xml
Labels: status/code-review

#1202 Context-specific procedure and verification steps for openshift-image-puller
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-kubernetes-image-puller-using-openshift-templates_prepare.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-kubernetes-image-puller-using-openshift-templates_process.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-kubernetes-image-puller-using-openshift-templates_verify-configmap.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
Labels: need-cherry-pick/7.9, status/code-review

#1160 Using different artifact repositories in a restricted environment
  .ci/vale/styles/vocab.txt
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/proc_using-npm-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-artifact-repositories-in-a-restricted-environment.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-go-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-gradle-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-maven-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-nuget-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-python-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-global-gradle-repositories.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-go-to-use-a-non-standard-registry.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-nuget-to-use-a-non-standard-registry.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-python-to-use-a-non-standard-registry.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-maven-repositories-in-the-settings-xml-file.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-different-versions-of-gradle.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-go-projects.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-java-projects.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-nuget-projects.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-python-projects.adoc
Labels: status/code-review

#1204 Move proc_using-npm-artifact-repositories.adoc into end-user-guide
  src/main/pages/che-7/end-user-guide/proc_using-npm-artifact-repositories.adoc
Labels: need-cherry-pick/7.9, status/code-review

#1205 Fix parent-context-of-using-gradle-artifact-repositories
  src/main/pages/che-7/end-user-guide/assembly_using-gradle-artifact-repositories.adoc
Labels: need-cherry-pick/7.9

#1207 Remove attributes in attributes definitions
  src/main/pages/che-7/administration-guide/assembly_troubleshooting-for-che-administrators.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-workspaces-logs.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
Labels: need-cherry-pick/7.9, status/code-review

#1206 First IBM styles, small fixes
  .ci/vale/styles/IBM/README.md
  .ci/vale/styles/IBM/Usage.yml
  .ci/vale/styles/IBM/terms.yml
  .ci/vale/styles/PlainLanguage/PassiveVoice.yml
  .ci/vale/styles/vocab.txt
  .vale.ini
Labels: kind/bug, status/code-review

#1199 Align oauth documentation for to the delegated auth mode
  src/main/images/git/github-keycloak-setup.png
  src/main/images/git/github-provider-added.png
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
Labels: kind/enhancement, status/code-review

#1208 Redirect for db setup.
  src/main/pages/che-7/administration-guide/con_external-database-setup.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1209 Reviewing language according to the IBM styleguide.
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-traces-in-jaeger-ui.adoc
  src/main/pages/che-7/administration-guide/ref_che-tracing-codebase-overview-and-extension-guide.adoc
  src/main/pages/che-7/contributor-guide/assembly_testing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-registries.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-lifecycle.adoc
  src/main/pages/che-7/end-user-guide/con_disambiguation-between-stacks-and-devfiles.adoc
  src/main/pages/che-7/end-user-guide/con_embedded-and-remote-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/con_security-considerations.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-python-to-use-a-non-standard-registry.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-workspace-names.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-nuget-projects.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
  src/main/pages/che-7/overview/con_che-postgresql.adoc
  src/main/pages/che-7/overview/proc_creating-a-workspace-from-template-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/proc_using-minishift-to-set-up-openshift-3.adoc
Labels: status/code-review

#1210 Fix the command for creating a key for the GCP SA
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-google-cloud-platform.adoc
Labels: kind/bug, status/code-review

#1213 fix erroneous double slashes
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1214 close ifeval
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
Labels: need-cherry-pick/7.9, status/code-review

#1216 Remove tls from installation intructions.
  src/main/pages/che-7/administration-guide/examples/changing-default-variables.adoc
  src/main/pages/che-7/contributor-guide/proc_deploying-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploying-che-with-self-signed-tls-on-openhift3-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploying-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
Labels: need-cherry-pick/7.9, status/code-review

#1215 Removed the note about self-signed certs
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
Labels: kind/enhancement, need-cherry-pick/7.9, status/code-review

#1217 Introduced attribute for identity provider.
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/assembly_authenticating-in-a-che-workspace.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-keycloak-logs.adoc
  src/main/pages/che-7/administration-guide/con_authorization-and-user-management.adoc
  src/main/pages/che-7/administration-guide/con_workspace-jwt-token.adoc
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-oauth.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-other-authentication-implementations.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-che-to-work-with-keycloak.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-keycloak-tokens.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-smtp-and-email-notifications.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_managing-users-using-keycloak.adoc
  src/main/pages/che-7/administration-guide/proc_setting-up-user-federation.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
  src/main/pages/che-7/administration-guide/proc_using-swagger-or-rest-clients-to-execute-queries.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-keycloak-client-logs-on-firefox.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-keycloak-client-logs-on-google-chrome.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-keycloak-server-logs.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-with-and-without-keycloak.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-controller.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/con_che-keycloak.adoc
  src/main/pages/che-7/overview/con_che-postgresql.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
Labels: status/code-review

#1218 Allow CPU limits in dockerimage components
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#1220 Add ifevals.
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_setting-up-user-federation.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
Labels: kind/enhancement, status/code-review

#1221 Ready to merge: I1724 ibm style guide
  src/main/pages/che-7/administration-guide/assembly_authenticating-in-a-che-workspace.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-oauth.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-other-authentication-implementations.adoc
  src/main/pages/che-7/administration-guide/proc_detecting-memory-problems.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-camel-language-server.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-xml-language-server.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/proc_sharing-your-che-theia-plug-in-with-a-factory.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/con_factory-json-reference.adoc
  src/main/pages/che-7/end-user-guide/con_security-considerations.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  src/main/pages/che-7/end-user-guide/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-devfile-for-your-project.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_che-workspaces-architecture.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/con_che-workspace-creation-flow.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1219 Added shell exec to the command.
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1224 Image puller fixes
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/assembly_caching-images-for-faster-workspace-start.adoc
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_parameters.adoc
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_prepare.adoc
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_process.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-kubernetes-image-puller-using-openshift-templates_process.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
Labels: kind/bug, status/code-review

#1212 Alternate -> alternative
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1227 Note about OpenShift Connector log-in issue
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
Labels: status/code-review

#1226 I1813 workspace
  src/main/pages/che-7/administration-guide/proc_assigning-che-permissions.adoc
  src/main/pages/che-7/administration-guide/ref_che-tracing-codebase-overview-and-extension-guide.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: status/code-review

#1230 Fixes in PVC config.
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, status/code-review

#1229 Several fixes in Che on kind.
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, status/code-review

#1231 Fixes in Deploying Che w/ selfsigned Git repos.
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1203 kubernetes/openshift components endpoints
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#1232 Link to system variables.
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#1233 Specified the correct default strategy
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/examples/che-pvc-strategies.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1236 Remove Kubernetes
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
Labels: status/code-review

#1237 External PostgreSQL database need an external {identity-provider}.
  src/main/pages/che-7/administration-guide/con_external-database-setup.adoc
Labels: status/code-review

#1234 endpoints for chePlugin and cheEditor components
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#1235 Sys vars
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  tools/enviromnent_docs_gen.sh
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1239 Applying proper YAML notification
  src/main/pages/che-7/end-user-guide/assembly_using-artifact-repositories-in-a-restricted-environment.adoc
  src/main/pages/che-7/end-user-guide/proc_using-npm-artifact-repositories.adoc
Labels: status/code-review

#1240 che #16689 Adding a note about the minimal requirment of an image to be pre-pulled via kubernetes-image-puller
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
Labels: kind/task, status/code-review

#1242 che #16689 Adding a note about unsupported images that mount voulmes for pre-pulling via kubernetes-image-puller
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
Labels: status/code-review

#1245 fix checluster in oc commands
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
Labels: kind/bug, need-cherry-pick/7.9.x, status/code-review

#1243 Fix Allowing user-defined workspace namespaces.
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.9.x, status/code-review

#1244 Move clone procedure to a seperate file.
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_cloning-project.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1247 [release] bump master to 7.13.0-SNAPSHOT
  pom.xml
Labels: status/code-review

#1249 Refresh Codeowners
  .github/CODEOWNERS
Labels: status/code-review

#1241 Add example of array-type preferences
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#1246 Che/CRW branding+fixes+newAttribute
  src/main/_config.yml
  src/main/images/architecture/che-high-level.png
  src/main/images/architecture/che-workspaces-controllers.png
  src/main/images/architecture/che-workspaces.png
  src/main/pages/che-7/administration-guide/con_che-architectural-components.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-controller.adoc
  src/main/pages/che-7/overview/assembly_che-workspaces-architecture.adoc
  src/main/pages/che-7/overview/con_high-level-che-architecture.adoc
Labels: kind/bug, status/code-review

#1238 Lang fixes
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-plug-in-broker-logs.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/con_additional-tools-in-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/con_security-considerations.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minishift-using-chectl.adoc
Labels: kind/bug, need-cherry-pick/7.9.x, status/code-review

#1250 Added missing {context}
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/con_organizations-in-eclipse-che.adoc
  src/main/pages/che-7/administration-guide/con_roles-in-an-organization.adoc
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_parameters.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-smtp-and-email-notifications.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-logs-for-php-debug.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-alternative-ides-in-che.adoc
  src/main/pages/che-7/end-user-guide/con_factory-json-reference.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/ref_objects-supported-in-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/enhancement, status/code-review

#1254 Removing an unnecesary procedure step
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review

#1255 Fix typo in kubernetes image puller instructions
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_process.adoc
Labels: kind/bug, status/code-review

#1253 Reword the sentence.
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-java-projects.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1256 Removing an unnecesary procedure step
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review, target/branch

#1257 Remove Kubernetes.
  src/main/pages/che-7/administration-guide/assembly_caching-images-for-faster-workspace-start.adoc
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1258 Rename k8s-image-puller doc file.
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_verify-configmap.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.9.x, status/code-review
