Repository eclipse-che/che-docs, pull requests merged in 2020-07, with the labels that each got.

#1351 Many fixes
  linkcheckerrc
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_using-swagger-or-rest-clients-to-execute-queries.adoc
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-and-configuring-a-new-workspace.adoc
  src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-projects-to-your-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard-get-started.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-open-button.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-run-button.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-che-workspace-in-debug-mode.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-from-che-6-on-openshift-4-using-the-web-console.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, status/code-review

#1349 Fix broken links
  .gitignore
  linkcheckerrc
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/proc_configuring-prod-short-to-work-without-identity-provider.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-and-configuring-a-new-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/installation-guide/con_supported-platforms.adoc
  src/main/pages/che-7/installation-guide/examples/system-variables.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-3-using-the-cli-management-tool.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-4-using-the-cli-management-tool.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-bare-metal-using-kubespray.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/examples/che-pvc-strategies.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_using-codeready-containers-to-set-up-openshift-4.adoc
  src/main/pages/che-7/overview/proc_using-minishift-to-set-up-openshift-3.adoc
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#1350 Content + link mentions
  src/main/pages/che-7/administration-guide/assembly_authenticating-users.adoc
  src/main/pages/che-7/administration-guide/con_authentication-modes.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-controller.adoc
Labels: status/code-review

#1352 Add vale plug-in in devfile
  devfile.yaml
Labels: kind/enhancement, status/code-review

#1354 first batch
  src/main/pages/che-7/end-user-guide/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  src/main/pages/che-7/installation-guide/proc_mounting-custom-ssl-certificates-to-che-workspace-pods.adoc
Labels: status/code-review

#1359 Fix typo on {prod-short} attribute
  src/main/pages/che-7/administration-guide/proc_viewing-postgresql-server-logs.adoc
Labels: kind/bug, status/code-review

#1356 pointing on the correct example file
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
Labels: kind/bug, kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1360 Fix a broken link
  src/main/pages/che-7/administration-guide/proc_building-a-custom-devfile-registry.adoc
Labels: kind/bug, status/code-review

#1361 Remove nbsp
  src/main/pages/che-7/administration-guide/con_a-workspace-example.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/con_embedded-and-remote-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_navigating-che-using-the-dashboard-on-minishift.adoc
  src/main/pages/che-7/overview/assembly_hosted-che.adoc
  src/main/pages/che-7/overview/proc_contributing-to-github-projects-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_creating-a-workspace-from-template-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_creating-a-worskpace-from-the-user-dashboard.adoc
  src/main/pages/che-7/overview/proc_importing-projects-from-github-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_registering-to-hosted-che.adoc
  src/main/pages/che-7/overview/ref_about-hosted-che.adoc
Labels: status/code-review

#1358 fix converting a Che 6 workspace to a Che 7 devfile
  src/main/images/workspaces/add-custom-project.png
  src/main/images/workspaces/create-and-edit.png
  src/main/images/workspaces/create-and-open.png
  src/main/images/workspaces/create-custom-workspace.png
  src/main/images/workspaces/remove-default-project.png
  src/main/images/workspaces/revise-commands.png
  src/main/images/workspaces/update-default-project.png
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
Labels: kind/task, status/code-review

#1362 Add {prod-id-short} in links
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1363 Substitutions: script output and human revision
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/con_authentication-modes.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-prod-short-to-work-without-identity-provider.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-operator.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/con_additional-tools-in-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options-for-the-che-server-component.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/installation-guide/proc_mounting-custom-ssl-certificates-to-che-workspace-pods.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-from-che-6-on-openshift-4-using-the-web-console.adoc
  src/main/pages/che-7/installation-guide/ref_checluster-custom-resource-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_3-minutes-to-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_hosted-che.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-bare-metal-using-kubespray.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-codeready-containers.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-kind.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minishift.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/assembly_using-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/con_glossary.adoc
  src/main/pages/che-7/overview/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  src/main/pages/che-7/overview/proc_contributing-to-github-projects-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_creating-a-workspace-from-template-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_creating-a-worskpace-from-the-user-dashboard.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
  src/main/pages/che-7/overview/proc_importing-projects-from-github-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubespray-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_registering-to-hosted-che.adoc
  src/main/pages/che-7/overview/ref_about-hosted-che.adoc
  src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
  tools/substitutions.sed
Labels: status/code-review

#1367 Fix erroneous usage of undefined asciidoctor attributes
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: kind/bug, status/code-review

#1366 che #17338 Fixing the misleading procedure step for enabling metrics. Adding a note that metrics enabled by default when Eclipse Che is installed via the OperatorHub
  src/main/images/monitoring/monitoring-che-che-cluster-cr.png
  src/main/pages/che-7/administration-guide/proc_enabling-and-exposing-che-metrics.adoc
Labels: kind/enhancement, status/code-review

#1370 deactivate links
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
Labels: status/code-review

#1369 Removing an obsolete file (duplicate).
  src/main/pages/che-7/end-user-guide/assembly_creating-and-configuring-a-new-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
Labels: status/code-review

#1371 Introducing the orch-namespace attribute
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/con_authorization-and-user-management.adoc
  src/main/pages/che-7/administration-guide/con_super-privileged-mode.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-operator.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-openshift.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-maven-settings-xml-file-across-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-3.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-4.adoc
  src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-chectl-installation.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-from-che-6-on-openshift-4-using-the-web-console.adoc
  src/main/pages/che-7/installation-guide/ref_checluster-custom-resource-fields-reference.adoc
  src/main/pages/che-7/overview/con_che-plug-in-broker.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/con_workspaces-namespaces-configuration.adoc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-azure.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-storage-for-kubernetes.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
  tools/substitutions.sed
Labels: status/code-review

#1365 Merge instructions to install certificates on macOS
  src/main/pages/che-7/installation-guide/proc_importing-self-signed-tls-certificates-to-browsers.adoc
Labels: status/code-review

#1374 Revert back attributes in include statements
  linkcheckerrc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-bare-metal-using-kubespray.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-codeready-containers.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-docker-desktop.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-kind.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minishift.adoc
  src/main/pages/che-7/overview/assembly_using-the-chectl-management-tool.adoc
  tools/substitutions.sed
Labels: status/code-review

#1368 Fix link for linkchecker
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
Labels: kind/bug, status/code-review

#1373 Use attributes instead of hardcoded version names.
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1375 Refreshing the OpenShift 3.11 installation procedure
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
Labels: status/code-review

#1377 Remove mention about self-signed certificates in OperatorHub install
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: status/code-review

#1376 Remove "Using organizations".
  src/main/pages/che-7/administration-guide/assembly_using-organizations.adoc
  src/main/pages/che-7/administration-guide/con_organization-and-sub-organization-administration.adoc
  src/main/pages/che-7/administration-guide/con_organizations-in-eclipse-che.adoc
  src/main/pages/che-7/administration-guide/con_roles-in-an-organization.adoc
  src/main/pages/che-7/administration-guide/con_root-organizations-and-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/con_workspaces-in-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_adding-members-to-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_adding-members-to-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_allocating-resources-for-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_creating-an-organization.adoc
  src/main/pages/che-7/administration-guide/proc_creating-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_deleting-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_displaying-the-list-of-organization.adoc
  src/main/pages/che-7/administration-guide/proc_leaving-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_managing-limits.adoc
  src/main/pages/che-7/administration-guide/proc_removing-organization-and-sub-organization-members.adoc
  src/main/pages/che-7/administration-guide/proc_renaming-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_updating-organization-and-sub-organization-member-roles.adoc
Labels: status/code-review

#1379 Cleanup after organizations removal
  src/main/pages/che-7/administration-guide/assembly_configuring-authorization.adoc
  src/main/pages/che-7/administration-guide/assembly_managing-users.adoc
  src/main/pages/che-7/administration-guide/con_che-organization-permissions.adoc
  src/main/pages/che-7/administration-guide/con_che-system-permissions.adoc
  src/main/pages/che-7/administration-guide/con_super-privileged-mode.adoc
  src/main/pages/che-7/overview/con_glossary.adoc
  src/main/pages/che-7/tags/organizations.adoc
Labels: status/code-review

#1380 More cleanup after organizations removal
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
Labels: status/code-review

#1381 Add steps to OpenShit 3.11 installation
  Jenkinsfile
  src/main/_config.yml
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: kind/enhancement, status/code-review

#1383 Replace k8s in generated doc
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: status/code-review

#1357 Updating section for creating a workspace with desired projects
  src/main/images/workspaces/add-git-project.png
  src/main/images/workspaces/devfile-projects.png
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
Labels: kind/task, status/code-review

#1382 Use attributes for name and namespace
  src/main/pages/che-7/administration-guide/examples/changing-default-variables.adoc
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
  src/main/pages/che-7/extensions/examples/telemetry/che_cluster_with_custom_plugin.yaml
  src/main/pages/che-7/extensions/examples/telemetry/webserver.yaml
  src/main/pages/che-7/installation-guide/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/examples/checluster-custom-resource.yaml
  src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/installation-guide/ref_checluster-custom-resource-fields-reference.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: status/code-review

#1385 Add contexts.
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
Labels: kind/enhancement, status/code-review

#1384 Removing che 6 content.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/workspaces/che-6-workspace-configuration.png
  src/main/images/workspaces/commands-in-che-6.png
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/ref_comparing-che-6-workspace-to-a-devfile.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-from-che-6-on-openshift-4-using-the-web-console.adoc
Labels: status/code-review

#1364 Updating docs for creating and configuring a new Che 7 workspace
  src/main/images/workspaces/minimal-devfile.png
  src/main/images/workspaces/projects-add-project.png
  src/main/images/workspaces/workspace-devfile-editor.png
  src/main/images/workspaces/workspace-save-apply-cancel.png
  src/main/pages/che-7/end-user-guide/proc_adding-projects-to-your-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
Labels: kind/task, status/code-review

#1386 Isolate Code of Conduct, rewrite Contributing in asciidoc with some e…
  CODE_OF_CONDUCT.adoc
  CONTRIBUTING.adoc
  CONTRIBUTION.md
  devfile.yaml
Labels: status/code-review

#1387 chore(github): Add pull request link to che.openshift.io
  .github/workflows/che.yaml
Labels: status/code-review

#1388 Refresh Upgrading Che chapter
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-3-using-the-cli-management-tool.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-4-using-the-cli-management-tool.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-using-operatorhub.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-using-the-cli-management-tool.adoc
Labels: status/code-review

#1390 Rephrasing configuring
  src/main/pages/che-7/installation-guide/con_understanding-the-checluster-custom-resource.adoc
Labels: status/code-review

#1392 document mounting secret as files updates for older clusters
  src/main/pages/che-7/end-user-guide/proc_defining-maven-settings-xml-file-across-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
Labels: kind/bug, status/code-review

#1393 Contributing link fix
  README.md
Labels: kind/bug, status/code-review

#1394 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/enhancement, status/code-review

#1395 Simplifying the contributing procedure
  CONTRIBUTING.adoc
Labels: status/code-review

#1389 WIP: Various fixes.
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-operator.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-components.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: kind/bug, status/code-review

#1396 Remove search. Fixes che/17406.
  src/main/_includes/topnav.html
Labels: kind/bug, status/code-review

#1397 Unify on using TLS instead of SSL
  .vale.ini
  .vale/styles/CheDocs/CommonTerms.yml
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-go-projects.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-nuget-projects.adoc
  src/main/pages/che-7/end-user-guide/proc_using-self-signed-certificates-in-python-projects.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/proc_mounting-custom-tls-certificates-to-che-workspace-pods.adoc
Labels: status/code-review

#1398 Add vale rule.
  .vale/styles/CheDocs/CommonTerms.yml
  src/main/pages/che-7/overview/assembly_che-workspaces-architecture.adoc
Labels: kind/bug, status/code-review

#1399 Added readability grade rule.
  .vale/styles/CheDocs/ReadabilityGrade.yml
Labels: kind/enhancement, status/code-review

#1400 Removed "there are"s.
  src/main/pages/che-7/administration-guide/proc_extending-che-monitoring-metrics.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-logs-for-the-nodedebug-nodedebug2-adapter.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/con_embedded-and-remote-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-kubernetes.adoc
  src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: status/code-review

#1402 Unify language for: The `nameoftool` tool is available
  .vale/styles/CheDocs/CommonTerms.yml
  .vale/styles/IBM/PassiveVoice.yml
  .vale/styles/vocab.txt
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-prod-short-to-work-without-identity-provider.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/ref_netcoredebugoutput-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-3.adoc
  src/main/pages/che-7/installation-guide/proc_mounting-custom-tls-certificates-to-che-workspace-pods.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/con_openshift-developer-perspective-integration-with-che.adoc
  src/main/pages/che-7/overview/proc_accessing-che-from-red-hat-applications-menu.adoc
  src/main/pages/che-7/overview/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  src/main/pages/che-7/overview/proc_contributing-to-github-projects-in-hosted-che.adoc
  src/main/pages/che-7/overview/proc_creating-a-google-kubernetes-engine-instance.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubespray-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_upgrading-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/proc_using-minishift-to-set-up-openshift-3.adoc
Labels: status/code-review

#1403 Installing Che minikube: moving the lxc part at the end of the section.
  src/main/pages/che-7/overview/assembly_installing-che-on-minikube.adoc
  src/main/pages/che-7/overview/proc_using-minikube-and-lxc.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: status/code-review

#1405 Remove empty values in generated system-variables.adoc
  src/main/pages/che-7/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: status/code-review

#1404 Fix typo: CLuster -> Cluster
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/bug, status/code-review

#1408 Adding the option to select the project in the CLI upgrade procedure
  src/main/pages/che-7/installation-guide/proc_upgrading-che-using-the-cli-management-tool.adoc
Labels: kind/enhancement, status/code-review

#1407 Attribute for che ws
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: status/code-review

#1409 More consistent use of JWT vs machine tokens
  src/main/pages/che-7/administration-guide/assembly_authenticating-in-a-che-workspace.adoc
  src/main/pages/che-7/administration-guide/con_machine-token-validation.adoc
  src/main/pages/che-7/administration-guide/con_workspace-jwt-token.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
Labels: status/code-review

#1411 Fix Uninstalling Che after chectl installation
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-chectl-installation.adoc
Labels: kind/bug, status/code-review

#1406 AG fixes, rename metrics collections, restrcuture installation procedure
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-operator.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-che-traces-collections.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-maven-settings-xml-file-across-workspaces.adoc
Labels: kind/bug, status/code-review

#1410 Fix boolean string in file and variable mount examples
  src/main/pages/che-7/end-user-guide/examples/che-ref_a-kubernetes-secret-as-a-file.adoc
  src/main/pages/che-7/end-user-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
Labels: kind/bug, status/code-review

#1401 More directive language.
  src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
Labels: status/code-review

#1412 tlsSupport is now true by default
  src/main/pages/che-7/installation-guide/ref_checluster-custom-resource-fields-reference.adoc
Labels: status/code-review

#1413 EuG fixes - frist batch
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/assembly_adding-tools-to-che-after-creating-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-a-visual-studio-code-extension-in-che.adoc
  src/main/pages/che-7/end-user-guide/con_additional-tools-in-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
Labels: kind/bug, kind/enhancement, status/code-review

#1414 Uninstalling after OperatorHub installation
  src/main/pages/che-7/installation-guide/assembly_uninstalling-che.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation-using-openshift-cli.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation-using-openshift-web-console.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
Labels: status/code-review

#1416 Fix typo.
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: kind/bug, status/code-review

#1417 Tables
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: status/code-review

#1418 Move adding a plugin to the plugin registry into the administration g…
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_adding-che-plug-in-registry-vs-code-extension-to-a-workspace.adoc
  src/main/pages/che-7/administration-guide/assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc
  src/main/pages/che-7/administration-guide/assembly_using-a-visual-studio-code-extension-in-che.adoc
  src/main/pages/che-7/administration-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/administration-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  src/main/pages/che-7/administration-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
Labels: status/code-review

#1421 Git credentials store file mounting
  src/main/pages/che-7/end-user-guide/assembly_mounting-secrets-as-file-or-env-variable-in-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/examples/che-ref_annotations-description.adoc
  src/main/pages/che-7/end-user-guide/examples/che-ref_git-credential-file-as-kubernetes-secret-into-the-file.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-git-credential-store-into-a-workspace-container.adoc
Labels: kind/enhancement, status/code-review

#1422 Add a contribute link on Che docs
  src/main/_data/topnav.yml
Labels: kind/task, status/code-review

#1423 Add keys to _config.yml to support different postgres and keycloak
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/overview/con_che-keycloak.adoc
  src/main/pages/che-7/overview/con_che-postgresql.adoc
Labels: kind/enhancement, status/code-review

#1424 Fix procedure to import TLS certificates in Che server Java turststore #RHDEVDOCS-1893
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/proc_importing-tls-certificates-to-che-server-java-truststore.adoc
  src/main/pages/che-7/installation-guide/proc_mounting-custom-tls-certificates-to-che-workspace-pods.adoc
Labels: kind/bug, status/code-review

#1425 Add Persistent/Ephemeral/Asynchronous storage type description
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-for-che-end-users.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
  src/main/pages/che-7/overview/proc_creating-a-worskpace-from-the-user-dashboard.adoc
Labels: status/code-review

#1427 Add missing backslash
  src/main/pages/che-7/installation-guide/proc_importing-tls-certificates-to-che-server-java-truststore.adoc
Labels: kind/enhancement, status/code-review

#1429 feat(Docker): add git inside the image
  Dockerfile
Labels: kind/task, status/code-review

#1430 Add steps to use external PostgreSQL
  src/main/pages/che-7/administration-guide/con_external-database-setup.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-che-to-work-with-external-PostgreSQL.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-external-PostgreSQL.adoc
Labels: kind/task, status/code-review

#1434 Update Azure / Gcp guides
  src/main/images/installation/completing-the-creation-of-the-zone.png
  src/main/images/installation/entering-the-name-fo-the-domain.png
  src/main/pages/che-7/overview/assembly_installing-che-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_creating-a-google-kubernetes-engine-instance.adoc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-ingress-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: kind/bug, status/code-review

#1436 Update procedure
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
Labels: kind/enhancement, status/code-review
