Repository eclipse-che/che-docs, pull requests merged in 2020-08, with the labels that each got.

#1428 Improve docs about Persistent/Ephemeral/Asynchronous storage type description
  src/main/images/troubleshooting/status-bar-file-sync.png
  src/main/images/workspaces/create-custom-ws-storage-type-2.png
  src/main/images/workspaces/create-custom-ws-storage-type.png
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
  src/main/pages/che-7/overview/proc_creating-a-worskpace-from-the-user-dashboard.adoc
Labels: status/code-review

#1437 EuG SMEs feedback
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/assembly_defining-custom-commands-for-che-theia.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-lifecycle.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-task-types.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-projects-to-your-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  src/main/pages/che-7/end-user-guide/proc_editing-a-task-and-a-launch-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-git-credential-store-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_restarting-a-che-workspace-in-debug-mode-after-start-failure.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-open-button.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-run-button.adoc
  src/main/pages/che-7/end-user-guide/proc_running-and-debugging.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: status/code-review

#1439 Update assembly_network-troubleshooting.adoc
  src/main/pages/che-7/end-user-guide/assembly_network-troubleshooting.adoc
Labels: kind/enhancement, status/code-review, target/branch

#1440 Update proc_network-requirement.adoc
  src/main/pages/che-7/end-user-guide/proc_network-requirement.adoc
Labels: kind/enhancement, status/code-review, target/branch

#1441 Update proc_websocket-troubleshooting.adoc
  src/main/pages/che-7/end-user-guide/proc_websocket-troubleshooting.adoc
Labels: kind/enhancement, status/code-review, target/branch

#1444 Devfiles can now have multiple names
  src/main/pages/che-7/end-user-guide/con_a-minimal-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_what-is-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-workspace-names.adoc
Labels: kind/enhancement, status/code-review

#1448 Correct instructions for importing self-signed cert in firefox
  src/main/pages/che-7/installation-guide/proc_importing-self-signed-tls-certificates-to-browsers.adoc
Labels: status/code-review

#1442 Add procedure how to configure custom cheHost
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/keycloak/keycloak_che_public_client.png
  src/main/images/keycloak/keycloak_clients.png
  src/main/pages/che-7/installation-guide/proc_configuring-che-hostname.adoc
Labels: kind/enhancement, status/code-review

#1449 Update the procedure about configuring che hostname
  src/main/images/keycloak/keycloak_clients.png
  src/main/pages/che-7/installation-guide/proc_configuring-che-hostname.adoc
Labels: kind/enhancement, status/code-review

#1450 attribute fix
  src/main/pages/che-7/installation-guide/proc_configuring-che-hostname.adoc
Labels: kind/bug, status/code-review

#1454 Reenabling search bar with Google custom search
  src/main/_includes/topnav.html
  src/main/css/customstyles.css
Labels: status/code-review

#1456 Change docker image references to quay
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/overview/con_che-plug-in-broker.adoc
Labels: status/code-review

#1455 Add instructions for including the devloper workspace button in a README
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/workspace_button/eclipse_che_badges.png
  src/main/pages/che-7/end-user-guide/assembly_the-developer-workspace-button.adoc
Labels: status/code-review

#1459 Add information about Asynchronous Storage Pod idling
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
Labels: kind/task, status/code-review

#1460 Revert "Add information about Asynchronous Storage Pod idling"
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
Labels: status/code-review

#1458 17596 - support releasing Che docs
  VERSION
  make-release.sh
Labels: kind/bug, kind/task, status/code-review

#1463 17596 - set VERSION = 7.18.0 in master...
  VERSION
Labels: status/code-review

#1462 Fix a 404 by adding trailing slash to permalink
  src/main/pages/che-7/end-user-guide/assembly_the-developer-workspace-button.adoc
Labels: status/code-review

#1432 Clean up how to add VSCode plug ins into the plugin registry, and prepare for downstreaming
  src/main/pages/che-7/administration-guide/proc_building-a-custom-plug-in-registry.adoc
  src/main/pages/che-7/administration-guide/proc_che-including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.9.x

#1464 Use repo URL attributes for flexibility
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1433 Add theia-endpoint-image attribute.
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/examples/che-choosing-the-sidecar-image-images.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
Labels: kind/enhancement, status/code-review

#1465 Use (previous) major version attribute
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/assembly_configuring-a-workspace-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_disambiguation-between-stacks-and-devfiles.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.16.x, status/code-review

#1426 Fix unrendered attributes
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-maven-settings-xml-file-across-workspaces.adoc
Labels: kind/bug, status/code-review

#1466 Some fixes.
  src/main/pages/che-7/administration-guide/examples/che-choosing-the-sidecar-image-images.adoc
  src/main/pages/che-7/administration-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
  src/main/pages/che-7/extensions/assembly_openshift-connector-overview.adoc
  src/main/pages/che-7/extensions/con_features-of-openshift-connector.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_installing-openshift-connector-in-eclipse-che.adoc
Labels: kind/bug, need-cherry-pick/7.16.x, status/code-review

#1468 Remove redundant bracket, add context.
  src/main/pages/che-7/end-user-guide/assembly_the-developer-workspace-button.adoc
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
Labels: need-cherry-pick/7.16.x, status/code-review

#1469 ocp3.11 installation procedure update
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review

#1471 Formatting fix.
  src/main/pages/che-7/end-user-guide/assembly_the-developer-workspace-button.adoc
Labels: kind/bug, need-cherry-pick/7.16.x, status/code-review

#1472 Move the example file to examples.
  src/main/images/ide/che-theia-basics-3-d.png
  src/main/pages/che-7/administration-guide/examples/proc_che-including-the-plug-in-binaries-in-the-registry-image.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
Labels: need-cherry-pick/7.16.x, status/code-review

#1475 Rename Troubleshooting.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-for-che-end-users.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1474 Fix devel badge.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_the-developer-workspace-button.adoc
  src/main/pages/che-7/end-user-guide/assembly_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_using-a-badge-to-link-to-workspaces.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.16.x, severity/blocker, status/code-review

#1476 fixing the procedure steps
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: kind/bug, need-cherry-pick/7.16.x, status/code-review

#1477 Conflict solving
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review, target/branch

#1470 Fix docs release tagging script
  make-release.sh
Labels: kind/bug, kind/task, status/code-review

#1467 Edit instructions for editing a devfile at runtime
  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
Labels: need-cherry-pick/7.16.x, status/code-review

#1478 add trailing newline
  make-release.sh
Labels: kind/enhancement, status/code-review

#1480 Sort attributes in alphabetical order
  src/main/_config.yml
Labels: status/code-review

#1453 Update ref_devfile-reference.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, need-cherry-pick/7.16.x

#1483 Use attrib for baseurl.
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-task-types.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.16.x, status/code-review

#1484 Modularizing, adding prerequisites.
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/con_network-connectivity-in-restricted-environments.adoc
  src/main/pages/che-7/installation-guide/proc_building-offline-versions-of-the-plug-in-and-devfile-registries.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-to-run-in-a-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_pulling-images-used-by-che-to-a-private-registry.adoc
Labels: status/code-review

#1479 Add page about configuring nodeselectors
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/proc_configuring-workspaces-nodeselector.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1443 Reworking "making a workspace portable with a devfile"
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: need-cherry-pick/7.16.x, status/code-review

#1461 Add information about Asynchronous Storage Pod idling #1459 - review
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-che.adoc
  src/main/pages/che-7/end-user-guide/proc_using-different-types-of-storage.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-storage-types.adoc
Labels: kind/docs, kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1488 A simplified version of :Authenticating with OAuth
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-oauth.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1451 Reorganize documentation for self-signed certificates
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-4.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-codeready-containers.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-docker-desktop.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-kind.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minishift.adoc
  src/main/pages/che-7/overview/proc_adding-self-signed-certs-to-minishift.adoc
  src/main/pages/che-7/overview/proc_exporting-self-signed-ca-certificate-from-deployment.adoc
  src/main/pages/che-7/overview/proc_generating-self-signed-tls-certificates.adoc
  src/main/pages/che-7/overview/proc_importing-self-signed-tls-certificates-to-browsers.adoc
Labels: kind/bug, status/code-review

#1492 Fix auth. modes.
  src/main/pages/che-7/administration-guide/con_authentication-modes.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1487 Che4z page update
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
Labels: status/code-review

#1445 Troubleshooting revamped
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-che.adoc
  src/main/pages/che-7/end-user-guide/proc_restarting-a-che-workspace-in-debug-mode-after-start-failure.adoc
  src/main/pages/che-7/end-user-guide/proc_starting-a-che-workspace-in-debug-mode.adoc
  src/main/pages/che-7/end-user-guide/proc_troubleshooting-network-problems.adoc
Labels: kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1486 feat(troubleshooting): Add section about slow workspaces
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-che.adoc
  src/main/pages/che-7/end-user-guide/proc_troubleshooting-slow-workspaces.adoc
Labels: kind/enhancement, need-cherry-pick/7.16.x, status/code-review

#1495 Fix a bunch minor troubleshooting-related things.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-che.adoc
  src/main/pages/che-7/end-user-guide/proc_troubleshooting-network-problems.adoc
  src/main/pages/che-7/overview/proc_creating-a-worskpace-from-the-user-dashboard.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.16.x, status/code-review

#1435 feat(guide): Add guide on how to test a VS Code extension
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/workspaces/vscode-gist-setup.png
  src/main/pages/che-7/administration-guide/assembly_testing-a-visual-studio-code-extension-in-che.adoc
  src/main/pages/che-7/administration-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/administration-guide/proc_testing-the-vs-code-extension-using-gist.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
Labels: need-cherry-pick/7.16.x, status/code-review

#1494 chectl usage improvements
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/proc_upgrading-che-using-the-cli-management-tool.adoc
  src/main/pages/che-7/overview/assembly_using-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: status/code-review

#1497 Remove logs from troublesh.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-che.adoc
Labels: kind/bug, kind/docs, need-cherry-pick/7.16.x, status/code-review

#1496 Add PR checklist into PR template to update docs references in clients
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/enhancement, status/code-review

#1493 Add assembly for importing self-signed certs to allow direct link
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/overview/assembly_importing-self-signed-certificates-to-browsers.adoc
Labels: kind/bug, need-cherry-pick/7.16.x, status/code-review

#1498 Improve documentation to get access token
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
Labels: status/code-review

#1447 Rework che-theia tasks and commands
  src/main/pages/che-7/end-user-guide/assembly_defining-custom-commands-for-che-theia.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-task-types.adoc
Labels: status/code-review

#1501 Fix edit this file
  Jenkinsfile
  antora-playbook.yml
Labels: kind/bug, status/code-review

#1504 Fix favicon footer
  supplemental-ui/partials/footer-content.hbs
  supplemental-ui/partials/head-meta.hbs
Labels: kind/bug, kind/docs, status/code-review

#1506 One more alias
  modules/overview/pages/running-che-locally.adoc
Labels: status/code-review

#1505 Fix prod-short variable in che-theia task doc
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
Labels: kind/bug, status/code-review

#1508 Fix search
  supplemental-ui/css/extra.css
  supplemental-ui/img/icon-eclipse-che.svg
  supplemental-ui/img/logo-eclipse-che.svg
  supplemental-ui/partials/header-content.hbs
Labels: kind/docs, kind/enhancement, status/code-review

#1507 New location for topics in substitutions.sh
  tools/substitutions.sh
Labels: status/code-review
