Repository eclipse-che/che-docs, pull requests merged in 2020-05, with the labels that each got.

#1260 Added missing contexts.
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/extensions/proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1261 Language and style fixes
  .ci/vale/styles/IBM/terms.yml
  .vale.ini
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/con_persistent-volumes-backups.adoc
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_logging-the-client-server-traffic-for-debug-adapters.adoc
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-remote-plugin-image.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-lifecycle.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-task-types.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-projects-to-your-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/overview/assembly_accessing-che-from-openshift-developer-perspective.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/con_che-plug-ins.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-dns-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-registering-as-a-new-user.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-using-oauth.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: kind/bug, status/code-review

#1262 Update assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
Labels: kind/enhancement, status/code-review

#1263 Consistency fixes
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1264 Use correct command for plug-in generator installation
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
Labels: kind/bug, status/code-review

#1270 Removing unnecessary procedure step and prerequsities
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review, target/branch

#1271 Removing unnecessary steps and prerequsities
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review, target/branch

#1272 Removing unnecessary steps and prerequsities
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review

#1252 Bare metal kubespray quick start
  src/main/pages/che-7/overview/assembly_installing-che-on-premise-with-kubespray.adoc
  src/main/pages/che-7/overview/assembly_installing-chectl.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubespray-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-load-balancer-on-a-bare-metal-cluster.adoc
  src/main/pages/che-7/overview/proc_installing-storage-on-a-bare-metal-cluster.adoc
  src/main/pages/che-7/overview/proc_using-kubespray-to-set-up-kubernetes.adoc
Labels: kind/enhancement, status/code-review

#1267 Backporting fixes from the downstream.
  src/main/pages/che-7/administration-guide/examples/che-deploying-image-puller-using-openshift-templates_parameters.adoc
  src/main/pages/che-7/administration-guide/examples/che-prepulled-images-table.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
Labels: kind/bug, need-cherry-pick/7.9.x, status/code-review

#1273 Enviromnent docs gen fixes
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  tools/enviromnent_docs_gen.sh
Labels: Che-7, kind/bug, kind/docs, kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1211 Glossary file.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/overview/con_glossary.adoc
Labels: status/code-review

#1266 CONTRIBUTION.md and README.md update
  CONTRIBUTION.md
  README.md
Labels: status/code-review

#1275 Moved vale directory out of .ci to keep things organized
  .vale.ini
  .vale/styles/CheDocs/Attributes.yml
  .vale/styles/CheDocs/CommonTerms.yml
  .vale/styles/CheDocs/Links-che6.yml
  .vale/styles/CheDocs/Links.yml
  .vale/styles/IBM/README.md
  .vale/styles/IBM/Usage.yml
  .vale/styles/IBM/terms.yml
  .vale/styles/Microsoft/Foreign.yml
  .vale/styles/Microsoft/HeadingPunctuation.yml
  .vale/styles/Microsoft/Spacing.yml
  .vale/styles/PlainLanguage/PassiveVoice.yml
  .vale/styles/PlainLanguage/SentenceLength.yml
  .vale/styles/PlainLanguage/Slash.yml
  .vale/styles/PlainLanguage/Wordiness.yml
  .vale/styles/PlainLanguage/Words.yml
  .vale/styles/proselint/Annotations.yml
  .vale/styles/proselint/README.md
  .vale/styles/proselint/Spelling.yml
  .vale/styles/proselint/Very.yml
  .vale/styles/vocab.txt
  .vale/styles/write-good/README.md
  .vale/styles/write-good/ThereIs.yml
Labels: status/code-review

#1276 fix file names in Image Puller docs
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_cloning-project.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_parameters.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_prepare.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_process.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_verify-configmap.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
Labels: kind/bug, status/code-review

#1268 Reorganization of the "Configuring Che" chapter.
  .gitignore
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options-for-the-che-server-component.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-the-che-installation.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/installation-guide/con_deployment-architecture-diagram.adoc
  src/main/pages/che-7/installation-guide/con_target-platforms.adoc
  src/main/pages/che-7/installation-guide/con_understanding-che-server-advanced-configuration-not-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/con_understanding-the-checluster-custom-resource.adoc
  src/main/pages/che-7/installation-guide/examples/.placeholder
  src/main/pages/che-7/installation-guide/examples/checluster-custom-resource.yaml
  src/main/pages/che-7/installation-guide/proc_adding-custom-certificates-to-trust-store.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-persistent-volumes-strategy.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-with-and-without-keycloak.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/installation-guide/ref_che-server-component-system-properties-reference.adoc
  src/main/pages/che-7/installation-guide/ref_checluster-custom-resource-fields-reference.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  tools/enviromnent_docs_gen.sh
Labels: status/code-review

#1269 PVC strategies and Without Keycloak content
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/assembly_configuring-authorization.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-prod-short-to-work-without-identity-provider.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-configuration.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
Labels: status/code-review

#1277 Update doc: mount a maven settings volume instead of using /projects
  src/main/pages/che-7/end-user-guide/proc_defining-maven-repositories-in-the-settings-xml-file.adoc
Labels: kind/task, status/code-review

#1274 Style and language fixes.
  .vale/styles/IBM/terms.yml
  .vale/styles/vocab.txt
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_installing-che-using-storage-classes.adoc
Labels: kind/bug, status/code-review

#1278 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/enhancement, status/code-review

#1279 Update assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
Labels: status/code-review

#1280 Fix broken links for installation on Kind cluster
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
Labels: kind/bug, status/code-review

#1281 Table and language fixes
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/examples/che-pvc-strategies.adoc
Labels: kind/bug, status/code-review

#1282 Editing the prodcli installation method
  src/main/_config.yml
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
Labels: status/code-review

#1284 Readme fix
  CONTRIBUTION.md
  README.md
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#1285 Fix dumb GH rendering issue in README.
  CONTRIBUTION.md
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1288 Table and language fixes
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/examples/che-pvc-strategies.adoc
Labels: kind/bug, status/code-review, target/branch
