Repository eclipse-che/che-docs, pull requests merged in 2020-12, with the labels that each got.

#1704 Switching between external and internal ways in inter-component communication
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/switching-between-external-and-internal-communication.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/enhancement, status/code-review

#1707 Fix xref
  modules/end-user-guide/examples/che-adding-a-git-project-into-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/partials/proc_writing-a-devfile-for-your-project.adoc
Labels: kind/bug, status/code-review

#1598 Update the documentation about importing external certificates
  modules/installation-guide/examples/snip_importing-untrusted-tls-certificates_1.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/importing-tls-certificates-to-che-server-java-truststore.adoc
  modules/installation-guide/pages/importing-untrusted-tls-certificates.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_importing-tls-certificates-to-che-server-java-truststore.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: kind/enhancement, need-cherry-pick/7.18.x, need-cherry-pick/7.20.x, status/code-review

#1708 Adds docs about how to configure server logging levels.
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-server-logging.adoc
  modules/administration-guide/partials/assembly_configuring-server-logging.adoc
  modules/administration-guide/partials/assembly_retrieving-che-logs.adoc
  modules/administration-guide/partials/con_logger-naming.adoc
  modules/administration-guide/partials/con_logging-http-traffic.adoc
  modules/administration-guide/partials/proc_configuring-server-logging.adoc
Labels: status/code-review

#1710 Fix command to patch checluster
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
Labels: kind/bug, status/code-review

#1701 Add the DEPLOYMENT_NAME parameter to the image puller parameters
  modules/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_parameters.adoc
  modules/administration-guide/partials/con_image-puller-overview.adoc
  modules/administration-guide/partials/proc_deploying-image-puller-using-helm.adoc
Labels: kind/enhancement, status/code-review

#1711 Removing l0rd from codeowners
  .github/CODEOWNERS
Labels: status/code-review

#1712 Language fixes.
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/importing-a-kubernetes-application-into-a-workspace.adoc
  modules/end-user-guide/pages/importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
  modules/end-user-guide/partials/proc_adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard.adoc
  modules/end-user-guide/partials/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  modules/end-user-guide/partials/proc_including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
Labels: kind/bug, kind/enhancement, status/code-review

#1713 Add @eclipse/ecd-che-docs-reviewers to CODEOWNERS
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review

#1716 fix unexisting dockerimage in examples
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: kind/bug, status/code-review

#1715 Add attribute.
  modules/end-user-guide/partials/assembly_navigating-che-using-the-dashboard.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1718 Review EuG - Team lead feedback
  modules/end-user-guide/partials/assembly_customizing-developer-environments.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-concept-in-detail.adoc
  modules/end-user-guide/partials/con_openshift-developer-perspective-integration-with-che.adoc
  modules/end-user-guide/partials/proc_accessing-che-from-red-hat-applications-menu.adoc
  modules/end-user-guide/partials/proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc
  modules/end-user-guide/partials/proc_importing-certificates-to-browsers.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1709 Fixing typo in env variable CHE_LIMITS_USER_WORKSPACES_RUN_COUNT and improving docs for PVC Strategy.
  modules/administration-guide/partials/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
Labels: kind/bug, status/code-review

#1720 Upstream EuG review; almost there
  modules/end-user-guide/partials/con_additional-tools-in-the-che-workspace.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-lifecycle.adoc
  modules/end-user-guide/partials/con_embedded-and-remote-che-theia-plug-ins.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/partials/proc_defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file.adoc
  modules/end-user-guide/partials/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
  modules/end-user-guide/partials/proc_publishing-metadata-for-a-vs-code-extension.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1721 Fix example block
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
Labels: kind/bug, need-cherry-pick/7.20.x, status/code-review

#1717 Add a note about webview
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/differences-in-how-che-theia-webview-works-on-a-single-host-mode-comparing-to-a-multi-host-mode.adoc
  modules/end-user-guide/partials/assembly_che-theia-ide-basics.adoc
  modules/end-user-guide/partials/assembly_differences-in-how-che-theia-webview-works-on-a-single-host-mode-comparing-to-a-multi-host-mode.adoc
Labels: kind/task, need-cherry-pick/7.20.x, status/code-review

#1725 fix(link): fix link checker
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: kind/bug, status/code-review

#1724 chore(netlify): Fix build of documentation on forked repositories by uploading artifacts in the actions
  .github/workflows/build-pr-docs.yaml
  .github/workflows/netlify.yaml
  .github/workflows/publish-netlify.yaml
Labels: kind/bug, status/code-review

#1729 Fix chectl arguments order
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool.adoc
Labels: kind/bug, status/code-review

#1723 Setting up Keycloak che-username-readonly-theme
  modules/installation-guide/images/keycloak/che-keycloak-username-readonly-theme.png
  modules/installation-guide/images/keycloak/crw-keycloak-username-readonly-theme.png
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
Labels: kind/docs, kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1730 Fix doc
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/bug, status/code-review

#1732 che #18463 Adding clarification that Hosted Che is Eclipse Che hosted by Red Hat
  CONTRIBUTING.adoc
  modules/hosted-che/pages/hosted-che.adoc
  modules/hosted-che/partials/assembly_hosted-che.adoc
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: kind/enhancement, status/code-review

#1731 Upstream EuG review: Chapter 5 and beyond + Extensions
  modules/end-user-guide/images/troubleshooting/download_logs.png
  modules/end-user-guide/images/troubleshooting/run_workspace_in_debug_mode.png
  modules/end-user-guide/images/troubleshooting/starting_workspace_debug_logs.png
  modules/end-user-guide/images/troubleshooting/try_again_in_debug_mode.png
  modules/end-user-guide/partials/assembly_troubleshooting-che.adoc
  modules/end-user-guide/partials/con_additional-tools-in-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/partials/proc_configuring-openshift-oauth.adoc
  modules/end-user-guide/partials/proc_troubleshooting-slow-workspaces.adoc
  modules/extensions/partials/con_features-of-openshift-connector.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1727 Add an xref.
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1734 memoryRequest for devfile dockerimage component
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#1733 Remove redundant prereqs.
  modules/end-user-guide/partials/proc_accessing-a-git-repository-via-https.adoc
  modules/end-user-guide/partials/proc_accessing-a-git-repository-via-ssh.adoc
  modules/end-user-guide/partials/proc_managing-git-configuration-identity.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1735 Fix xref to an alias
  modules/end-user-guide/partials/con_embedded-and-remote-che-theia-plug-ins.adoc
Labels: kind/bug, need-cherry-pick/7.20.x, status/code-review

#1739 Rework GCP instruction to avoid need use screenshots
  modules/installation-guide/images/installation/che-user-dashboard-gcp.png
  modules/installation-guide/images/installation/keycloak-and-che-with-valid-wildcard-certs.gif
  modules/installation-guide/partials/proc_configuring-the-che-operator-checluster-resource-with-kubectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
Labels: kind/task, status/code-review

#1742 Fix Multi-cluster OpenShift env usage
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/bug, status/code-review

#1719 Update import additional CA certificates chapter
  modules/installation-guide/pages/importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: kind/bug, status/code-review

#1740 Reuse chectl commands to deploy on any in cloud k8s
  antora-playbook.yml
  modules/installation-guide/images/installation/certificate-generate-lets-encrypt.png
  modules/installation-guide/images/installation/che-user-dashboard.png
  modules/installation-guide/images/installation/eclipse-che-welcome-to-your-workspace.png
  modules/installation-guide/images/installation/wildcard-certificates-for-keycloak-che.png
  modules/installation-guide/partials/assembly_installing-che-on-aws.adoc
  modules/installation-guide/partials/assembly_installing-che-on-google-cloud-platform.adoc
  modules/installation-guide/partials/assembly_installing-che-on-microsoft-azure.adoc
  modules/installation-guide/partials/proc_installing-che-on-azure-using-the-chectl-command.adoc
  modules/installation-guide/partials/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubernetes_using_chectl_and_helm.adoc
Labels: kind/task, status/code-review

#1741 Configuring storage strategies
  modules/administration-guide/partials/assembly_che-workspace-configuration.adoc
  modules/administration-guide/partials/assembly_understanding-che-workspaces-architecture.adoc
  modules/administration-guide/partials/con_workspaces-namespaces-configuration.adoc
  modules/installation-guide/examples/che-pvc-strategies.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/configuring-storage-strategies.adoc
  modules/installation-guide/partials/assembly_configuring-storage-strategies.adoc
  modules/installation-guide/partials/con_persistent-volume-configuration.adoc
  modules/installation-guide/partials/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1746 External and internal inter component communication methods
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: status/code-review, target/branch

#1743 Review inter-component communication config
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/enhancement, status/code-review

#1744 Remove outdated step
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: kind/enhancement, status/code-review

#1745 Replace outdated factories info with sharing workspace with devfile URL
  modules/contributor-guide/images/extensibility/adding-plug-ins-in-dashboard.png
  modules/contributor-guide/images/extensibility/adding-plug-ins-in-workspace-devfile.png
  modules/contributor-guide/partials/assembly_publishing-che-theia-plug-ins.adoc
  modules/contributor-guide/partials/proc_adding-a-che-theia-plug-in-into-a-workspace.adoc
  modules/contributor-guide/partials/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  modules/contributor-guide/partials/proc_sharing-your-che-theia-plug-in-with-a-factory.adoc
Labels: kind/task, status/code-review

#1748 attribute and fixes
  antora-playbook.yml
  modules/end-user-guide/partials/assembly_remotely-accessing-workspaces.adoc
  modules/end-user-guide/partials/proc_accessing-workspaces-remotely-using-kubectl.adoc
  modules/end-user-guide/partials/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1714 update CheCluster with cheClusterRoles property
  modules/installation-guide/partials/ref_checluster-custom-resource-fields-reference.adoc
Labels: kind/enhancement, status/code-review

#1752 Minikube and Minishift
  modules/administration-guide/partials/assembly_running-custom-registries.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1753 Fix linkchecker errors
  linkcheckerrc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review

#1751 Remove conditionals.
  antora-playbook.yml
  modules/administration-guide/partials/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  modules/administration-guide/partials/proc_using-protocol-based-providers.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1754 Bump to Antora 2.3.4
  yarn.lock
Labels: status/code-review

#1756 Use quay.io container images for che-docs devfile where available
  devfile.yaml
Labels: status/code-review

#1757 Fix a typo in xref
  linkcheckerrc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: kind/bug, status/code-review

#1755 Add a PR check that detects unused images
  .github/workflows/unused-images.yaml
  devfile.yaml
  modules/contributor-guide/images/extensibility/sharing-plug-in-with-factory.png
  modules/end-user-guide/images/extensibility/local-che-theia-plug-in.png
  modules/end-user-guide/images/extensibility/remote-che-theia-plug-in.png
  modules/installation-guide/images/keycloak/crw-keycloak-username-readonly-theme.png
  tools/detect-unused-images.sh
Labels: kind/enhancement, status/code-review

#1749 Rework running custom registries not to use screenshots
  modules/administration-guide/images/customization/che-deploying-plugin-registry-in-kubernetes.png
  modules/administration-guide/images/customization/deploying-devfile-registry-in-kubernetes.png
  modules/administration-guide/partials/assembly_running-custom-registries.adoc
  modules/administration-guide/partials/proc_deploying-registries-in-kubernetes.adoc
  modules/administration-guide/partials/proc_deploying-registries-in-openshift.adoc
  modules/administration-guide/partials/proc_verification-custom-registries.adoc
Labels: kind/task, status/code-review

#1760 Fixes for 7.20.x
  antora-playbook.yml
  linkcheckerrc
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  modules/installation-guide/pages/switching-between-external-and-internal-communication.adoc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review, target/branch

#1738 fix and simplify workspace exposure strategies doc
  modules/installation-guide/partials/assembly_configuring-workspace-exposure-strategies.adoc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: kind/enhancement, status/code-review

#1765 Fix attribute and url
  antora-playbook.yml
  modules/administration-guide/partials/proc_using-protocol-based-providers.adoc
Labels: kind/bug, status/code-review

#1726 update workspace components resource requirements
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
Labels: kind/enhancement, status/code-review

#1747 describe operator and helm configuration of namespace strategies
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review

#1759 fix(double-anchor): invalid link
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: kind/bug, status/code-review

#1766 Reword a list of options for better visibility
  modules/administration-guide/partials/proc_configuring-che-to-use-external-identity-provider.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x

#1758 Fixes in lang., formatting, naming.
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/jetbrains-ides.adoc
  modules/end-user-guide/pages/jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/pages/jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/pages/jetbrains-provision-activation-code-for-offline-usage.adoc
  modules/end-user-guide/pages/jetbrains-webstorm.adoc
  modules/end-user-guide/pages/provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/pages/support-for-jetbrains-ides.adoc
  modules/end-user-guide/pages/using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/pages/using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/pages/using-jetbrains-webstorm.adoc
  modules/end-user-guide/partials/con_jetbrains-ides.adoc
  modules/end-user-guide/partials/con_jetbrains-product-name-mapping.adoc
  modules/end-user-guide/partials/con_support-for-jetbrains-ides.adoc
  modules/end-user-guide/partials/proc_jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/partials/proc_jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/partials/proc_jetbrains-provision-activation-code-for-offline-usage.adoc
  modules/end-user-guide/partials/proc_jetbrains-webstorm.adoc
  modules/end-user-guide/partials/proc_provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-webstorm.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review, target/branch
