Repository eclipse-che/che-docs, pull requests merged in 2020-11, with the labels that each got.

#1663 update pre-creating namespaces for users documentation
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/enhancement, status/code-review

#1668 Instead of using the prod name, use its attribute in link & anchor
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-storage-types.adoc
  modules/installation-guide/partials/proc_installing-che-on-kind-using-chectl.adoc
Labels: status/code-review

#1684 Adding note and example command for the `Runnin more worksapces` chapter
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
  modules/installation-guide/examples/system-variables.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1688 Tiny bugfix.
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/bug, status/code-review

#1669 Explain how users can define workspace deployment labels and annotations
  modules/end-user-guide/partials/assembly_configuring-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/partials/proc_allowing-users-to-define-workspace-deployment-labels-and-annotations.adoc
Labels: kind/task, status/code-review

#1686 Update instructions to install ingress-nginx
  modules/installation-guide/partials/proc_installing-che-on-kind-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-ingress-on-kubernetes.adoc
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: kind/enhancement, status/code-review

#1693 Update diagrams.
  modules/end-user-guide/images/extensibility/che-theia-plug-in-lifecycle.png
  modules/end-user-guide/images/extensibility/che-theia-plug-in-lifecycle.svg
  modules/end-user-guide/images/extensibility/client-server-side-plug-ins.png
  modules/end-user-guide/images/extensibility/client-server-side-plug-ins.svg
  modules/end-user-guide/images/extensibility/extending-che.png
  modules/end-user-guide/images/extensibility/extending-che.svg
  modules/end-user-guide/partials/assembly_customizing-developer-environments.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-concept-in-detail.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-lifecycle.adoc
  modules/end-user-guide/partials/con_embedded-and-remote-che-theia-plug-ins.adoc
Labels: Che-7, kind/docs, kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1692 Replace [TIP] w/ [NOTE]
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/end-user-guide/partials/proc_adding-projects-to-your-workspace.adoc
  modules/end-user-guide/partials/proc_changing-the-configuration-of-an-existing-workspace.adoc
  modules/end-user-guide/partials/proc_checking-important-logs.adoc
  modules/end-user-guide/partials/proc_creating-a-new-workspace-from-the-dashboard.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
  modules/installation-guide/examples/proc_che-uninstalling-che-after-chectl-installation.adoc
  modules/installation-guide/partials/assembly_installing-che.adoc
  modules/installation-guide/partials/proc_building-a-registry-image.adoc
  modules/installation-guide/partials/proc_creating-a-google-kubernetes-engine-instance.adoc
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
  modules/installation-guide/partials/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  modules/installation-guide/partials/proc_uninstalling-che-after-operatorhub-installation-using-openshift-web-console.adoc
Labels: need-cherry-pick/7.20.x, status/code-review

#1656 Fix external DB setup
  modules/administration-guide/partials/proc_configuring-che-to-work-with-external-PostgreSQL.adoc
  modules/administration-guide/partials/proc_configuring-external-PostgreSQL.adoc
Labels: kind/question, status/code-review

#1696 Fix attributes in system-variables.adoc
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#1695 fix formatting - see https://github.com/eclipse/che/issues/18345
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
Labels: kind/bug, status/code-review

#1697 Eu g review upstreeam
  modules/end-user-guide/images/git/git-config-identity.png
  modules/end-user-guide/images/git/terminal-git-command.png
  modules/end-user-guide/partials/assembly_che-theia-troubleshooting.adoc
  modules/end-user-guide/partials/assembly_version-control.adoc
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
  modules/end-user-guide/partials/proc_accessing-a-git-repository-via-ssh.adoc
  modules/end-user-guide/partials/proc_accessing-che-from-red-hat-applications-menu.adoc
  modules/end-user-guide/partials/proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc
  modules/end-user-guide/partials/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  modules/end-user-guide/partials/proc_managing-git-configuration-identity.adoc
Labels: status/code-review

#1694 document how che-server labels the namespaces and the permissions nee…
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/enhancement, status/code-review

#1698 Fix create workspace section using chectl
  modules/end-user-guide/images/loggingin/copy_login_command_menu.png
  modules/end-user-guide/images/loggingin/copy_login_command_notification.png
  modules/end-user-guide/partials/assembly_navigating-che-using-the-dashboard.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  modules/end-user-guide/partials/proc_logging-in-to-che-server-using-cli.adoc
Labels: kind/bug, status/code-review

#1690 Update proc_preparing-the-aws-system-for-installing-che.adoc
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: kind/enhancement, status/code-review

#1700 Eug and IG markup fixes
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
  modules/end-user-guide/partials/con_a-minimal-devfile.adoc
  modules/end-user-guide/partials/proc_overriding-devfile-values-using-factory-parameters.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspaces-nodeselector.adoc
Labels: kind/bug, status/code-review

#1687 Update k8s.tlsSecretName property behaviour doc
  modules/installation-guide/partials/ref_checluster-custom-resource-fields-reference.adoc
Labels: kind/bug, status/code-review

#1702 Improve configuring-openshift-oauth section
  modules/end-user-guide/partials/proc_configuring-openshift-oauth.adoc
Labels: status/code-review

#1703 Upstream review of EuG - chapter 3
  modules/end-user-guide/examples/che-adding-a-git-project-into-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/partials/proc_accessing-workspaces-remotely-using-kubectl.adoc
  modules/end-user-guide/partials/proc_adding-projects-to-your-workspace.adoc
  modules/end-user-guide/partials/proc_configuring-the-workspace-and-adding-tooling.adoc
  modules/end-user-guide/partials/proc_creating-a-new-workspace-from-the-dashboard.adoc
  modules/end-user-guide/partials/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
  modules/end-user-guide/partials/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  modules/end-user-guide/partials/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  modules/end-user-guide/partials/proc_writing-a-devfile-for-your-project.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1705 test-fixing-xref
  modules/end-user-guide/partials/proc_writing-a-devfile-for-your-project.adoc
Labels: kind/bug, status/code-review
