Repository eclipse-che/che-docs, pull requests merged in 2020-03, with the labels that each got.

#1102 A rule to check links with www.eclipse.org instead of {site-baseurl}.
  .ci/vale/styles/CheDocs/Links.yml
  .vale.ini
Labels: status/code-review

#1087 Add make-release.sh script to automate the release process
  RELEASE.md
  make-release.sh
Labels: kind/enhancement, status/code-review

#1078 Add instructions for adding custom ssl cert to trust store
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/proc_adding-custom-certificates-to-trust-store.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
Labels: kind/task, status/code-review

#1104 Adding tool - content
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_adding-tools-to-che-after-creating-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-and-configuring-a-new-che-7-workspace.adoc
  src/main/pages/che-7/end-user-guide/con_additional-tools-in-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/examples/che-java-language-support.yml
  src/main/pages/che-7/end-user-guide/examples/che-workspace-from-the-php-stack-java-language-support.yml
  src/main/pages/che-7/end-user-guide/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#1105 Fixing quotes and double quotes and some other stuff
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
  src/main/pages/che-7/contributor-guide/assembly_branding-che-theia.adoc
  src/main/pages/che-7/contributor-guide/assembly_che-extensibility-reference.adoc
  src/main/pages/che-7/contributor-guide/assembly_developing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/assembly_publishing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/assembly_setup-che-in-tls-mode-with-self-signed-certificate.adoc
  src/main/pages/che-7/contributor-guide/assembly_testing-che-theia-plug-ins.adoc
  src/main/pages/che-7/end-user-guide/assembly_adding-che-plug-in-registry-vs-code-extension-to-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-ide-basics.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-oauth-authorization.adoc
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/assembly_defining-custom-commands-for-che-theia.adoc
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_making-a-workspace-portable-using-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/assembly_navigating-che-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/assembly_running-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/assembly_troubleshooting-for-che-end-users.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-a-visual-studio-code-extension-in-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_using-alternative-ides-in-che.adoc
  src/main/pages/che-7/end-user-guide/assembly_version-control.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/installation-guide/assembly_advanced-configuration-options.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che-on-openshift-4-using-the-openshift-web-console.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/overview/assembly_che-architecture.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-components.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-configuration.adoc
  src/main/pages/che-7/overview/assembly_che-workspace-controller.adoc
  src/main/pages/che-7/overview/assembly_che-workspaces-architecture.adoc
  src/main/pages/che-7/overview/assembly_deploying-che-on-kubernetes-on-aws.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-google-cloud-platform.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-microsoft-azure.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-from-operatorhub.adoc
  src/main/pages/che-7/overview/assembly_installing-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_preparing-google-cloud-platform-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_configuring-dns-on-azure.adoc
  src/main/pages/che-7/overview/proc_creating-a-service-account-secret-on-azure.adoc
  src/main/pages/che-7/overview/proc_enabling-the-tls-dns-challenge-on-azure.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_preparing-azure-for-installing-che.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/bug, status/code-review

#1085 Document the kubernetes image puller
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_caching-images-for-faster-workspace-start.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
Labels: kind/task, status/code-review

#1101 default project attribute
  src/main/_config.yml
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: status/code-review

#1108 remove duplicate lines
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
Labels: status/code-review

#1103 Add documentation about new resource limits of Che plugins
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/task, status/code-review

#1109 pr-update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status/code-review

#1106 Add menu item for environment variables configuration page
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
Labels: kind/enhancement, status/code-review

#1111 Small fixes for Configuring system variables module
  src/main/pages/che-7/administration-guide/examples/changing-default-variables.yaml
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
Labels: kind/bug, status/code-review

#1113 Added slash
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
Labels: kind/enhancement, status/code-review

#1115 Fixes.
  src/main/pages/che-7/administration-guide/examples/changing-default-variables.adoc
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
Labels: kind/bug, status/code-review

#1114 Removing crw mentions from Upstream, applying atributes
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-openshift.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/extensions/proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-chectl-installation.adoc
Labels: status/code-review

#1116 che 6 links warning
  .ci/vale/styles/CheDocs/Links-che6.yml
Labels: status/code-review

#1117 I1687 adding a missing intro
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
  src/main/pages/che-7/administration-guide/proc_building-a-custom-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
Labels: status/code-review

#1118 add workspace start attempts graphs to grafana dashboard
  src/main/images/monitoring/monitoring-che-che-server-dashboard-workspace-panel.png
  src/main/pages/che-7/administration-guide/ref_grafana-dashboards-for-che.adoc
Labels: kind/enhancement, status/code-review

#1119 [WIP] runtime logs messages metrics
  src/main/images/monitoring/monitoring-che-che-server-dashboard-workspace-detailed-panel-2.png
  src/main/pages/che-7/administration-guide/ref_grafana-dashboards-for-che.adoc
Labels: kind/enhancement, status/code-review

#1107 Added Compute Resource Requirements assembly
  .ci/vale/styles/proselint/Airlinese.yml
  .ci/vale/styles/proselint/AnimalLabels.yml
  .ci/vale/styles/proselint/Annotations.yml
  .ci/vale/styles/proselint/Apologizing.yml
  .ci/vale/styles/proselint/Archaisms.yml
  .ci/vale/styles/proselint/But.yml
  .ci/vale/styles/proselint/Cliches.yml
  .ci/vale/styles/proselint/CorporateSpeak.yml
  .ci/vale/styles/proselint/Currency.yml
  .ci/vale/styles/proselint/Cursing.yml
  .ci/vale/styles/proselint/DateCase.yml
  .ci/vale/styles/proselint/DateMidnight.yml
  .ci/vale/styles/proselint/DateRedundancy.yml
  .ci/vale/styles/proselint/DateSpacing.yml
  .ci/vale/styles/proselint/DenzienLabels.yml
  .ci/vale/styles/proselint/Diacritical.yml
  .ci/vale/styles/proselint/GenderBias.yml
  .ci/vale/styles/proselint/GroupTerms.yml
  .ci/vale/styles/proselint/Hedging.yml
  .ci/vale/styles/proselint/Hyperbole.yml
  .ci/vale/styles/proselint/Illusions.yml
  .ci/vale/styles/proselint/Jargon.yml
  .ci/vale/styles/proselint/LGBTOffensive.yml
  .ci/vale/styles/proselint/LGBTTerms.yml
  .ci/vale/styles/proselint/Malapropisms.yml
  .ci/vale/styles/proselint/Needless.yml
  .ci/vale/styles/proselint/Nonwords.yml
  .ci/vale/styles/proselint/Oxymorons.yml
  .ci/vale/styles/proselint/P-Value.yml
  .ci/vale/styles/proselint/RASSyndrome.yml
  .ci/vale/styles/proselint/README.md
  .ci/vale/styles/proselint/Skunked.yml
  .ci/vale/styles/proselint/Spelling.yml
  .ci/vale/styles/proselint/Typography.yml
  .ci/vale/styles/proselint/Uncomparables.yml
  .ci/vale/styles/proselint/Very.yml
  .ci/vale/styles/vocab.txt
  .ci/vale/styles/write-good/Cliches.yml
  .ci/vale/styles/write-good/E-Prime.yml
  .ci/vale/styles/write-good/Illusions.yml
  .ci/vale/styles/write-good/Passive.yml
  .ci/vale/styles/write-good/README.md
  .ci/vale/styles/write-good/So.yml
  .ci/vale/styles/write-good/ThereIs.yml
  .ci/vale/styles/write-good/TooWordy.yml
  .ci/vale/styles/write-good/Weasel.yml
  .vale.ini
  run.sh
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/architecture/che-high-level.png
  src/main/pages/che-7/administration-guide/assembly_che-compute-resource-requirements.adoc
  src/main/pages/che-7/administration-guide/con_a-workspace-example.adoc
  src/main/pages/che-7/administration-guide/con_che-architectural-components.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
Labels: kind/enhancement, status/code-review

#1121 Add trailing slash in permalink: + :page-liquid:
  src/main/pages/che-7/administration-guide/assembly_backup-and-disaster-recovery.adoc
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
  src/main/pages/che-7/administration-guide/con_persistent-volumes-backups.adoc
Labels: kind/enhancement, status/code-review

#1124 Consistency fix
  src/main/pages/che-7/administration-guide/proc_building-a-custom-devfile-registry.adoc
Labels: kind/bug, status/code-review

#1122 Language suggestion according to IBM styleguide
  release-notes/release-6.18.0.md
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
  src/main/pages/che-7/administration-guide/con_persistent-volumes-backups.adoc
  src/main/pages/che-7/administration-guide/proc_checking-important-logs.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-in-the-web-console.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-keycloak-server-logs.adoc
  src/main/pages/che-7/contributor-guide/assembly_branding-che-theia.adoc
  src/main/pages/che-7/contributor-guide/assembly_setup-che-in-tls-mode-with-self-signed-certificate.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_che-usage-with-tls.adoc
  src/main/pages/che-7/contributor-guide/proc_defining-custom-branding-values-for-che-theia.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_generating-self-signed-certificates.adoc
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/end-user-guide/assembly_running-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/installation-guide/proc_finishing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-registering-as-a-new-user.adoc
  src/main/pages/che-7/overview/proc_logging-in-to-che-on-openshift-for-the-first-time-using-oauth.adoc
Labels: status/code-review

#1120 🚧 update with current log watchers grafana graph
  src/main/images/monitoring/monitoring-che-che-server-dashboard-workspace-detailed-panel-2.png
  src/main/pages/che-7/administration-guide/ref_grafana-dashboards-for-che.adoc
Labels: kind/enhancement, status/code-review

#1129 Content for OpenShift version of `Deploying registries`
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-openshift.adoc
Labels: status/code-review

#1128 Better wording in the Database Setup procedure
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
Labels: status/code-review

#1127 Clarify what the CHE_WORKSPACE_NAMESPACE environment variable means.
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/bug, status/code-review

#1125 Set next development version
  pom.xml
Labels: status/code-review

#1133 Random fixes.
  src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
Labels: kind/bug, status/code-review

#1135 enviromnent_docs_gen.sh script fix
  tools/enviromnent_docs_gen.sh
Labels: kind/bug, status/code-review

#1136 Typos fixes
  .vale.ini
  release-notes/release-6.16.0.md
  src/main/_data/samplelist.yml
  src/main/images/workspaces/che-select-workspace.png
  src/main/pages/che-7/administration-guide/assembly_managing-users.adoc
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/administration-guide/proc_extending-che-monitoring-metrics.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-locally-using-a-pre-built-container-image.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-traces-in-jaeger-ui.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-plug-in-broker-logs.adoc
  src/main/pages/che-7/administration-guide/ref_grafana-dashboards-for-che.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-concept-in-detail.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-plug-in-lifecycle.adoc
  src/main/pages/che-7/end-user-guide/con_factory-json-reference.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/bug, status/code-review

#1137 Set correct self signed certificte secret name for Kubernetes infrastructure
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: kind/bug, status/code-review

#1138 Upstream specification and additional content amelioration
  src/main/pages/che-7/administration-guide/assembly_caching-images-for-faster-workspace-start.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
Labels: status/code-review

#1141 i1696 7.9.x version
  src/main/pages/che-7/administration-guide/assembly_caching-images-for-faster-workspace-start.adoc
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
  tools/enviromnent_docs_gen.sh
Labels: status/code-review, target/branch

#1143 Grammar fixes
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
Labels: kind/bug, status/code-review, target/branch

#1142 Fixing the database concept
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
Labels: kind/bug, status/code-review

#1134 Tell how to generate an SSH key
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
Labels: status/code-review

#1131 Common terms capitalisation check
  .ci/vale/styles/CheDocs/CommonTerms.yml
  .vale.ini
Labels: status/code-review

#1140 Added new terms for vale to ignore and new styles
  .ci/vale/styles/Microsoft/Foreign.yml
  .ci/vale/styles/Microsoft/HeadingPunctuation.yml
  .ci/vale/styles/Microsoft/Spacing.yml
  .ci/vale/styles/PlainLanguage/ComplexWords.yml
  .ci/vale/styles/PlainLanguage/Contractions.yml
  .ci/vale/styles/proselint/Airlinese.yml
  .ci/vale/styles/proselint/AnimalLabels.yml
  .ci/vale/styles/proselint/Apologizing.yml
  .ci/vale/styles/proselint/Archaisms.yml
  .ci/vale/styles/proselint/But.yml
  .ci/vale/styles/proselint/Cliches.yml
  .ci/vale/styles/proselint/CorporateSpeak.yml
  .ci/vale/styles/proselint/Currency.yml
  .ci/vale/styles/proselint/Cursing.yml
  .ci/vale/styles/proselint/DateCase.yml
  .ci/vale/styles/proselint/DateMidnight.yml
  .ci/vale/styles/proselint/DateRedundancy.yml
  .ci/vale/styles/proselint/DateSpacing.yml
  .ci/vale/styles/proselint/DenzienLabels.yml
  .ci/vale/styles/proselint/Diacritical.yml
  .ci/vale/styles/proselint/GenderBias.yml
  .ci/vale/styles/proselint/GroupTerms.yml
  .ci/vale/styles/proselint/Hedging.yml
  .ci/vale/styles/proselint/Hyperbole.yml
  .ci/vale/styles/proselint/Illusions.yml
  .ci/vale/styles/proselint/Jargon.yml
  .ci/vale/styles/proselint/LGBTOffensive.yml
  .ci/vale/styles/proselint/LGBTTerms.yml
  .ci/vale/styles/proselint/Malapropisms.yml
  .ci/vale/styles/proselint/Needless.yml
  .ci/vale/styles/proselint/Nonwords.yml
  .ci/vale/styles/proselint/Oxymorons.yml
  .ci/vale/styles/proselint/P-Value.yml
  .ci/vale/styles/proselint/RASSyndrome.yml
  .ci/vale/styles/proselint/Skunked.yml
  .ci/vale/styles/proselint/Spelling.yml
  .ci/vale/styles/proselint/Typography.yml
  .ci/vale/styles/proselint/Uncomparables.yml
  .ci/vale/styles/vocab.txt
  .ci/vale/styles/write-good/Cliches.yml
  .vale.ini
Labels: kind/enhancement, status/code-review

#1144 Typos fixes, proper capitalization.
  .ci/vale/styles/proselint/Spelling.yml
  .ci/vale/styles/vocab.txt
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/con_machine-token-validation.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_checking-important-logs.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-server-logs-on-the-cli.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/administration-guide/ref_omnisharp-theia-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/con_what-is-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/con_workspaces-namespaces-configuration.adoc
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_preparing-azure-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
Labels: kind/bug, status/code-review

#1146 Added subs=none to prevent rendering of {PLUGIN_REMOTE_ENDPOINT_EXECU…
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
Labels: kind/enhancement, status/code-review

#1145 Fixing broken keycloak links, attributes fixes.
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_setting-up-user-federation.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
Labels: kind/bug, status/code-review

#1148 More build fixes.
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
  src/main/pages/che-7/end-user-guide/assembly_che-theia-remote-plugin-image.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
Labels: kind/bug, status/code-review

#1149 Add volumes support and example for cheEditor/chePlugin
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: kind/enhancement, status/code-review

#1150 Cherry-pick 1144: Typos fixes, proper capitalization.
  .ci/vale/styles/proselint/Spelling.yml
  .ci/vale/styles/vocab.txt
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/con_machine-token-validation.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-devfile-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_adding-a-plug-in-at-runtime.adoc
  src/main/pages/che-7/administration-guide/proc_checking-important-logs.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-helm.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-kubernetes-image-puller-using-openshift-templates.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-server-logs-on-the-cli.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/administration-guide/ref_omnisharp-theia-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/con_what-is-a-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_choosing-the-sidecar-image.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-the-workspace-and-adding-tooling.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_remotely-accessing-workspaces-using-kubectl.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/con_workspaces-namespaces-configuration.adoc
  src/main/pages/che-7/overview/proc_enabling-ssl-on-openshift-4.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-cert-manager.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_preparing-azure-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
Labels: kind/bug, status/code-review, target/branch

#1151 Cherry-pick 1145: Fixing broken keycloak links. Weird attribute fix.
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_setting-up-user-federation.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
Labels: kind/bug, status/code-review, target/branch

#1152 Enhancing a procedure about SSH pairs and fixing a typo
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
Labels: kind/bug, status/code-review

#1153 Formatting, spelling fixes. New words to ingore. pre scope to be igno…
  .ci/vale/styles/vocab.txt
  .vale.ini
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
  src/main/pages/che-7/administration-guide/ref_creating-a-bug-report.adoc
  src/main/pages/che-7/contributor-guide/proc_defining-custom-branding-values-for-che-theia.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/con_factory-json-reference.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/overview/ref_about-hosted-che.adoc
Labels: kind/bug, status/code-review

#1156 Fix caps in menu
  src/main/_data/sidebars/che_7_docs.yml
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1155 Fix lang, formatting in 'Che resources'.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_calculating-che-resource-requirements.adoc
  src/main/pages/che-7/administration-guide/assembly_che-compute-resource-requirements.adoc
  src/main/pages/che-7/administration-guide/con_a-workspace-example.adoc
  src/main/pages/che-7/administration-guide/con_che-architectural-components.adoc
  src/main/pages/che-7/administration-guide/con_controller-requirements.adoc
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1154 Applying IBM styl guide, fixing typos
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-registries.adoc
  src/main/pages/che-7/contributor-guide/ref_debug-adapter-protocol.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-https.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1161 Add known issue with SameSite on non-tls installations
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/bug, status/code-review

#1163 Bugfixes.
  src/main/pages/che-7/administration-guide/con_authorization-and-user-management.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-che-to-work-with-keycloak.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
  src/main/pages/che-7/administration-guide/ref_che-tracing-codebase-overview-and-extension-guide.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file.adoc
  src/main/pages/che-7/overview/proc_finding-the-cluster-where-the-hosted-che-workspace-is-running.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1164 Quick contexts fixups.
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/administration-guide/con_organization-and-sub-organization-administration.adoc
  src/main/pages/che-7/administration-guide/con_organizations-in-eclipse-che.adoc
  src/main/pages/che-7/administration-guide/con_roles-in-an-organization.adoc
  src/main/pages/che-7/administration-guide/con_root-organizations-and-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/con_workspaces-in-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_adding-members-to-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_adding-members-to-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_allocating-resources-for-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-smtp-and-email-notifications.adoc
  src/main/pages/che-7/administration-guide/proc_creating-an-organization.adoc
  src/main/pages/che-7/administration-guide/proc_creating-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_deleting-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_displaying-the-list-of-organization.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_leaving-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_managing-limits.adoc
  src/main/pages/che-7/administration-guide/proc_removing-organization-and-sub-organization-members.adoc
  src/main/pages/che-7/administration-guide/proc_renaming-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_setting-up-user-federation.adoc
  src/main/pages/che-7/administration-guide/proc_updating-organization-and-sub-organization-member-roles.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1162 Removed duplicating, unsuitable or poorely performing write-good styles.
  .ci/vale/styles/CheDocs/Attributes.yml
  .ci/vale/styles/write-good/E-Prime.yml
  .ci/vale/styles/write-good/Illusions.yml
  .ci/vale/styles/write-good/Passive.yml
  .ci/vale/styles/write-good/So.yml
  .ci/vale/styles/write-good/TooWordy.yml
  .ci/vale/styles/write-good/Weasel.yml
  .vale.ini
Labels: status/code-review

#1159 Fixing the headings in CG,Extensions,IG
  src/main/pages/che-7/contributor-guide/assembly_branding-che-theia.adoc
  src/main/pages/che-7/contributor-guide/assembly_che-extensibility-reference.adoc
  src/main/pages/che-7/contributor-guide/assembly_developing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/assembly_publishing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/assembly_setup-che-in-tls-mode-with-self-signed-certificate.adoc
  src/main/pages/che-7/contributor-guide/assembly_testing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-development-flow.adoc
  src/main/pages/che-7/contributor-guide/con_che-theia-plug-in-registries.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-into-a-workspace.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-debugger.adoc
  src/main/pages/che-7/contributor-guide/proc_adding-support-for-a-new-language.adoc
  src/main/pages/che-7/contributor-guide/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  src/main/pages/che-7/contributor-guide/proc_building-a-che-theia-container-image-with-custom-branding.adoc
  src/main/pages/che-7/contributor-guide/proc_che-usage-with-tls.adoc
  src/main/pages/che-7/contributor-guide/proc_defining-custom-branding-values-for-che-theia.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_developing-che-theia-plug-ins-using-che.adoc
  src/main/pages/che-7/contributor-guide/proc_generating-self-signed-certificates.adoc
  src/main/pages/che-7/contributor-guide/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  src/main/pages/che-7/contributor-guide/proc_packaging-a-visual-studio-code-plug-in-for-che.adoc
  src/main/pages/che-7/contributor-guide/proc_sharing-access-to-a-workspace.adoc
  src/main/pages/che-7/contributor-guide/proc_sharing-your-che-theia-plug-in-with-a-factory.adoc
  src/main/pages/che-7/contributor-guide/proc_testing-che-theia-with-custom-branding.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/contributor-guide/ref_language-server-protocol.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/assembly_openshift-connector-overview.adoc
  src/main/pages/che-7/installation-guide/assembly_uninstalling-che.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che-on-openshift-4-using-the-openshift-web-console.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/installation-guide/con_deployment-architecture-diagram.adoc
  src/main/pages/che-7/installation-guide/con_target-platforms.adoc
  src/main/pages/che-7/installation-guide/proc_adding-custom-certificates-to-trust-store.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-persistent-volumes-strategy.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-che-with-and-without-keycloak.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_finishing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_preparing-the-upgrade-of-che-on-openshift-using-the-operator.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-chectl-installation.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-3-using-the-cli-management-tool.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-4-using-the-cli-management-tool.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/proc_creating-the-che-project-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1168 Bugfixes. Added missing contexts. Removed redundant spaces.
  .ci/vale/styles/vocab.txt
  src/main/pages/che-7/administration-guide/con_kubernetes-image-puller-overview.adoc
  src/main/pages/che-7/contributor-guide/con_che-extension-points.adoc
  src/main/pages/che-7/contributor-guide/ref_che-theia-plug-in-api.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-a-git-repository-via-ssh.adoc
  src/main/pages/che-7/installation-guide/con_che-configmaps-and-their-behavior.adoc
  src/main/pages/che-7/overview/con_persistent-volume-configuration.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: kind/bug, need-cherry-pick/7.9, status/code-review

#1170 Add screenshot thumbnail.
  src/main/pages/che-7/administration-guide/proc_viewing-camel-logs-in-the-output-panel.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1171 usptream-synergy-with-crw-RNaKI
  src/main/pages/che-7/overview/con_openshift-developer-perspective-integration-with-che.adoc
Labels: status/code-review

#1172 usptream-synergy-with-crw-RNaKI
  src/main/pages/che-7/overview/con_openshift-developer-perspective-integration-with-che.adoc
Labels: status/code-review, target/branch
