Repository eclipse-che/che-docs, pull requests merged in 2020-02, with the labels that each got.

#1062 Language and formatting suggestions (review for 1039 PR).
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
Labels: status/code-review, target/branch

#1066 Adding Yana as a CODEOWNER.
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review

#1039 Install Eclipse Che uses storage classes.
  src/main/pages/che-7/overview/proc_installing-che-using-storage-classes.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: kind/enhancement, status/code-review

#1069 Execute environment variable docs generation during publish docs ci process
  Jenkinsfile
Labels: status/code-review

#1071 Language suggestions and restructure of #1022
  src/main/pages/che-7/end-user-guide/assembly_che-theia-remote-plugin-image.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/con_che-theia-remote-plugin-image.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
Labels: status/code-review, target/branch

#1022 Add info about remote plugin endpoint and remote plugin images.
  src/main/pages/che-7/end-user-guide/assembly_che-theia-remote-plugin-image.adoc
  src/main/pages/che-7/end-user-guide/assembly_what-is-a-che-theia-plug-in.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc
Labels: kind/enhancement, status/code-review

#1063 First batch of enhanced logs. New attributes applied
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-openshift.adoc
  src/main/pages/che-7/contributor-guide/proc_che-usage-with-tls.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
  src/main/pages/che-7/installation-guide/ref_che-configmaps-fields-reference.adoc
  src/main/pages/che-7/overview/con_openshift-developer-perspective-integration-with-che.adoc
  src/main/pages/che-7/overview/examples/che-cluster-deployment-openshift-logs.log
  src/main/pages/che-7/overview/examples/che-cluster-url-logs.log
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/ref_che-7-known-issues.adoc
Labels: status/code-review

#1065 1575 logs replacing - second batch
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
Labels: status/code-review

#1070 Attributes and logs fix
  src/main/pages/che-7/administration-guide/proc_viewing-che-server-logs-on-the-cli.adoc
  src/main/pages/che-7/installation-guide/assembly_upgrading-che.adoc
Labels: kind/bug, status/code-review

#1067 Updating terms of service: RAM increase to 7GB, removing misleading CPU info and renaming ephemeral mode to the Temporary Storage
  src/main/pages/che-7/overview/ref_about-hosted-che.adoc
Labels: status/code-review

#1077 Fixes in some other documents
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
Labels: kind/bug, status/code-review

#1037 managing users
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_configuring-authorization.adoc
  src/main/pages/che-7/administration-guide/assembly_managing-users.adoc
  src/main/pages/che-7/administration-guide/assembly_troubleshooting-for-che-administrators.adoc
  src/main/pages/che-7/administration-guide/assembly_using-organizations.adoc
  src/main/pages/che-7/administration-guide/con_authorization-and-user-management.adoc
  src/main/pages/che-7/administration-guide/con_organization-and-sub-organization-administration.adoc
  src/main/pages/che-7/administration-guide/con_organizations-in-eclipse-che.adoc
  src/main/pages/che-7/administration-guide/con_roles-in-an-organization.adoc
  src/main/pages/che-7/administration-guide/con_root-organizations-and-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/con_workspaces-in-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_adding-members-to-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_adding-members-to-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_allocating-resources-for-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-che-to-work-with-keycloak.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-keycloak-tokens.adoc
  src/main/pages/che-7/administration-guide/proc_configuring-smtp-and-email-notifications.adoc
  src/main/pages/che-7/administration-guide/proc_creating-an-organization.adoc
  src/main/pages/che-7/administration-guide/proc_creating-sub-organizations.adoc
  src/main/pages/che-7/administration-guide/proc_deleting-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_displaying-the-list-of-organization.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  src/main/pages/che-7/administration-guide/proc_leaving-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_managing-limits.adoc
  src/main/pages/che-7/administration-guide/proc_managing-users.adoc
  src/main/pages/che-7/administration-guide/proc_removing-organization-and-sub-organization-members.adoc
  src/main/pages/che-7/administration-guide/proc_removing-user-data.adoc
  src/main/pages/che-7/administration-guide/proc_renaming-an-organization-or-sub-organization.adoc
  src/main/pages/che-7/administration-guide/proc_setting-up-user-federation.adoc
  src/main/pages/che-7/administration-guide/proc_updating-organization-and-sub-organization-member-roles.adoc
  src/main/pages/che-7/administration-guide/proc_using-protocol-based-providers.adoc
  src/main/pages/che-7/end-user-guide/con_factory-json-reference.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
Labels: status/code-review

#1081 Add minimal versions in prerequisites
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minishift-using-chectl.adoc
Labels: kind/enhancement, status/code-review

#1082 Update Gemfile.
  src/main/Gemfile.lock
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1083 Add factory doc redirect.
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
Labels: Che-7, kind/bug, status/code-review

#1064 Redesign Che4z section as one page
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-release-information.adoc
Labels: status/code-review

#1074 Clarify process for adding a VS Code extension to Che
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
Labels: status/code-review

#1075 Make note of assumptions on the secure endpoints
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
Labels: status/code-review

#1079 Add CPU limis/request into plugin container description
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
Labels: kind/enhancement, status/code-review

#1073 Fixing typos in multiple docs and enhancing the oc procedure
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
  src/main/pages/che-7/installation-guide/proc_upgrading-che-on-openshift-4-using-the-cli-management-tool.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minishift-using-chectl.adoc
Labels: kind/bug, status/code-review

#1076 Instructions for OpenShift OAuth provider
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-oauth-authorization.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/end-user-guide/assembly_version-control.adoc
  src/main/pages/che-7/end-user-guide/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
Labels: kind/task, status/code-review

#1084 Updated CSS to improve rendering of callouts.
  src/main/css/asciidoc.css
Labels: kind/enhancement, status/code-review

#1088 [release] Bump to 7.10.0-SNAPSHOT in master
  pom.xml
Labels: status/code-review

#1086 typo on link:{site-baseurl}che-7/
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
Labels: status/code-review

#1090 Removed harcoded instances of eclipse.org
  src/main/pages/che-7/administration-guide/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
  src/main/pages/che-7/end-user-guide/assembly_configuring-github-oauth.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
Labels: status/code-review

#1091 I15219 quick start redir
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1068 Fixing Prometheus procedure
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/examples/prometheus-config.yaml
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-and-exposing-che-metrics.adoc
Labels: kind/bug, status/code-review

#1080 I1463 open shift connector - ready for the review
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_customizing-developer-environments.adoc
  src/main/pages/che-7/extensions/assembly_openshift-connector-overview.adoc
  src/main/pages/che-7/extensions/con_features-of-openshift-connector.adoc
  src/main/pages/che-7/extensions/proc_authenticating-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/extensions/proc_installing-openshift-connector-in-eclipse-che.adoc
Labels: status/code-review

#1093 Fix metadata in assemblies from Admin Guide
  src/main/pages/che-7/administration-guide/assembly_authenticating-in-a-che-workspace.adoc
  src/main/pages/che-7/administration-guide/assembly_authenticating-to-the-che-server.adoc
  src/main/pages/che-7/administration-guide/assembly_authenticating-users.adoc
  src/main/pages/che-7/administration-guide/assembly_authorizing-users.adoc
  src/main/pages/che-7/administration-guide/assembly_building-and-running-a-custom-registry-image.adoc
  src/main/pages/che-7/administration-guide/assembly_configuring-authorization.adoc
  src/main/pages/che-7/administration-guide/assembly_customizing-the-devfile-and-plug-in-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_deploying-the-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_editing-a-devfile-and-plug-in-at-runtime.adoc
  src/main/pages/che-7/administration-guide/assembly_managing-users.adoc
  src/main/pages/che-7/administration-guide/assembly_modifying-the-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_monitoring-che.adoc
  src/main/pages/che-7/administration-guide/assembly_removing-user-data.adoc
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_securing-che.adoc
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/assembly_troubleshooting-for-che-administrators.adoc
  src/main/pages/che-7/administration-guide/assembly_using-organizations.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-server-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-theia-ide-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-workspaces-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-external-service-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-keycloak-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-camel.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-dotnet-with-netcoredebugoutput-plug-in.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-dotnet-with-omnisharp-theia-plug-in.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-go.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-intelephense.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-java.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-typescript.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-xml.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-for-yaml.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-logs-from-language-servers-and-debug-adapters.adoc
Labels: kind/enhancement, status/code-review

#1095 Managing users using Keycloak fixes
  src/main/pages/che-7/administration-guide/assembly_configuring-authorization.adoc
  src/main/pages/che-7/administration-guide/proc_managing-users-using-keycloak.adoc
  src/main/pages/che-7/administration-guide/proc_managing-users.adoc
Labels: kind/bug, status/code-review

#1089 Added a prerequisite for using the supported browser.
  src/main/pages/che-7/end-user-guide/proc_navigating-che-using-the-dashboard-on-minishift.adoc
  src/main/pages/che-7/end-user-guide/proc_navigating-che-using-the-dashboard-on-openshift.adoc
Labels: kind/enhancement, status/code-review

#1096 I1640 proper labeling open shift console upstream backup
  src/main/_config.yml
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_viewing-the-state-of-the-che-cluster-deployment-in-openshift-4-web-console.adoc
Labels: status/code-review

#1097 New run.sh functionalities
  Dockerfile
  run.sh
Labels: status/code-review

#1092 Removing optional project definition from the devfile
  devfile.yaml
Labels: status/code-review

#1098 Fix broken attribute prod-shor and add a vale rule for it
  .ci/vale/styles/ModularDoc/Attributes.yml
  .vale.ini
  src/main/pages/che-7/extensions/proc_creating-components-with-openshift-connector-in-eclipse-che.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
Labels: kind/bug, status/code-review

#1094 che #14240 Adding 'Backup and Disaster Recovery' documentation
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_backup-and-disaster-recovery.adoc
  src/main/pages/che-7/administration-guide/con_database-setup.adoc
  src/main/pages/che-7/administration-guide/con_persistent-volumes-backups.adoc
Labels: kind/task, status/code-review

#1099 fix overview
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
Labels: kind/bug, status/code-review

#1100 fix context
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
Labels: kind/bug, status/code-review
