Repository eclipse-che/che-docs, pull requests merged in 2020-06, with the labels that each got.

#1292 Fix navigation
  src/main/_data/sidebars/che_7_docs.yml
Labels: kind/bug, status/code-review

#1287 WIP: Add article about mounting secrets as files and env; - Reviewing by mmaler
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_mounting-secrets-as-file-or-env-variable-in-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/ref_the-use-of-annotations-in-a-process-of-mounting-secret-into-a-workspace-container.adoc
Labels: kind/enhancement, status/code-review

#1293 Add article about mounting secrets as files and env;
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_mounting-secrets-as-file-or-env-variable-in-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/ref_the-use-of-annotations-in-a-process-of-mounting-secret-into-a-workspace-container.adoc
Labels: kind/enhancement, status/code-review, target/branch

#1289 Refresh documentation about CPU & RAM limits;
  src/main/pages/che-7/administration-guide/proc_workspaces-requirements.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.9.x, status/code-review

#1295 Moving Hosted Che FAQ to the che-docs
  src/main/pages/che-7/overview/assembly_hosted-che.adoc
  src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: kind/task, status/code-review

#1294 Add conditionals around Helm mentions in IG.
  src/main/pages/che-7/installation-guide/proc_adding-custom-certificates-to-trust-store.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1296 fix contribute factory: link + devfile
  README.md
  devfile.yaml
Labels: kind/bug, status/code-review

#1297 Add antora and vale containers in Jenkinsfile
  Jenkinsfile
Labels: kind/enhancement, status/code-review

#1299 Fixing env var name for super-privileged mode. Removing deprecated reference to che.env file
  src/main/pages/che-7/administration-guide/con_super-privileged-mode.adoc
Labels: kind/bug, status/code-review

#1300 Adding GDPR section to the 'removing-user-data' page
  src/main/pages/che-7/administration-guide/assembly_removing-user-data.adoc
Labels: kind/task, status/code-review

#1301 fix link to jwtproxy
  src/main/pages/che-7/administration-guide/assembly_authenticating-users.adoc
Labels: kind/bug, need-cherry-pick/7.9.x, status/code-review

#1298 i1957 public certificates - Rewriting the Adding custom public SSL certificates to Che trust-store
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_configuring-openshift-oauth.adoc
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/proc_adding-custom-certificates-to-trust-store.adoc
  src/main/pages/che-7/installation-guide/proc_adding-self-signed-ssl-certificates-to-che.adoc
Labels: status/code-review

#1304 Rename SSL trust-store procedure.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_configuring-che-overview.adoc
  src/main/pages/che-7/installation-guide/proc_mounting-custom-ssl-certificates-to-che-workspace-pods.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#1305 Move self-signed certs install to IG.
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-openhift3-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_generating-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_using-che-with-tls.adoc
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#1307 archiveArtifacts in Jenkinsfile
  Jenkinsfile
Labels: status/code-review

#1306 Change placeholder values for consistency.
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
Labels: kind/bug, need-cherry-pick/7.9.x, status/code-review

#1309 Adding procedure steps for all OS + examples
  src/main/images/contributor/macOS-adding-certificate.png
  src/main/pages/che-7/installation-guide/proc_using-che-with-tls.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1311 language fixes for TLS procedure
  src/main/images/contributor/che-tls-chrome-import_1.png
  src/main/images/contributor/che-tls-chrome-import_2.png
  src/main/images/contributor/che-tls-firefox-import_1.png
  src/main/images/contributor/che-tls-firefox-import_2.png
  src/main/images/contributor/che-tls-firefox-import_3.png
  src/main/images/contributor/che-tls-firefox-import_4.png
  src/main/pages/che-7/installation-guide/proc_using-che-with-tls.adoc
Labels: kind/bug, kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1308 Supported platforms upstream
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/installation-guide/con_supported_platforms.adoc
  src/main/pages/che-7/installation-guide/examples/che-ref_supported-platforms-and-installation-methods.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_introduction-to-eclipse-che.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1313 Fix sidebar.
  linkcheckerrc
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/examples/system-variables.adoc
  src/main/pages/che-7/overview/con_che-user-dashboard.adoc
  tools/enviromnent_docs_gen.sh
Labels: Che-7, kind/bug, kind/docs, level/beginner, severity/P1, status/code-review

#1314 Kubernetes image puller operator
  src/main/pages/che-7/administration-guide/assembly_caching-images-for-faster-workspace-start.adoc
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/examples/image_puller/example_image_puller.yaml
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-operator.adoc
Labels: kind/task, status/code-review

#1316 Pollishing the procedure
  src/main/pages/che-7/installation-guide/proc_using-che-with-tls.adoc
Labels: status/code-review

#1315 Added conditionals for strategies
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1318 fix double quotes in ids
  src/main/pages/che-7/end-user-guide/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
Labels: kind/bug, status/code-review

#1319 Chapter 1 fixes
  src/main/_config.yml
  src/main/pages/che-7/administration-guide/proc_building-a-custom-devfile-registry.adoc
  src/main/pages/che-7/administration-guide/proc_including-the-plug-in-binaries-in-the-registry-image.adoc
Labels: kind/bug, status/code-review

#1320 fix formatting
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
Labels: kind/bug, status/code-review

#1290 Extending the telemetry system and implementing custom backends
  src/main/_data/sidebars/che_7_docs.yml
  src/main/images/telemetry/custom_telemetry_plugin.png
  src/main/images/telemetry/telemetry_diagram.png
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
  src/main/pages/che-7/extensions/examples/telemetry/AnalyticsManagerSkeleton.java
  src/main/pages/che-7/extensions/examples/telemetry/MainConfiguration.java
  src/main/pages/che-7/extensions/examples/telemetry/che_cluster_with_custom_plugin.yaml
  src/main/pages/che-7/extensions/examples/telemetry/destroy.java
  src/main/pages/che-7/extensions/examples/telemetry/increaseDuration.java
  src/main/pages/che-7/extensions/examples/telemetry/isEnabled.java
  src/main/pages/che-7/extensions/examples/telemetry/main.go
  src/main/pages/che-7/extensions/examples/telemetry/onActivity.java
  src/main/pages/che-7/extensions/examples/telemetry/onEvent.java
  src/main/pages/che-7/extensions/examples/telemetry/plugin.adoc
  src/main/pages/che-7/extensions/examples/telemetry/pom_snippet.xml
  src/main/pages/che-7/extensions/examples/telemetry/sample_meta.yaml
  src/main/pages/che-7/extensions/examples/telemetry/settings.xml
  src/main/pages/che-7/extensions/examples/telemetry/webserver.yaml
  src/main/pages/che-7/installation-guide/examples/system-variables.adoc
Labels: kind/task, status/code-review

#1302 settings.xml across workspaces
  src/main/pages/che-7/end-user-guide/assembly_using-maven-artifact-repositories.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-maven-settings-xml-file-across-workspaces.adoc
Labels: kind/enhancement, status/code-review

#1323 Link id fixes
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/end-user-guide/assembly_importing-a-kubernetes-application-into-a-workspace.adoc
  src/main/pages/che-7/end-user-guide/assembly_mounting-secrets-as-file-or-env-variable-in-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/assembly_remotely-accessing-workspaces.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-a-kubernetes-application-to-an-existing-workspace-using-the-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_generating-a-devfile-from-an-existing-kubernetes-application.adoc
  src/main/pages/che-7/end-user-guide/proc_including-a-kubernetes-application-in-a-workspace-devfile-definition.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/ref_the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container.adoc
  src/main/pages/che-7/installation-guide/proc_generating-self-signed-certificates.adoc
Labels: Che-7, kind/bug, kind/docs, status/code-review

#1325 creating and moving files
  src/main/_config.yml
Labels: status/code-review, target/branch

#1326 Section2 ag fixes upstream
  src/main/images/logs/viewing-camel-logs-in-the-output-panel.png
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-server-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-theia-ide-logs.adoc
  src/main/pages/che-7/administration-guide/proc_logging-the-client-server-traffic-for-debug-adapters.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-intelephense-events-in-the-output-panel.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-logs-for-php-debug.adoc
Labels: kind/bug, status/code-review

#1328 document subPath limitation
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
Labels: kind/bug, status/code-review

#1329 Add CPU requests/limits to openshift, helm installation
  src/main/pages/che-7/administration-guide/con_image-puller-overview.adoc
  src/main/pages/che-7/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_parameters.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-image-puller-using-helm.adoc
Labels: kind/enhancement, status/code-review

#1330 Pr 1265
  .gitignore
  src/main/_config.yml
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
  src/main/pages/che-7/end-user-guide/con_workspaces-overview.adoc
  src/main/pages/che-7/installation-guide/examples/system-variables.adoc
  src/main/pages/che-7/overview/assembly_3-minutes-to-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_accessing-che-from-openshift-developer-perspective.adoc
  src/main/pages/che-7/overview/assembly_che-quick-starts.adoc
  src/main/pages/che-7/overview/assembly_deploying-che-on-kubernetes-on-aws.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-aws.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-bare-metal-using-kubespray.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-codeready-containers.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-docker-desktop.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-kind.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-microsoft-azure.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minishift.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-openshift-4-using-operatorhub.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-premise-with-kubespray.adoc
  src/main/pages/che-7/overview/assembly_installing-chectl.adoc
  src/main/pages/che-7/overview/assembly_running-che-locally.adoc
  src/main/pages/che-7/overview/assembly_using-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/con_openshift-developer-perspective-integration-with-che.adoc
  src/main/pages/che-7/overview/proc_configuring-the-metallb-load-balancer-on-kubernetes.adoc
  src/main/pages/che-7/overview/proc_finding-che-cluster-url-using-openshift-4-cli-tools.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-azure-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-docker-desktop-using-helm.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-google-cloud-platform-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kind-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubernetes-using-the-chectl-command.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubespray-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator.adoc
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  src/main/pages/che-7/overview/proc_installing-load-balancer-on-a-bare-metal-cluster.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-codeready-containers-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minikube-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-multi-user-che-on-minishift-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-storage-for-kubernetes.adoc
  src/main/pages/che-7/overview/proc_installing-storage-on-a-bare-metal-cluster.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-linux-or-macos.adoc
  src/main/pages/che-7/overview/proc_installing-the-chectl-management-tool-on-windows.adoc
  src/main/pages/che-7/overview/proc_preparing-openshift-3-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_preparing-the-aws-system-for-installing-che.adoc
  src/main/pages/che-7/overview/proc_upgrading-the-chectl-management-tool.adoc
  src/main/pages/che-7/overview/proc_using-codeready-containers-to-set-up-openshift-4.adoc
  src/main/pages/che-7/overview/proc_using-docker-desktop-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/proc_using-kubespray-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.adoc
  src/main/pages/che-7/overview/proc_using-minishift-to-set-up-openshift-3.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
  tools/enviromnent_docs_gen.sh
Labels: Che-7, kind/docs, kind/enhancement, status/code-review

#1322 Apply changes related to secrets mount override;
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/examples/che-ref_a-kubernetes-secret-as-a-file.adoc
  src/main/pages/che-7/end-user-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
  src/main/pages/che-7/end-user-guide/examples/che-ref_annotations-description.adoc
  src/main/pages/che-7/end-user-guide/proc_defining-maven-settings-xml-file-across-workspaces.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/ref_the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container.adoc
Labels: kind/enhancement, kind/task, need-cherry-pick/7.9.x, status/code-review

#1334 Fix broken quickstarts links
  src/main/pages/che-7/overview/assembly_installing-che-on-codeready-containers.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-docker-desktop.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-kind.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minikube.adoc
  src/main/pages/che-7/overview/assembly_installing-che-on-minishift.adoc
Labels: kind/bug, status/code-review

#1332 Fixes for installing on OpenShift 4
  .vale/styles/vocab.txt
  src/main/pages/che-7/overview/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/bug, status/code-review

#1333 Modularizing and adding conditionals.
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
  src/main/pages/che-7/end-user-guide/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1336 Technical feedback
  src/main/pages/che-7/administration-guide/assembly_installing-the-jaeger-tracing-tool.adoc
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/assembly_tracing-che.adoc
  src/main/pages/che-7/administration-guide/assembly_viewing-che-workspaces-logs.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-plug-in-broker-logs.adoc
  src/main/pages/che-7/administration-guide/proc_viewing-postgresql-server-logs.adoc
Labels: need-cherry-pick/7.9.x, status/code-review

#1338 fix id
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
Labels: kind/bug, need-cherry-pick/7.9.x, status/code-review

#1337 Fix broken URLs.
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
  src/main/pages/che-7/extensions/assembly_eclipse-che4z.adoc
  src/main/pages/che-7/extensions/assembly_telemetry.adoc
  src/main/pages/che-7/installation-guide/examples/system-variables.adoc
Labels: kind/bug, status/code-review

#1343 Fix ids and comment out non-existing xref
  src/main/pages/che-7/administration-guide/assembly_installing-the-jaeger-tracing-tool.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc
  src/main/pages/che-7/end-user-guide/proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc
Labels: kind/bug, status/code-review

#1341 Put module in conditionals
  src/main/pages/che-7/end-user-guide/assembly_configuring-workspace-exposure-strategies.adoc
Labels: status/code-review

#1342 Add prod-prev-ver-major.
  src/main/_config.yml
  src/main/pages/che-7/end-user-guide/assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_accessing-che-6-workspace-configuration.adoc
  src/main/pages/che-7/end-user-guide/proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc
  src/main/pages/che-7/end-user-guide/ref_comparing-che-6-workspace-to-a-devfile.adoc
Labels: Che-7, kind/bug, kind/docs, need-cherry-pick/7.9.x, status/code-review

#1344 Adding missing information
  src/main/_config.yml
  src/main/pages/che-7/overview/assembly_che-workspaces-architecture.adoc
  src/main/pages/che-7/overview/con_che-editor-plug-in.adoc
  src/main/pages/che-7/overview/con_che-server.adoc
Labels: kind/enhancement, need-cherry-pick/7.9.x, status/code-review

#1346 Updated docs for creating a workspace from code samples
  src/main/images/workspaces/che-config-projects-add-git.png
  src/main/images/workspaces/che-config-projects-add-github.png
  src/main/images/workspaces/che-create-and-open.png
  src/main/images/workspaces/che-sample-card.png
  src/main/images/workspaces/che-select-devfile.png
  src/main/images/workspaces/che-select-sample.png
  src/main/images/workspaces/che-select-workspace.png
  src/main/images/workspaces/che-stack-list.png
  src/main/images/workspaces/create-and-open.png
  src/main/images/workspaces/workspace-config-projects.png
  src/main/pages/che-7/end-user-guide/assembly_creating-a-workspace-from-code-sample.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace-from-the-user-dashboard.adoc
  src/main/pages/che-7/end-user-guide/proc_changing-the-configuration-of-an-existing-workspace.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard-get-started.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-user-dashboard.adoc
Labels: kind/task, status/code-review

#1347 Tools improvements
  Jenkinsfile
  devfile.yaml
  tools/environment_docs_gen.sh
  tools/newtopic.sh
  tools/test-adoc.sh
Labels: status/code-review

#1340 Pr 1331
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-3.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-4.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-openhift3-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_generating-self-signed-tls-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_importing-self-signed-tls-certificates-to-browsers.adoc
  src/main/pages/che-7/installation-guide/proc_using-che-with-tls.adoc
Labels: Che-7, kind/docs, kind/enhancement, kind/task, status/code-review, target/branch

#1348 Update CONTRIBUTION.md to make it dogfooding centric
  CONTRIBUTION.md
Labels: kind/enhancement, status/code-review

#1331 Change docs according self-signed certificate flag automation
  src/main/_config.yml
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-3.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-certificates-on-openhift-4.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-openhift3-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_deploying-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/installation-guide/proc_generating-self-signed-tls-certificates.adoc
  src/main/pages/che-7/installation-guide/proc_importing-self-signed-tls-certificates-to-browsers.adoc
  src/main/pages/che-7/installation-guide/proc_using-che-with-tls.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-kubespray-using-chectl.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
  src/main/pages/che-7/overview/ref_che-deployment-options-using-chectl.adoc
Labels: kind/task, status/code-review
