Repository eclipse-che/che-docs, pull requests merged in 2020-01, with the labels that each got.

#979 Add ci scripts
  .ci/cico_build.sh
  .ci/cico_build_nightly.sh
  .ci/cico_build_release.sh
  .ci/cico_common.sh
Labels: kind/enhancement, status/code-review

#1006 How to collect logs using chectl
  src/main/_data/sidebars/che_7_docs.yml
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
Labels: Che-7, kind/docs, kind/task, status/code-review

#1040 sh tools/substitutions.sh
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
  src/main/pages/che-7/administration-guide/assembly_customizing-the-devfile-and-plug-in-registries.adoc
  src/main/pages/che-7/administration-guide/assembly_installing-the-jaeger-tracing-tool.adoc
  src/main/pages/che-7/administration-guide/assembly_retrieving-che-logs.adoc
  src/main/pages/che-7/administration-guide/proc_deploying-registries-in-kubernetes.adoc
  src/main/pages/che-7/administration-guide/proc_enabling-che-metrics-collections.adoc
  src/main/pages/che-7/administration-guide/proc_installing-jaeger-using-operatorhub-on-openshift-4.adoc
  src/main/pages/che-7/administration-guide/proc_installing-the-jaeger-tracing-tool-for-che-on-openshift-4.adoc
  src/main/pages/che-7/contributor-guide/assembly_testing-che-theia-plug-ins.adoc
  src/main/pages/che-7/contributor-guide/proc_testing-che-theia-with-custom-branding.adoc
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_importing-a-vs-code-extension-in-the-che-theia-editor.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc
  src/main/pages/che-7/end-user-guide/ref_che-theia-plug-in-metadata.adoc
  src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc
  src/main/pages/che-7/installation-guide/proc_uninstalling-che-after-operatorhub-installation.adoc
  src/main/pages/che-7/overview/con_che-editor-plug-in.adoc
  src/main/pages/che-7/overview/con_che-plug-in-broker.adoc
  src/main/pages/che-7/overview/con_che-plug-ins.adoc
  src/main/pages/che-7/overview/con_che-workspace-creation-flow.adoc
  tools/substitutions.sed
Labels: status/code-review

#1042 Formatting fixes.
  src/main/pages/che-7/administration-guide/assembly_modifying-the-registries.adoc
  src/main/pages/che-7/administration-guide/ref_grafana-dashboards-for-che.adoc
  src/main/pages/che-7/overview/proc_installing-che-on-openshift-3-using-the-operator-and-ssl.adoc
Labels: kind/bug, status/code-review

#1043 Update che4z-installing.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#1044 Commented out the `ifdef`.
  src/main/pages/che-7/administration-guide/assembly_collecting-logs-using-chectl.adoc
Labels: status/code-review

#1045 prod-url-replacement-first-batch
  src/main/pages/che-7/administration-guide/proc_authenticating-to-the-che-server-using-openid.adoc
  src/main/pages/che-7/end-user-guide/con_workspace-exposure-strategies.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  src/main/pages/che-7/end-user-guide/proc_overriding-devfile-values-using-factory-parameters.adoc
  src/main/pages/che-7/extensions/che4z-installing.adoc
Labels: status/code-review

#1048 Use run.sh -war for maven build
  pom.xml
Labels: status/code-review

#1054 Removing obsolete information about default plugin registry
  src/main/pages/che-7/overview/con_che-plug-in-registry.adoc
Labels: status/code-review

#1053 Removing obsolete information about default devfile-registry
  src/main/pages/che-7/overview/con_che-devfile-registry.adoc
Labels: status/code-review

#1052 Fixing broken links.
  src/main/pages/che-7/end-user-guide/proc_adding-the-vs-code-extension-using-the-che-plugins-panel.adoc
  src/main/pages/che-7/end-user-guide/proc_creating-a-new-workspace-from-the-dashboard.adoc
  src/main/pages/che-7/installation-guide/assembly_installing-che-in-restricted-environment.adoc
  src/main/pages/che-7/overview/proc_accessing-che-from-red-hat-applications-menu.adoc
Labels: kind/bug, status/code-review

#1041 Add script to autogenerate Che configuration properties documentation
  .gitignore
  src/main/pages/che-7/administration-guide/ref_configuring-system-variables.adoc
  tools/enviromnent_docs_gen.sh
Labels: kind/task, status/code-review

#1051 Doc changes related to default project source from Git repository
  src/main/pages/che-7/end-user-guide/con_a-minimal-devfile.adoc
  src/main/pages/che-7/end-user-guide/proc_writing-a-devfile-for-your-project.adoc
Labels: kind/enhancement, status/code-review

#1057 Vale config
  .ci/vale/styles/PlainLanguage/ComplexWords.yml
  .ci/vale/styles/PlainLanguage/Contractions.yml
  .ci/vale/styles/PlainLanguage/PassiveVoice.yml
  .ci/vale/styles/PlainLanguage/SentenceLength.yml
  .ci/vale/styles/PlainLanguage/Slash.yml
  .ci/vale/styles/PlainLanguage/Wordiness.yml
  .ci/vale/styles/PlainLanguage/Words.yml
  .ci/vale/styles/vocab.txt
  .vale.ini
Labels: status/code-review

#1007 Setup Che in TLS mode with self-signed certificates
  src/main/images/contributor/che-tls-chrome-import_1.png
  src/main/images/contributor/che-tls-chrome-import_2.png
  src/main/images/contributor/che-tls-chrome-import_3.png
  src/main/images/contributor/che-tls-firefox-import_1.png
  src/main/images/contributor/che-tls-firefox-import_2.png
  src/main/images/contributor/che-tls-firefox-import_3.png
  src/main/images/contributor/che-tls-firefox-import_4.png
  src/main/pages/che-7/contributor-guide/assembly_setup-che-in-tls-mode-with-self-signed-certificate.adoc
  src/main/pages/che-7/contributor-guide/proc_che-usage-with-tls.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-kubernetes.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_deploy-che-with-self-signed-tls-on-openhift4-using-operator.adoc
  src/main/pages/che-7/contributor-guide/proc_gerenating-self-signed-certificates.adoc
Labels: kind/task, status/code-review

#1050 fix che-docs factory URL
  README.md
Labels: kind/bug, status/code-review

#1055 Update GitHub authentication flow
  src/main/pages/che-7/end-user-guide/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
Labels: kind/enhancement, status/code-review

#1047 Add release instruction
  RELEASE.md
Labels: kind/enhancement, status/code-review

#1059 Set new development version in master branch
  pom.xml
Labels: status/code-review

#1060 Update parent version
  pom.xml
Labels: kind/enhancement, status/code-review

#1058 Add newdoc, test-adoc.sh and vale to the che-docs container
  Dockerfile
  src/main/Gemfile.lock
Labels: kind/enhancement, status/code-review

#1061 fix a typo in Dockerfile
  Dockerfile
Labels: kind/bug, status/code-review

#1004 more details about prometheus-config.yaml
  src/main/pages/che-7/administration-guide/examples/grafana-dashboard-provider.yaml
  src/main/pages/che-7/administration-guide/examples/grafana-datasources.yaml
  src/main/pages/che-7/administration-guide/examples/prometheus-config.yaml
  src/main/pages/che-7/administration-guide/proc_collecting-che-metrics-with-prometheus.adoc
Labels: status/code-review
