Repository eclipse-che/che-docs, pull requests merged in 2021-01, with the labels that each got.

#1683 Support ideaIU and WebStorm
  modules/end-user-guide/images/jetbrains/activation-code.jpg
  modules/end-user-guide/images/jetbrains/jetbrains-account.jpg
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/pages/support-for-jetbrains-ides.adoc
  modules/end-user-guide/pages/using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/pages/using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/pages/using-jetbrains-webstorm.adoc
  modules/end-user-guide/partials/assembly_customizing-developer-environments.adoc
  modules/end-user-guide/partials/con_jetbrains-product-name-mapping.adoc
  modules/end-user-guide/partials/con_support-for-jetbrains-ides.adoc
  modules/end-user-guide/partials/proc_provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-webstorm.adoc
Labels: kind/docs, need-cherry-pick/7.20.x, status/code-review

#1774 Use the prod-id-short attribute for pages id
  antora-playbook.yml
  linkcheckerrc
  modules/administration-guide/partials/assembly_configuring-server-logging.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  modules/end-user-guide/partials/proc_logging-in-to-che-server-using-cli.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
Labels: status/code-review

#1775 Fix environment_docs_gen.sh
  VERSION
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#1776 Add upstream IBM rules
  .vale/styles/IBM/Abbreviations.yml
  .vale/styles/IBM/DashSpacing.yml
  .vale/styles/IBM/Definitions.yml
  .vale/styles/IBM/Ellipses.yml
  .vale/styles/IBM/Headings.yml
  .vale/styles/IBM/Latin.yml
  .vale/styles/IBM/OxfordComma.yml
  .vale/styles/IBM/SentenceLength.yml
  .vale/styles/IBM/Terms.yml
Labels: kind/enhancement, status/code-review

#1770 Small fixes to vale style specifications
  .vale/styles/CheDocs/Attributes.yml
  .vale/styles/IBM/Usage.yml
  devfile.yaml
  tools/test-adoc.sh
Labels: kind/bug, status/code-review

#1768 Make yeoman wizard article independent from Dashboard
  modules/contributor-guide/images/extensibility/adding-workspace.png
  modules/contributor-guide/images/extensibility/building-plug-in-using-yarn.png
  modules/contributor-guide/images/extensibility/choosing-che-7-dev-stack.png
  modules/contributor-guide/images/extensibility/launching-yeoman-wizard.png
  modules/contributor-guide/images/extensibility/open-terminal-in-container.png
  modules/contributor-guide/images/extensibility/yeoman-successful.png
  modules/contributor-guide/images/extensibility/yeoman-wizard-choosing-plug-in-name.png
  modules/contributor-guide/images/extensibility/yeoman-wizard-choosing-plug-in-sample.png
  modules/contributor-guide/images/extensibility/yeoman-wizard-choosing-plug-in-type.png
  modules/contributor-guide/images/extensibility/yeoman-wizard-launching.png
  modules/contributor-guide/images/extensibility/yeoman-wizard-logs.png
  modules/contributor-guide/images/extensibility/yeoman-wizard-plug-in-generated.png
  modules/contributor-guide/partials/proc_developing-che-theia-plug-ins-using-che.adoc
Labels: kind/task, status/code-review

#1778 Fix Deactivate http links
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#1781 Fixing IBM vale style Terms file that has been checked in twice
  .vale/styles/IBM/Terms.yml
  .vale/styles/IBM/terms.yml
Labels: kind/enhancement, status/code-review

#1783 Clarify devfile storage locations
  modules/end-user-guide/partials/con_what-is-a-devfile.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
Labels: kind/enhancement, need-cherry-pick/7.20.x, status/code-review

#1784 CRW-1226: Do not exclude the GH Pull-Requests chapter
  modules/end-user-guide/partials/assembly_version-control.adoc
Labels: kind/enhancement, status/code-review

#1785 Add xref
  modules/installation-guide/partials/assembly_advanced-configuration-options-for-the-che-server-component.adoc
Labels: kind/enhancement, status/code-review

#1782 Image Puller reorganization + image list
  antora-playbook.yml
  modules/administration-guide/examples/che-prepulled-images-table.adoc
  modules/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_parameters.adoc
  modules/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_prepare.adoc
  modules/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_process.adoc
  modules/administration-guide/examples/che-proc_deploying-image-puller-using-openshift-templates_verify-configmap.adoc
  modules/administration-guide/examples/image_puller/example_image_puller.yaml
  modules/administration-guide/examples/snip_che-cloning-image-puller-project.adoc
  modules/administration-guide/examples/snip_che-getting-the-list-of-relevant-images.adoc
  modules/administration-guide/examples/snip_che-images-incompatibles-with-image-puller.adoc
  modules/administration-guide/examples/snip_che-process-and-apply-image-puller-openshift-templates.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/pages/defining-the-list-of-images-to-pull.adoc
  modules/administration-guide/pages/defining-the-memory-parameters-for-the-image-puller.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-helm.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-the-operator.adoc
  modules/administration-guide/pages/installing-image-puller-on-openshift-using-openshift-templates.adoc
  modules/administration-guide/pages/installing-image-puller-on-openshift-using-operatorhub.adoc
  modules/administration-guide/partials/assembly_caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/partials/con_image-puller-overview.adoc
  modules/administration-guide/partials/proc_defining-the-list-of-images-to-pull.adoc
  modules/administration-guide/partials/proc_defining-the-memory-parameters-for-the-image-puller.adoc
  modules/administration-guide/partials/proc_deploying-image-puller-using-openshift-templates.adoc
  modules/administration-guide/partials/proc_deploying-image-puller-using-operator.adoc
  modules/administration-guide/partials/proc_installing-image-puller-on-kubernetes-using-the-operator.adoc
  modules/administration-guide/partials/proc_installing-image-puller-on-openshift-using-operatorhub.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-helm.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-openshift-templates.adoc
Labels: status/code-review

#1779 Mount secrets into eclipse-che containers
  modules/end-user-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
  modules/installation-guide/examples/che-ref_a-kubernetes-secret-as-a-file.adoc
  modules/installation-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/assembly_mounting-secrets-as-file-or-env-variable-in-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-as-a-file-into-a-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-as-an-environment-variable-into-a-container.adoc
Labels: kind/enhancement, status/code-review

#1789 Differentiate OpenShift 3 and 4 installations for Image Puller
  modules/administration-guide/pages/defining-the-list-of-images-to-pull.adoc
  modules/administration-guide/pages/defining-the-memory-parameters-for-the-image-puller.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-helm.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-the-operator.adoc
  modules/administration-guide/pages/installing-image-puller-on-openshift-using-openshift-templates.adoc
  modules/administration-guide/pages/installing-image-puller-on-openshift-using-operatorhub.adoc
  modules/administration-guide/partials/proc_installing-image-puller-on-openshift-using-operatorhub.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-openshift-templates.adoc
Labels: status/code-review

#1787 Bug fix
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-gradle-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-maven-projects.adoc
Labels: kind/bug, need-cherry-pick/7.20.x, status/code-review

#1791 Fixing examples in IG
  modules/installation-guide/examples/che-ref_a-kubernetes-secret-as-a-file.adoc
  modules/installation-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-as-a-file-into-a-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-as-an-environment-variable-into-a-container.adoc
Labels: kind/enhancement, status/code-review

#1790 Review linkchecker configuration.
  antora-playbook.yml
  linkcheckerrc
  modules/administration-guide/partials/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  modules/contributor-guide/partials/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  modules/contributor-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/partials/con_what-is-a-devfile.adoc
  modules/end-user-guide/partials/proc_configuring-openshift-oauth.adoc
  modules/end-user-guide/partials/proc_logging-the-java-language-server-protocol-lsp-messages.adoc
  modules/end-user-guide/partials/proc_troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-camel-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-omnisharp-theia-plug-in-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-xml-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-yaml-language-server.adoc
  modules/extensions/partials/assembly_eclipse-che4z.adoc
  modules/extensions/partials/assembly_telemetry-overview.adoc
  modules/installation-guide/examples/proc_che-configuring-che-to-run-in-a-restricted-environment.adoc
  modules/installation-guide/examples/proc_che-preparing-a-private-registry.adoc
Labels: status/code-review

#1773 Provision GitHub OAuth using secret
  modules/administration-guide/images/git/kc_provider.png
  modules/administration-guide/images/git/kc_roles.png
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/administration-guide/partials/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  modules/end-user-guide/images/git/github-keycloak-setup.png
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/configuring-github-oauth.adoc
  modules/end-user-guide/partials/assembly_configuring-oauth-authorization.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/partials/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
Labels: kind/enhancement, status/code-review

#1792 Fix GitHub plugin documentation
  modules/end-user-guide/images/git/github-sign-in-action.png
  modules/end-user-guide/images/git/github-sign-in-notification.png
  modules/end-user-guide/partials/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
Labels: kind/enhancement, status/code-review

#1788 Add Bitbucket authentication topic
  modules/administration-guide/examples/snip_bitbucket-personal-access-token-secret.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/authenticating-users-3rd-party-services.adoc
  modules/administration-guide/partials/assembly_authenticating-users-on-3rd-party-services.adoc
  modules/administration-guide/partials/assembly_managing-users.adoc
  modules/administration-guide/partials/proc_configuring_bitbucket_authentication.adoc
  modules/administration-guide/partials/proc_configuring_bitbucket_servers.adoc
Labels: kind/enhancement, status/code-review

#1794 Add a word to accept list + A tiny bugfix
  .vale/styles/Vocab/Che/accept.txt
  modules/administration-guide/partials/proc_defining-the-list-of-images-to-pull.adoc
Labels: kind/enhancement, status/code-review

#1793 Fix logo size following Antora theme change.
  supplemental-ui/css/extra.css
Labels: Che-7, kind/bug, kind/docs, sprint/next-sprint, status/code-review

#1797 [backport] Add Bitbucket authentication topic
  modules/administration-guide/examples/snip_bitbucket-personal-access-token-secret.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/authenticating-users-3rd-party-services.adoc
  modules/administration-guide/partials/assembly_authenticating-users-on-3rd-party-services.adoc
  modules/administration-guide/partials/assembly_managing-users.adoc
  modules/administration-guide/partials/proc_configuring_bitbucket_authentication.adoc
  modules/administration-guide/partials/proc_configuring_bitbucket_servers.adoc
Labels: status/code-review, target/branch

#1795 Resurrect the che-docs container
  .gitignore
  Dockerfile
  Jenkinsfile
  devfile.yaml
  package.json
  tools/podmanpreview.sh
  tools/preview.sh
  yarn.lock
Labels: status/code-review

#1786 Use certificates from /public-certs
  modules/end-user-guide/examples/che-go-use-self-signed-cert.adoc
  modules/end-user-guide/examples/che-python-use-self-signed-cert.adoc
  modules/end-user-guide/partials/proc_using-npm-artifact-repositories.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-go-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-gradle-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-maven-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-nuget-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-python-projects.adoc
Labels: kind/enhancement, status/code-review

#1798 Fix attribute, fix broken link, fix unterminated listing block
  modules/administration-guide/examples/snip_che-images-incompatibles-with-image-puller.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/partials/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  tools/podmanlinkchecker.sh
Labels: kind/bug, status/code-review

#1796 Use eclipse-che as default namespace
  antora-playbook.yml
  modules/administration-guide/partials/con_authentication-modes.adoc
  modules/administration-guide/partials/proc_verification-custom-registries.adoc
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
  modules/installation-guide/examples/proc_che-uninstalling-che-after-chectl-installation.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-the-che-operator-checluster-resource-with-kubectl.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  modules/installation-guide/partials/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
  modules/installation-guide/partials/proc_installing-cert-manager.adoc
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: status/code-review

#1799 Better description of kubernetes image puller installation platforms
  modules/administration-guide/partials/proc_installing-image-puller-on-openshift-using-operatorhub.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-openshift-templates.adoc
Labels: status/code-review

#1802 Create a GitHub actions workflow for release
  .github/workflows/release.yml
  make-release.sh
Labels: kind/task, status/code-review

#1805 Cleanup linkcheckerrc.
  linkcheckerrc
Labels: status/code-review

#1811 chore(linkchecker) Use of che-docs image to find linkchecker
  .github/workflows/link-checker.yaml
Labels: kind/task, status/code-review

#1801 Add a module on installing with chectl on OCP 4.
  .vale.ini
  .vale/styles/CheDocs/ReadabilityGrade.yml
  .vale/styles/Vocab/Che/accept.txt
  linkcheckerrc
  modules/installation-guide/examples/snip_installing-che-on-openshift-4-using-the-cli.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/installing-che-on-openshift-4-using-cli.adoc
  modules/installation-guide/pages/installing-che-on-openshift-4-using-operatorhub.adoc
  modules/installation-guide/partials/assembly_installing-che-in-cloud.adoc
  modules/installation-guide/partials/assembly_installing-che-on-openshift-4-using-operatorhub.adoc
  modules/installation-guide/partials/proc_installing-che-on-openshift-4-using-the-cli.adoc
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/enhancement, status/code-review

#1814 Update version to 7.24.2 for 7.24.x branch
  antora-playbook.yml
Labels: kind/enhancement, status/code-review, target/branch

#1815 Update version to 7.25.0 for master branch
  antora-playbook.yml
Labels: kind/enhancement, status/code-review

#1818 Remove Editing a devfile and plug-in at runtime
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/editing-a-devfile-and-plug-in-at-runtime.adoc
  modules/end-user-guide/partials/assembly_editing-a-devfile-and-plug-in-at-runtime.adoc
  modules/end-user-guide/partials/proc_adding-a-devfile-at-runtime.adoc
  modules/end-user-guide/partials/proc_adding-a-plug-in-at-runtime.adoc
Labels: status/code-review

#1804 Add configuration for htmltest
  .htmltest.yml
  tools/podmanhtmltest.sh
Labels: kind/enhancement, status/code-review

#1820 Add shellcheck plugin
  devfile.yaml
Labels: kind/task, status/code-review
