Repository eclipse-che/che-docs, pull requests merged in 2021-11, with the labels that each got.

#2148 Removig the warning about missing upstream devfile registry on the hosted che instance
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: status/code-review

#2154 fix: Fix outdated links
  antora.yml
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#2157 fix: removing a duplicate file with a name ending by a space.
  modules/administration-guide/partials/proc_managing-backups-using-chectl.adoc 
Labels: kind/bug, status/code-review, cherry-picked to 7.38.x

#2158 Fix xref.
  modules/administration-guide/pages/managing-backups-using-chectl.adoc
  modules/administration-guide/pages/managing-backups-using-chectl.adoc 
  modules/administration-guide/pages/managing-backups-using-cli.adoc
  modules/administration-guide/partials/proc_managing-backups-through-custom-resources.adoc
  modules/administration-guide/partials/proc_managing-backups-using-chectl.adoc
Labels: kind/bug, status/code-review, cherry-picked to 7.38.x

#2144 fix: Mounting secrets defined in a devfile
  modules/end-user-guide/partials/assembly_mounting-secrets-as-file-or-env-variable-in-workspace-container.adoc
Labels: kind/bug, status/code-review, need-cherry-pick/7.38.x

#2151 fix: vale errors and warnings
  .vale/styles/IBM/README-proselint.md
  .vale/styles/IBM/README-write-good.md
  .vale/styles/IBM/README.md
  CONTRIBUTING.adoc
  modules/administration-guide/partials/con_a-workspace-example.adoc
  modules/administration-guide/partials/con_define-backup-server-for-operator.adoc
  modules/administration-guide/partials/con_super-privileged-mode.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-with-external-PostgreSQL.adoc
  modules/administration-guide/partials/proc_configuring-gitlab-servers.adoc
  modules/administration-guide/partials/ref_grafana-dashboards-for-che.adoc
  modules/administration-guide/partials/ref_managesystem-permission.adoc
  modules/end-user-guide/partials/assembly_accessing-che-from-openshift-developer-perspective.adoc
  modules/end-user-guide/partials/proc_accessing-a-git-repository-via-ssh.adoc
  modules/end-user-guide/partials/proc_adding-the-vs-code-extension-using-the-workspace-configuration.adoc
  modules/end-user-guide/partials/proc_building-an-image-for-intellij-idea-community-or-pycharm-community.adoc
  modules/end-user-guide/partials/proc_troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-yaml-language-server.adoc
  modules/end-user-guide/partials/proc_viewing-netcoredebugoutput-plug-in-logs-in-the-output-panel.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
  modules/extensions/partials/proc_java-lombok.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_installing-dns-on-google-cloud-platform.adoc
  modules/installation-guide/partials/proc_using-kubespray-to-set-up-kubernetes.adoc
Labels: kind/bug, status/code-review, need-cherry-pick/7.38.x

#2162 fix: abort previous build on Jenkins
  Jenkinsfile
Labels: kind/bug, status/code-review

#2160 fix: Remove mentions of multiple instances of Che on one cluster
  modules/installation-guide/partials/assembly_installing-che.adoc
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: kind/bug, status/code-review

#2165 Pull request triage automation:
  .github/workflows/pull-request-assigned.yml
  .github/workflows/pull-request-opened.yml
Labels: status/code-review

#2147 fix: multiple workspaces compatibility list
  modules/installation-guide/partials/assembly_configuring-the-number-of-workspaces-that-a-user-can-run.adoc
  modules/installation-guide/partials/proc_using-configmap-to-configure-the-number-of-workspaces-that-a-user-can-run.adoc
  modules/installation-guide/partials/proc_using-the-operator-to-configure-the-number-of-workspaces-that-a-user-can-run.adoc
Labels: kind/bug, status/code-review, need-cherry-pick/7.38.x

#2150 chore: use a Vale Spelling rule instead of a Vocabulary
  .vale.ini
  .vale/fixtures/CheDocs/Spelling/.vale.ini
  .vale/fixtures/CheDocs/Spelling/testinvalid.adoc
  .vale/fixtures/CheDocs/Spelling/testvalid.adoc
  .vale/fixtures/CheDocs/TechnicalTerms/.vale.ini
  .vale/fixtures/CheDocs/TechnicalTerms/testinvalid.adoc
  .vale/fixtures/CheDocs/TechnicalTerms/testvalid.adoc
  .vale/styles/CheDocs/Spelling.yml
Labels: status/code-review

#2167 chore: add Web IDE link only at pull request creation
  .github/workflows/try-in-web-ide.yaml
Labels: kind/enhancement, status/code-review

#2168 fix: add missing . to docker build command
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
Labels: kind/bug, status/code-review

#2169 fix: prometheus config explanation formatting, broken link
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
Labels: kind/bug, status/code-review

#2171 chore: update Dockerfile
  Dockerfile
Labels: status/code-review

#2172 fix: erratic publication failures due to timeout.
  Jenkinsfile
Labels: kind/bug, status/code-review

#2170 procedures: Add new requirement for some objects to have part-of label
  modules/administration-guide/partials/proc_configuring-che-to-work-with-external-PostgreSQL.adoc
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
Labels: status/code-review

#2139 procedures: Add readiness init container docs
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/disabling-readiness-init-containers-for-the-olm-installer.adoc
  modules/administration-guide/pages/disabling-readiness-init-containers-for-the-operator-installer.adoc
  modules/administration-guide/pages/enabling-and-disabling-readiness-init-containers-for-the-olm-installer.adoc
  modules/administration-guide/pages/enabling-and-disabling-readiness-init-containers-for-the-operator-installer.adoc
  modules/administration-guide/pages/enabling-readiness-init-containers-for-the-olm-installer.adoc
  modules/administration-guide/pages/enabling-readiness-init-containers-for-the-operator-installer.adoc
  modules/administration-guide/pages/readiness-init-containers.adoc
  modules/administration-guide/partials/assembly_enabling-and-disabling-readiness-init-containers-for-the-olm-installer.adoc
  modules/administration-guide/partials/assembly_enabling-and-disabling-readiness-init-containers-for-the-operator-installer.adoc
  modules/administration-guide/partials/assembly_readiness-init-containers.adoc
  modules/administration-guide/partials/proc_disabling-readiness-init-containers-for-the-olm-installer.adoc
  modules/administration-guide/partials/proc_disabling-readiness-init-containers-for-the-operator-installer.adoc
  modules/administration-guide/partials/proc_enabling-readiness-init-containers-for-the-olm-installer.adoc
  modules/administration-guide/partials/proc_enabling-readiness-init-containers-for-the-operator-installer.adoc
Labels: kind/enhancement, status/code-review
