Repository eclipse-che/che-docs, pull requests merged in 2021-08, with the labels that each got.

#2073 fix: update image puller docs and csv link
  modules/administration-guide/examples/snip_che-getting-the-list-of-relevant-images.adoc
  modules/administration-guide/examples/snip_che-list-of-images-for-faster-workspace-start.adoc
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/partials/proc_defining-the-list-of-images-to-pull.adoc
Labels: kind/bug, need-cherry-pick/7.32.x, status/code-review

#2077 fix: Use semantic commit message for the release
  make-release.sh
Labels: kind/bug, status/code-review

#2079 fix: Use new URL for downloading and parsing CRD
  tools/checluster_docs_gen.sh
Labels: kind/bug

#2081 fix: Updating Hosted Che 'Troubleshooting' section. Adding a warning about currently disabled upstream devfile registry
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: kind/enhancement

#2067 fix: metadata consistency
  modules/installation-guide/partials/assembly_mounting-secrets-or-a-configmap-as-file-or-env-variable-in-container.adoc
Labels: kind/bug, status/code-review

#2062 fix: removing references to (previous) versions of Che in two .adoc files
  modules/end-user-guide/examples/che-ref_a-kubernetes-secret-as-a-file.adoc
  modules/end-user-guide/examples/che-ref_a-kubernetes-secret-as-an-variable.adoc
Labels: kind/bug, kind/enhancement, status/code-review, need-cherry-pick/7.32.x

#2072 Add Backup / Restore docs
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-cli-to-use-backup-server.adoc
  modules/administration-guide/pages/define-backup-server-for-operator.adoc
  modules/administration-guide/pages/managing-backups-using-cli.adoc
  modules/administration-guide/pages/managing-backups-using-custom-resources.adoc
  modules/administration-guide/pages/setup-backup-server.adoc
  modules/administration-guide/partials/assembly_backup-and-disaster-recovery.adoc
  modules/administration-guide/partials/con_define-backup-server-for-operator.adoc
  modules/administration-guide/partials/con_setup-backup-server.adoc
  modules/administration-guide/partials/proc_configuring-cli-to-use-backup-server.adoc
  modules/administration-guide/partials/proc_managing-backups-through-cli.adoc
  modules/administration-guide/partials/proc_managing-backups-through-custom-resources.adoc
  modules/administration-guide/partials/snip_internal-backup-server-warning.adoc
Labels: kind/task, status/code-review

#2086 fix: clarified that a parameter is optional
  modules/administration-guide/partials/proc_building-a-custom-devfile-registry-image.adoc
Labels: kind/enhancement, kind/docs

#2085 chore: set minimal kubernetes version to 1.19
  antora-playbook.yml
  modules/installation-guide/examples/ref_che-supported-platforms-and-installation-methods.adoc
  modules/installation-guide/partials/proc_installing-che-on-docker-desktop-using-helm.adoc
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
  modules/installation-guide/partials/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: kind/enhancement

#2089 chore: Mark helmcharts deprecated
  modules/installation-guide/examples/ref_che-supported-platforms-and-installation-methods.adoc
Labels: kind/enhancement, kind/docs

#2078 Fix vale warnings in End-user Guide
  modules/end-user-guide/partials/assembly_che-theia-troubleshooting.adoc
  modules/end-user-guide/partials/assembly_using-artifact-repositories-in-a-restricted-environment.adoc
  modules/end-user-guide/partials/assembly_using-gradle-artifact-repositories.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-concept-in-detail.adoc
  modules/end-user-guide/partials/proc_accessing-a-git-repository-via-ssh.adoc
  modules/end-user-guide/partials/proc_adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
  modules/end-user-guide/partials/proc_defining-maven-repositories-in-the-settings-xml-file.adoc
  modules/end-user-guide/partials/proc_downloading-different-versions-of-gradle.adoc
  modules/end-user-guide/partials/proc_managing-git-configuration-identity.adoc
  modules/end-user-guide/partials/proc_overriding-devfile-values-using-factory-parameters.adoc
  modules/end-user-guide/partials/proc_troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/partials/proc_using-npm-artifact-repositories.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: kind/enhancement, kind/docs, need-cherry-pick/7.34.x, need-cherry-pick/7.32.x

#2087 Install on azure
  modules/installation-guide/partials/proc_configuring-dns-on-azure.adoc
  modules/installation-guide/partials/proc_installing-cert-manager.adoc
Labels: kind/enhancement, kind/docs

#2075 Fix vale warnings
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/assembly_understanding-che-workspace-controller.adoc
  modules/administration-guide/partials/assembly_understanding-che-workspaces-architecture.adoc
  modules/administration-guide/partials/con_che-system-permissions.adoc
  modules/administration-guide/partials/con_che-workspaces-architecture.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-without-identity-provider.adoc
  modules/administration-guide/partials/proc_configuring-external-PostgreSQL.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-without-initial-user.adoc
  modules/administration-guide/partials/proc_removing-user-data.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/contributor-guide/partials/assembly_che-extensibility-reference.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
  modules/glossary/partials/con_glossary.adoc
  modules/hosted-che/partials/proc_registering-to-hosted-che.adoc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-ingresses.adoc
  modules/installation-guide/partials/proc_installing-che-on-kind-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubernetes_using_chectl_and_helm.adoc
  modules/installation-guide/partials/proc_manually-upgrading-che-in-operatorhub.adoc
  modules/installation-guide/partials/proc_sizing-google-cloud-node-pools-for-your-eclipse-che-workspaces.adoc
  modules/installation-guide/partials/proc_specifying-the-approval-strategy-of-che-in-operatorhub.adoc
  modules/installation-guide/partials/proc_using-kubespray-to-set-up-kubernetes.adoc
Labels: kind/bug, kind/enhancement, status/code-review

#2094 fix: capitalization
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/end-user-guide/examples/che-ref_annotations-description.adoc
  modules/end-user-guide/examples/che-ref_git-credential-file-as-kubernetes-secret-into-the-file.adoc
  modules/end-user-guide/partials/con_what-is-a-devfile.adoc
  modules/end-user-guide/partials/proc_adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
  modules/end-user-guide/partials/proc_logging-the-java-language-server-protocol-lsp-messages.adoc
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/proc_building-an-offline-plug-in-registry-image.adoc
Labels: kind/bug, status/code-review

#2051 Fix: references to the 'Get Started' UI label
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/authoring-devfiles-version-2.adoc
  modules/end-user-guide/pages/creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
  modules/end-user-guide/pages/creating-a-workspace-from-a-code-sample.adoc
  modules/end-user-guide/pages/creating-a-workspace-from-a-template-devfile.adoc
  modules/end-user-guide/pages/creating-a-workspace-from-code-sample.adoc
  modules/end-user-guide/pages/importing-the-source-code-of-a-project-into-a-workspace.adoc
  modules/end-user-guide/partials/assembly_authoring-devfiles-version-2.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-a-code-sample.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-a-template-devfile.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-code-sample.adoc
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_changing-the-configuration-of-an-existing-workspace.adoc
  modules/end-user-guide/partials/proc_creating-a-custom-workspace-from-a-template.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
  modules/end-user-guide/partials/proc_importing-the-source-code-of-a-project-into-a-workspace.adoc
  modules/end-user-guide/partials/proc_using-a-badge-to-link-to-workspaces.adoc
  modules/installation-guide/partials/assembly_installing-che-locally.adoc
  modules/installation-guide/partials/assembly_upgrading-che-namespace-strategies-other-than-per-user.adoc
Labels: kind/bug, status/code-review, team/che-qe, need-cherry-pick/7.30.x

#2092 Create try-pr-on-eclipse-che-hosted-by-red-hat.yaml
  .github/workflows/try-pr-on-eclipse-che-hosted-by-red-hat.yaml
Labels: kind/task, status/code-review

#2095 fix: remove dash in 'multi-...' terms according to IBM Style Guide
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
  modules/administration-guide/partials/con_che-keycloak.adoc
  modules/administration-guide/partials/con_che-postgresql.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_che-workspace-controller.adoc
  modules/administration-guide/partials/con_che-workspace-jwt-proxy.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/pages/differences-in-how-che-theia-webview-works-on-a-single-host-mode-comparing-to-a-multi-host-mode.adoc
  modules/end-user-guide/partials/assembly_differences-in-how-che-theia-webview-works-on-a-single-host-mode-comparing-to-a-multi-host-mode.adoc
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/assembly_installing-che.adoc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspaces-nodeselector.adoc
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
  tools/environment_docs_gen.sh
  tools/test-adoc.sh
Labels: kind/bug, kind/enhancement, status/code-review, need-cherry-pick/7.34.x, need-cherry-pick/7.32.x

#2093 [1784] fix: Unify use of [...] in YAML and other files in Che docs
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-maven-projects.adoc
  modules/installation-guide/examples/proc_che-configuring-che-to-run-in-a-restricted-environment.adoc
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
  modules/installation-guide/partials/proc_using-the-operator-to-configure-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/installation-guide/partials/proc_using-the-operator-to-configure-the-number-of-workspaces-that-a-user-can-run.adoc
Labels: kind/bug, status/code-review

#2043 chore: update pull request template, add code review checklist
  .github/PULL_REQUEST_TEMPLATE.md
  .vale.ini
  .vale/styles/Vocab/Che/accept.txt
  CONTRIBUTING.adoc
  code_review_checklist.adoc
Labels: status/code-review

#2099 chore: Add recommended extensions in devfile
  devfile.yaml
Labels: status/code-review

#2098 fix: Remove reference to the removed share button
  modules/administration-guide/partials/assembly_authorizing-users.adoc
  modules/administration-guide/partials/proc_sharing-che-permissions.adoc
Labels: kind/bug, status/code-review, need-cherry-pick/7.34.x

#2105 fix: devfile URL changed
  modules/end-user-guide/partials/assembly_authoring-devfiles-version-2.adoc
Labels: kind/bug, status/code-review
