Repository eclipse-che/che-docs, pull requests merged in 2021-12, with the labels that each got.

#2175 fix: Follow latest devfile 2 specification
  modules/end-user-guide/partials/assembly_authoring-devfiles-version-2.adoc
Labels: kind/bug, status/code-review

#2179 fix: Example value of CHE_WORKSPACE_POD_TOLERATIONS__JSON to double-q…
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#2146 docs: storage strategies concept update
  modules/installation-guide/examples/che-pvc-strategies.adoc
  modules/installation-guide/partials/con_persistent-volume-configuration.adoc
Labels: kind/bug, status/code-review

#2180 fix: add thematic break to the Che server parameters reference
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#2176 fix and update the Contributing page
  CONTRIBUTING.adoc
  modules/administration-guide/images/architecture/crw-architecture-with-che-server-engine.png
  modules/administration-guide/images/architecture/crw-architecture-with-che-server-operator.png
  modules/administration-guide/images/architecture/crw-dashboard-interactions.png
  modules/administration-guide/images/architecture/crw-deployments-interacting-with-devworkspace.png
  modules/administration-guide/images/architecture/crw-devfile-registry-interactions.png
  modules/administration-guide/images/architecture/crw-gateway-interactions.png
  modules/administration-guide/images/architecture/crw-interacting-with-devworkspace.png
  modules/administration-guide/images/architecture/crw-plugin-registry-interactions.png
  modules/administration-guide/images/architecture/crw-postgresql-interactions.png
  modules/administration-guide/images/architecture/crw-server-interactions.png
  modules/administration-guide/images/architecture/crw-user-dashboard-interactions.png
  modules/administration-guide/images/architecture/crw-user-workspaces-interactions.png
  modules/administration-guide/images/architecture/crw-user_workspace.png
  templates/examples/snip_che_title.adoc
  templates/partials/snippet.adoc
Labels: kind/bug, status/code-review, target/branch

#2177 procedures: Setting Authorization callback URL in GitHub OAuth app to Che OAuth callback URL
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
Labels: status/code-review

#2190 chore: delete Jenkinsfile
  Jenkinsfile
Labels: status/code-review

#2191 chore: 7.40.x new publication
  .htmltest.yml
  antora-playbook-for-development.yml
  antora.yml
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
  supplemental-ui/partials/article-404.hbs
  supplemental-ui/partials/header-content.hbs
Labels: status/code-review, target/branch

#2185 fix: broken link
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
Labels: kind/bug, status/code-review

#2186 fix: typo
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review, cherry-picked to 7.40.x

#2184 fix: Add [hH]ostname
  .vale/styles/CheDocs/Spelling.yml
Labels: kind/enhancement, status/code-review

#2161 procedures: Dev Workspace monitoring documentation
  modules/administration-guide/images/monitoring/monitoring-dev-workspace-metrics-panel.png
  modules/administration-guide/images/monitoring/monitoring-dev-workspace-operator-metrics-panel-1.png
  modules/administration-guide/images/monitoring/monitoring-dev-workspace-operator-metrics-panel-2.png
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/monitoring-the-dev-workspace-operator.adoc
  modules/administration-guide/partials/assembly_monitoring-the-dev-workspace-operator.adoc
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_collecting-dev-workspace-operator-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_viewing-dev-workspace-operator-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/partials/ref_devworkspace-specific-metrics.adoc
  modules/administration-guide/partials/ref_grafana-dashboards-for-the-dev-workspace-operator.adoc
Labels: status/code-review

#2189 fix: Fix attribute in Uninstalling Che
  modules/installation-guide/partials/proc_uninstalling-che-after-operatorhub-installation-using-openshift-cli.adoc
  modules/installation-guide/partials/proc_uninstalling-che-after-operatorhub-installation-using-openshift-web-console.adoc
Labels: kind/bug, status/code-review, need-cherry-pick/7.40.x

#2193 chore: prepare master branch for multiversioned publication
  .htmltest.yml
  antora-playbook-for-development.yml
  antora-playbook-for-publication.yml
  antora-playbook-unbranded.yml
  antora.yml
  devfile.yaml
  tools/build-for-publication.sh
  tools/push-to-eclipse-repository.sh
  tools/runnerpublication.sh
Labels: status/code-review

#2188 chore: delete obsolete and unused vale vocabulary
  .vale.ini
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
Labels: status/code-review

#2194 chore: speed up build on pulls
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
Labels: status/code-review

#2182 fix: architecture overview xref statements
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/architecture-overview-with-che-server.adoc
  modules/administration-guide/pages/architecture-overview-with-devworkspace.adoc
  modules/administration-guide/pages/architecture-overview.adoc
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
Labels: kind/bug, status/code-review, cherry-picked to 7.38.x, cherry-picked to 7.39.x, cherry-picked to 7.40.x

#2197 chore: Adding Call publication builder workflow
  .github/workflows/call-publication-builder.yaml
Labels: status/code-review, cherry-picked to 7.40.x

#2201 chore: URLs changes
  modules/end-user-guide/partials/proc_verifying-the-vs-code-extension-api-compatibility-level.adoc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
  supplemental-ui/partials/header-content.hbs
Labels: status/code-review

#2136 procedures: Configuring the CheCluster Custom Resource
  .vale.ini
  .vale/fixtures/CheDocs/ConfigMap/.vale.ini
  .vale/fixtures/CheDocs/ConfigMap/testinvalid.adoc
  .vale/fixtures/CheDocs/ConfigMap/testvalid.adoc
  .vale/styles/CheDocs/ConfigMap.yml
  .vale/styles/CheDocs/TechnicalTerms.yml
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/creating-an-instance-of-the-che-operator.adoc
  modules/installation-guide/pages/using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/installation-guide/pages/using-the-cli-to-configure-the-checluster-custom-resource.adoc
  modules/installation-guide/pages/using-the-openshift-web-console-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/installation-guide/pages/using-the-openshift-web-console-to-configure-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/assembly_configuring-the-che-installation.adoc
  modules/installation-guide/partials/con_understanding-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/proc_creating-an-instance-of-the-che-operator.adoc
  modules/installation-guide/partials/proc_using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/installation-guide/partials/proc_using-the-cli-to-configure-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/proc_using-the-openshift-web-console-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/installation-guide/partials/proc_using-the-openshift-web-console-to-configure-the-checluster-custom-resource.adoc
Labels: status/code-review

#2187 procedures: native user auth docs
  .vale/styles/CheDocs/Spelling.yml
  antora.yml
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-minikube-github-authentication.adoc
  modules/administration-guide/pages/configuring-openshift-oauth.adoc
  modules/administration-guide/pages/managing-identities-and-authorizations.adoc
  modules/administration-guide/partials/assembly_authorizing-users.adoc
  modules/administration-guide/partials/assembly_managing-identities-and-authorizations.adoc
  modules/administration-guide/partials/con_che-operator.adoc
  modules/administration-guide/partials/con_gateway.adoc
  modules/administration-guide/partials/proc_configuring-minikube-github-authentication.adoc
  modules/installation-guide/partials/proc_enabling-dev-workspace-operator.adoc
Labels: status/code-review
