Repository eclipse-che/che-docs, pull requests merged in 2021-02, with the labels that each got.

#1822 che-docs container update
  Dockerfile
Labels: status/code-review

#1821 Add references to minimalism. Update links. Remove fluff.
  CONTRIBUTING.adoc
Labels: kind/enhancement, status/code-review

#1823 Remove VERSION file in che-docs; keep antora-playbook.yml up to date instead #18864
  VERSION
  make-release.sh
Labels: kind/task, status/code-review

#1833 Troubleshooting network problems: use a more reliable URL, compliance.
  .github/workflows/vale-on-pr.yaml
  .github/workflows/vale-on-push.yaml
  .github/workflows/vale.yaml
  modules/end-user-guide/partials/proc_troubleshooting-network-problems.adoc
Labels: status/code-review

#1834 Run build-pr-docs and link-checker in che-docs container
  .github/workflows/build-pr-docs.yaml
  .github/workflows/link-checker.yaml
Labels: status/code-review

#1835 Fix vale-on-pr.yaml: add a proper filter
  .github/workflows/vale-on-pr.yaml
Labels: kind/bug, status/code-review

#1836 gh18864 fix name of action; remove need to...
  .github/workflows/release.yml
  make-release.sh
Labels: kind/task, status/code-review

#1838 Remove redundant +
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: status/code-review

#1841 Update bitbucket related documentation with known issues and process workarounds
  modules/administration-guide/partials/proc_configuring_bitbucket_authentication.adoc
  package-lock.json
Labels: kind/enhancement, need-cherry-pick/7.24.x, status/code-review

#1844 Delete obsolete file
  package-lock.json
Labels: status/code-review

#1831 Fix dead links to Zowe CLI Plug-ins
  modules/extensions/partials/assembly_eclipse-che4z.adoc
Labels: kind/bug, status/code-review

#1845 Fix broken link. URL has changed.
  modules/installation-guide/partials/proc_installing-che-on-openshift-4-using-the-cli.adoc
Labels: kind/bug, status/code-review

#1846 Use the linkchecker configuration in GitHub action
  .github/workflows/link-checker.yaml
Labels: status/code-review

#1817 Expand upgrading Che chapter.
  .vale/styles/Vocab/Che/reject.txt
  modules/installation-guide/images/installation/specifying-upgrade-strategy.png
  modules/installation-guide/pages/upgrading-che-using-operatorhub.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-operatorhub.adoc
  modules/installation-guide/partials/proc_manually-upgrading-che-in-operatorhub.adoc
  modules/installation-guide/partials/proc_specifying-the-approval-strategy-of-che-in-operatorhub.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-operatorhub.adoc
Labels: status/code-review

#1807 Obtain and persist Bitbucket personal access token as k8s secret
  .vale.ini
  .vale/styles/CheDocs/CommonTerms.yml
  .vale/styles/Vocab/Che/accept.txt
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/authenticating-users-3rd-party-services.adoc
  modules/administration-guide/pages/configuring-openshift-oauth.adoc
  modules/administration-guide/pages/managing-identities-and-authorizations.adoc
  modules/administration-guide/pages/managing-users.adoc
  modules/administration-guide/partials/assembly_authenticating-users-on-3rd-party-services.adoc
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/assembly_managing-identities-and-authorizations.adoc
  modules/administration-guide/partials/assembly_managing-users.adoc
  modules/administration-guide/partials/proc_configuring-bitbucket-server-oauth1.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth.adoc
  modules/end-user-guide/examples/snip_bitbucket-personal-access-token-secret.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/authentication-against-bitbucket-server-with-the-personal-access-token.adoc
  modules/end-user-guide/pages/configuring-oauth-authorization.adoc
  modules/end-user-guide/partials/assembly_configuring-oauth-authorization.adoc
  modules/end-user-guide/partials/proc_configuring_bitbucket_authentication.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
Labels: kind/task, status/code-review

#1819 Add self-registration module.
  .vale/styles/Vocab/Che/reject.txt
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/proc_enabling-self-registration.adoc
  modules/end-user-guide/partials/proc_logging-in-to-che-on-openshift-for-the-first-time-registering-as-a-new-user.adoc
Labels: kind/enhancement, status/code-review

#1816 feat(plugin-registry): Handle new changes in plugin registry
  modules/installation-guide/examples/snip_che-build-a-registry.adoc
  modules/installation-guide/partials/proc_building-a-registry-image.adoc
Labels: status/code-review

#1842 Release fix
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review

#1847 loggin-into-identity-provider+location
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_logging-in-to-identity-provider.adoc
  modules/installation-guide/partials/proc_setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
Labels: status/code-review

#1850 downstreaming fixes
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
Labels: kind/bug, status/code-review

#1843 Language and minimalism authenticating-with-openshift-connector-from-che
  .vale.ini
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
Labels: status/code-review

#1803 Generate checluster references tables
  Jenkinsfile
  devfile.yaml
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/partials/ref_checluster-custom-resource-fields-reference.adoc
  tools/checluster_docs_gen.sh
Labels: kind/docs, kind/enhancement, status/code-review

#1853 Downstreamfix mm 2 includes
  .vale/styles/Vocab/Che/accept.txt
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_logging-in-to-identity-provider.adoc
Labels: kind/bug, status/code-review

#1855 fix
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
Labels: kind/bug, status/code-review

#1852 Update Vale rules.
  .vale/styles/IBM/Terms.yml
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
Labels: kind/enhancement, status/code-review

#1851 Update configure OpenShift OAuth
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-without-initial-user.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth.adoc
  modules/administration-guide/partials/proc_removing-initial-openshift-user.adoc
Labels: kind/docs, kind/enhancement, status/code-review

#1857 Merged PR fixes
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth.adoc
Labels: kind/bug, status/code-review

#1856 Adding a warning about EOL of Eclipse Che hosted by Red Hat
  modules/hosted-che/partials/assembly_hosted-che.adoc
Labels: kind/enhancement, status/code-review

#1858 Improving the Hosted Che EOL warning
  modules/hosted-che/partials/assembly_hosted-che.adoc
Labels: status/code-review

#1859 Updates proc to configure github/bitbucket oauth
  modules/administration-guide/partials/proc_configuring-bitbucket-server-oauth1.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/administration-guide/partials/proc_enabling-self-registration.adoc
Labels: kind/task, status/code-review

#1861 Fix self-signed certificates usage in Maven projects
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-maven-projects.adoc
Labels: kind/bug, status/code-review

#1862 Update vale plugin ID
  devfile.yaml
Labels: kind/enhancement, status/code-review

#1864 Fix release script and documentation
  RELEASE.md
  make-release.sh
Labels: kind/bug, status/code-review

#1868 New URL for olm-what-operators-are.html
  modules/installation-guide/partials/con_understanding-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: status/code-review
