Repository eclipse-che/che-docs, pull requests merged in 2021-04, with the labels that each got.

#1941 Fix vale rules in administration guide
  .vale/styles/Vocab/Che/accept.txt
  antora-playbook.yml
  modules/administration-guide/examples/prometheus-config.adoc
  modules/administration-guide/examples/snip_che-cloning-image-puller-project.adoc
  modules/administration-guide/examples/snip_che-cluster-deployment-openshift-logs.adoc
  modules/administration-guide/examples/snip_che-devfile-meta.adoc
  modules/administration-guide/examples/snip_che-plug-in-tree.adoc
  modules/administration-guide/partials/assembly_tracing-che.adoc
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/partials/con_che-user-runtimes.adoc
  modules/administration-guide/partials/con_che-workspaces-architecture.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/proc_building-a-custom-devfile-registry-image.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_configuring_bitbucket_servers.adoc
  modules/administration-guide/partials/proc_installing-image-puller-on-kubernetes-using-the-image-puller-operator.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-helm.adoc
  modules/administration-guide/partials/proc_viewing-che-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/partials/proc_viewing-che-traces-in-jaeger-ui.adoc
  modules/administration-guide/partials/proc_viewing-keycloak-server-logs.adoc
  modules/administration-guide/partials/proc_viewing-postgresql-server-logs.adoc
  modules/administration-guide/partials/proc_viewing-the-state-of-the-che-cluster-deployment-using-openshift-4-cli-tools.adoc
  modules/administration-guide/partials/prometheus-config.adoc
  modules/administration-guide/partials/ref_grafana-dashboards-for-che.adoc
Labels: kind/bug, status/code-review

#1940 RHDEVDOCS-2804 Removing the low level details from the image puller landing page
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
Labels: status/code-review

#1942 Fix vale rules in installation guide
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
  antora-playbook.yml
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/ref_che-supported-platforms-and-installation-methods.adoc
  modules/installation-guide/pages/configuring-labels-for-ingresses.adoc
  modules/installation-guide/partials/con_persistent-volume-configuration.adoc
  modules/installation-guide/partials/con_security-considerations.adoc
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
  modules/installation-guide/partials/con_workspace-exposure-strategies.adoc
  modules/installation-guide/partials/proc_configuring-dns-on-azure.adoc
  modules/installation-guide/partials/proc_configuring-labels-for-ingresses.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-storage-types.adoc
  modules/installation-guide/partials/proc_configuring-the-che-operator-checluster-resource-with-kubectl.adoc
  modules/installation-guide/partials/proc_creating-a-google-kubernetes-engine-instance.adoc
  modules/installation-guide/partials/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  modules/installation-guide/partials/proc_enabling-dev-workspace-engine.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_installing-cert-manager-on-kubernetes.adoc
  modules/installation-guide/partials/proc_installing-che-on-kind-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-dns-on-google-cloud-platform.adoc
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
  modules/installation-guide/partials/proc_setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
  modules/installation-guide/partials/proc_sizing-google-cloud-node-pools-for-your-eclipse-che-workspaces.adoc
  modules/installation-guide/partials/proc_using-kubespray-to-set-up-kubernetes.adoc
  modules/installation-guide/partials/proc_using-minishift-to-set-up-openshift-3.adoc
Labels: kind/bug, status/code-review

#1945 Fix default value in `useInternalClusterSVCNames` property
  modules/installation-guide/examples/checluster-properties.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1936 Deprecate namespace strategies other than 'per user'
  .vale/styles/Vocab/Che/accept.txt
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/upgrading-che-namespace-strategies-other-than-per-user.adoc
  modules/installation-guide/partials/assembly_upgrading-che-namespace-strategies-other-than-per-user.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_upgrading-che-and-backing-up-user-data.adoc
  modules/installation-guide/partials/proc_upgrading-che-and-losing-user-data.adoc
Labels: kind/task, status/code-review

#1917 Document upstream plugin registry changes
  modules/administration-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/administration-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/administration-guide/examples/snip_che-plugin-registry-build-output.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/contributor-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/adding-a-vs-code-extension-to-a-workspace.adoc
  modules/end-user-guide/pages/adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
  modules/end-user-guide/partials/proc_adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
  modules/end-user-guide/partials/proc_publishing-metadata-for-a-vs-code-extension.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
  modules/installation-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  package.json
Labels: status/code-review

#1944 Refresh system-variables.adoc and skip vale checks on it
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: status/code-review

#1937 Putting examples in boxes, adding missing verification steps
  modules/end-user-guide/partials/proc_allowing-users-to-define-workspace-deployment-labels-and-annotations.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  modules/end-user-guide/partials/proc_overriding-devfile-values-using-factory-parameters.adoc
Labels: kind/enhancement, need-cherry-pick/7.26.x, status/code-review

#1943 Report breakdown of vale errors per module
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .vale.ini
  tools/count_vale_errors.sh
  tools/validate_language_changes.sh
Labels: status/code-review

#1950 Fix language on hosted che
  modules/hosted-che/partials/proc_creating-a-workspace-from-template-in-hosted-che.adoc
  modules/hosted-che/partials/proc_creating-a-workspace-from-the-user-dashboard.adoc
  modules/hosted-che/partials/proc_registering-to-hosted-che.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: kind/bug, status/code-review

#1948 IntelliJ in an exiting workspace
  .vale/styles/Vocab/Che/accept.txt
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/configuring-an-existing-workspace-to-use-intellij-idea.adoc
  modules/end-user-guide/partials/proc_configuring-an-existing-workspace-to-use-intellij-idea.adoc
Labels: status/code-review

#1949 Fix language errors in extensions
  .vale/styles/Vocab/Che/accept.txt
  modules/extensions/partials/assembly_openshift-connector-overview.adoc
  modules/extensions/partials/con_features-of-openshift-connector.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
  modules/extensions/partials/proc_creating-components-with-openshift-connector-in-che.adoc
  modules/extensions/partials/proc_installing-openshift-connector-in-che.adoc
  modules/extensions/partials/ref_the-woopra-telemetry-plugin.adoc
Labels: kind/bug, status/code-review

#1951 Fix language on contributor guide
  .vale/styles/Vocab/Che/accept.txt
  modules/contributor-guide/partials/assembly_testing-che-theia-plug-ins.adoc
  modules/contributor-guide/partials/con_che-extension-points.adoc
  modules/contributor-guide/partials/proc_adding-support-for-a-new-debugger.adoc
  modules/contributor-guide/partials/proc_bootstrapping-che-theia-plug-in-development-with-yeoman.adoc
  modules/contributor-guide/partials/proc_defining-custom-branding-values-for-che-theia.adoc
  modules/contributor-guide/partials/ref_che-theia-plug-in-api.adoc
Labels: kind/bug, status/code-review

#1953 Changes in vale configuration to parse che.properties
  .vale.ini
Labels: kind/enhancement, status/code-review

#1955 Fix small formatting issues
  modules/administration-guide/partials/proc_removing-user-data.adoc
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-using-the-operator.adoc
Labels: status/code-review

#1954 Language review and Vale rules update
  .htmltest.yml
  .vale.ini
  .vale/fixtures/CheDocs/Attributes/.vale.ini
  .vale/fixtures/CheDocs/Attributes/invalid.testadoc
  .vale/fixtures/CheDocs/Attributes/test.adoc
  .vale/fixtures/CheDocs/Attributes/valid.testadoc
  .vale/styles/CheDocs/Attributes.yml
  .vale/styles/CheDocs/CommonTerms.yml
  .vale/styles/CheDocs/TechnicalTerms.yml
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
  antora-playbook.yml
  modules/administration-guide/partials/con_che-workspaces-architecture.adoc
  modules/administration-guide/partials/proc_configuring-bitbucket-server-oauth1.adoc
  modules/administration-guide/partials/proc_configuring-che-to-use-external-identity-provider.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
  modules/administration-guide/partials/ref_grafana-dashboards-for-che.adoc
  modules/contributor-guide/partials/ref_che-theia-plug-in-api.adoc
  modules/end-user-guide/examples/snip_gitlab-personal-access-token-secret.adoc
  modules/end-user-guide/partials/assembly_using-go-artifact-repositories.adoc
  modules/end-user-guide/partials/assembly_viewing-logs-for-dotnet-with-netcoredebugoutput-plug-in.adoc
  modules/end-user-guide/partials/assembly_viewing-logs-for-dotnet-with-omnisharp-theia-plug-in.adoc
  modules/end-user-guide/partials/proc_allowing-users-to-define-workspace-deployment-labels-and-annotations.adoc
  modules/end-user-guide/partials/proc_changing-the-configuration-of-an-existing-workspace.adoc
  modules/end-user-guide/partials/proc_configuring_bitbucket_authentication.adoc
  modules/end-user-guide/partials/proc_configuring_gitlab_authentication.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/partials/proc_using-npm-artifact-repositories.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-go-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-gradle-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-maven-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-nuget-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-python-projects.adoc
  modules/end-user-guide/partials/ref_netcoredebugoutput-plug-in.adoc
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/partials/assembly_configuring-che-on-google-cloud-platform.adoc
  modules/installation-guide/partials/assembly_upgrading-che-namespace-strategies-other-than-per-user.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
  modules/installation-guide/partials/proc_preparing-the-aws-system-for-installing-che.adoc
  modules/installation-guide/partials/proc_sizing-google-cloud-node-pools-for-your-eclipse-che-workspaces.adoc
  modules/installation-guide/partials/proc_upgrading-che-and-losing-user-data.adoc
Labels: status/code-review

#1957 Add IMAGE_PULL_SECRETS to image puller parameters
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
Labels: kind/enhancement, status/code-review

#1960 Fix URL to kubectl docsfix.
  modules/installation-guide/partials/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: kind/bug, status/code-review

#1959 Add AFFINITY to image puller parameters
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
Labels: kind/enhancement, status/code-review

#1961 Make checluster_docs_gen.sh script compatible with CRD v1
  tools/checluster_docs_gen.sh
Labels: kind/task, status/code-review

#1963 Fix broken link
  modules/installation-guide/partials/proc_installing-che-on-docker-desktop-using-helm.adoc
Labels: kind/bug, status/code-review

#1964 Update doc to mention that OpenShift initial user credentials are stored into openshift-config namespace
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
Labels: kind/task, status/code-review

#1968 Eclipse Che hosted by Red Hat: Updating the IDE link to the developer-sandbox
  modules/hosted-che/partials/proc_registering-to-hosted-che.adoc
Labels: status/code-review

#1952 Add GiLab OAuth configuration manual
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/proc_configuring-gitlab-oauth2.adoc
Labels: kind/task, status/code-review

#1970 annotation-fix
  modules/end-user-guide/partials/proc_defining-maven-settings-xml-file-across-workspaces.adoc
Labels: kind/bug, status/code-review

#1969 Fix asciidoc warnings.
  .vale/styles/IBM/Terms.yml
  antora-playbook.yml
  modules/administration-guide/partials/proc_configuring-gitlab-oauth2.adoc
  modules/contributor-guide/partials/proc_defining-custom-branding-values-for-che-theia.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
Labels: kind/bug, need-cherry-pick/7.28.x, status/code-review

#1967 Clarify 'per user' project strategy in case if users didn't have enough privileges
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/task, status/code-review

#1972 Fix inconsistent capitalization
  modules/end-user-guide/partials/proc_investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
Labels: status/code-review
