Repository eclipse-che/che-docs, pull requests merged in 2021-06, with the labels that each got.

#2011 Fix repository location. Update generated docs after version bump.
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
  tools/environment_docs_gen.sh
Labels: cherry-picked to 7.31.x, kind/bug, status/code-review

#2010 Chore - Changes in Docs Team
  .github/CODEOWNERS
Labels: status/code-review

#2004 Configuring the number of workspaces
  modules/installation-guide/examples/che-pvc-strategies.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/configuring-the-number-of-workspaces-a-user-can-run.adoc
  modules/installation-guide/pages/running-more-than-one-workspace-at-a-time.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/assembly_configuring-the-number-of-workspaces-a-user-can-run.adoc
  modules/installation-guide/partials/con_persistent-volume-configuration.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-the-number-of-workspaces-a-user-can-run-using-configmap.adoc
  modules/installation-guide/partials/proc_configuring-the-number-of-workspaces-a-user-can-run-using-the-operator.adoc
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
Labels: need-cherry-pick/7.31.x, status/code-review

#2012 Authoring devfile version 1 and 2
  .vale/styles/IBM/Terms.yml
  .vale/styles/Vocab/Che/reject.txt
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/proc_building-a-custom-devfile-registry-image.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/end-user-guide/examples/che-adding-a-git-project-into-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/authoring-devfiles-version-1.adoc
  modules/end-user-guide/pages/authoring-devfiles-version-2.adoc
  modules/end-user-guide/pages/authoring-devfiles.adoc
  modules/end-user-guide/pages/configuring-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/partials/assembly_authoring-devfiles-version-1.adoc
  modules/end-user-guide/partials/assembly_authoring-devfiles-version-2.adoc
  modules/end-user-guide/partials/assembly_authoring-devfiles.adoc
  modules/end-user-guide/partials/assembly_configuring-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/partials/assembly_configuring-a-workspace-with-dashboard.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-code-sample.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-remote-devfile.adoc
  modules/end-user-guide/partials/assembly_defining-custom-commands-for-che-theia.adoc
  modules/end-user-guide/partials/con_additional-tools-in-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_allowing-users-to-define-workspace-deployment-labels-and-annotations.adoc
  modules/end-user-guide/partials/proc_changing-the-configuration-of-an-existing-workspace.adoc
  modules/end-user-guide/partials/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  modules/end-user-guide/partials/proc_overriding-devfile-values-using-factory-parameters.adoc
  modules/end-user-guide/partials/proc_using-private-container-registries.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
  modules/extensions/partials/assembly_telemetry-overview.adoc
Labels: status/code-review

#2014 fix: metadata on assembly_authoring-devfiles-version-2.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/partials/assembly_authoring-devfiles-version-2.adoc
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
Labels: cherry-picked to 7.30.x, cherry-picked to 7.31.x, kind/bug, status/code-review

#2018 fix: deploying Eclipse Che on GCP
  modules/installation-guide/partials/proc_installing-che-on-kubernetes_using_chectl_and_helm.adoc
Labels: kind/bug, status/code-review

#2019 fix: configuring custom che hostname
  modules/installation-guide/images/keycloak/keycloak_che_public_client.png
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
Labels: kind/bug, status/code-review

#2017 fix: vocabulary
  .vale/styles/Vocab/Che/accept.txt
Labels: kind/bug, status/code-review

#2021 Fix language
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: kind/bug, status/code-review

#2015 docs: Add note about common PVC deletion
  modules/installation-guide/partials/con_persistent-volume-configuration.adoc
Labels: status/code-review

#2025 fix: Corrected a typo in url of role_binding.yaml
  modules/administration-guide/partials/proc_installing-image-puller-on-kubernetes-using-the-image-puller-operator.adoc
Labels: kind/bug, status/code-review

#2030 chore(docs): update che-theia-plugins.yaml fields
  modules/end-user-guide/partials/proc_adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
Labels: status/code-review

#2028 chore: prepare vale infringements counter for vale warnings hunt.
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .vale/styles/CheDocs/SentenceLength.yml
  .vale/styles/Vocab/Che/accept.txt
  modules/administration-guide/partials/proc_developing-grafana-dashboards.adoc
  tools/count_vale_errors.sh
Labels: status/code-review

#2029 fix: Kubernetes Image Puller namespace
  antora-playbook.yml
  modules/administration-guide/partials/proc_installing-image-puller-using-helm.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-openshift-templates.adoc
Labels: kind/bug, status/code-review, team/che-qe

#2031 fix: Fixup of Configuring GitLab OAuth2 procedure.
  modules/administration-guide/partials/proc_configuring-gitlab-oauth2.adoc
Labels: kind/bug, kind/enhancement, status/code-review, team/che-qe

#2027 fix: missing prereq step for an OCP3 installation
  modules/installation-guide/partials/proc_installing-che-on-openshift-3-using-the-operator.adoc
Labels: kind/bug, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2032 docs: procedure: Adding a topic about the factory workspace-creation policy
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-remote-devfile.adoc
  modules/end-user-guide/partials/proc_allowing-users-to-define-workspace-creation-strategy.adoc
Labels: kind/enhancement, kind/task, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2035 fix: check and update of intelliJ docs
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-webstorm.adoc
Labels: kind/docs, kind/enhancement, kind/task, status/code-review, team/che-qe

#2036 fix: Use double quotes for bumped versions during release
  make-release.sh
Labels: kind/bug, status/code-review

#2040 chore: Adding Tereza Stastna to code owners
  .github/CODEOWNERS
Labels: status/code-review

#2039 procedure: removing an unnecesary procedure step for the Image Puller
  modules/administration-guide/examples/snip_che-images-incompatibles-with-image-puller.adoc
  modules/administration-guide/partials/proc_defining-the-list-of-images-to-pull.adoc
Labels: kind/bug, kind/enhancement, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2034 fix: fixing an inaccurate figure description
  modules/administration-guide/partials/con_che-workspaces-architecture.adoc
Labels: kind/enhancement, kind/question, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2044 feat(docs): better describe custom plugin scenarios
  modules/contributor-guide/partials/proc_overriding-ram-of-a-che-theia-plug-in.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: need-cherry-pick/7.30.x, status/code-review

#2047 fix: typo
  modules/end-user-guide/partials/proc_configuring_gitlab_authentication.adoc
Labels: kind/bug, need-cherry-pick/7.30.x, status/code-review

#2045 fix: Add a step for explicit configuration of GitLab OAuth2 endpoints;
  modules/administration-guide/partials/proc_configuring-gitlab-oauth2.adoc
Labels: kind/enhancement, kind/task, status/code-review, team/che-qe

#2033 fix: adapt docs to dashboard pages renaming
  modules/administration-guide/partials/proc_verification-custom-registries.adoc
  modules/end-user-guide/images/workspaces/che-sample-card.png
  modules/end-user-guide/images/workspaces/che-select-sample.png
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-code-sample.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_creating-a-custom-workspace-from-a-template.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-user-dashboard-get-started.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-user-dashboard-quick-add.adoc
Labels: kind/enhancement, kind/task, need-cherry-pick/7.31.x, need-cherry-pick/7.32.x, status/code-review, team/che-qe

#2042 procedure: use organization instead of github-handle to explain fork …
  CONTRIBUTING.adoc
Labels: status/code-review, team/che-qe
