Repository eclipse-che/che-docs, pull requests merged in 2021-03, with the labels that each got.

#1872 Backports for 7.26.x 2021 02 24
  .vale.ini
  .vale/styles/IBM/Terms.yml
  .vale/styles/Vocab/Che/accept.txt
  .vale/styles/Vocab/Che/reject.txt
  Jenkinsfile
  RELEASE.md
  devfile.yaml
  make-release.sh
  modules/administration-guide/partials/proc_configuring-bitbucket-server-oauth1.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-without-initial-user.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth.adoc
  modules/administration-guide/partials/proc_enabling-self-registration.adoc
  modules/administration-guide/partials/proc_removing-initial-openshift-user.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-maven-projects.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
  modules/hosted-che/partials/assembly_hosted-che.adoc
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/con_understanding-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  modules/installation-guide/partials/proc_configuring-che-hostname.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
  modules/installation-guide/partials/proc_logging-in-to-identity-provider.adoc
  modules/installation-guide/partials/proc_setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
  modules/installation-guide/partials/ref_checluster-custom-resource-fields-reference.adoc
  tools/checluster_docs_gen.sh
Labels: status/code-review, target/branch

#1810 Remove a non-functional procedure.
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
  modules/extensions/partials/assembly_eclipse-che4z.adoc
Labels: status/code-review

#1849 Building the registries: duplicate content instead of conditionals.
  modules/administration-guide/examples/snip_che-build-a-custom-devfile-registry.adoc
  modules/administration-guide/examples/snip_che-build-a-custom-plug-in-registry.adoc
  modules/administration-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/administration-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/administration-guide/examples/snip_customizing-the-plug-in-registry.adoc
  modules/administration-guide/pages/building-custom-registry-images.adoc
  modules/administration-guide/partials/assembly_building-custom-registry-images.adoc
  modules/administration-guide/partials/proc_building-a-custom-devfile-registry-image.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/administration-guide/partials/proc_verification-custom-registries.adoc
  modules/installation-guide/examples/assembly_che-installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/examples/proc_che-configuring-che-to-run-in-a-restricted-environment.adoc
  modules/installation-guide/examples/proc_che-preparing-a-private-registry.adoc
  modules/installation-guide/examples/snip_che-build-a-registry.adoc
  modules/installation-guide/examples/snip_che-build-an-offline-devfile-registry.adoc
  modules/installation-guide/examples/snip_che-build-an-offline-plug-in-registry.adoc
  modules/installation-guide/examples/snip_che-building-offline-registry-images.adoc
  modules/installation-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-registry-repository.adoc
  modules/installation-guide/partials/assembly_building-offline-registry-images.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_building-a-registry-image.adoc
  modules/installation-guide/partials/proc_building-an-offline-devfile-registry-image.adoc
  modules/installation-guide/partials/proc_building-an-offline-plug-in-registry-image.adoc
Labels: status/code-review

#1880 Revert "Provision GitHub OAuth using secret (#1773)"
  modules/administration-guide/images/git/kc_provider.png
  modules/administration-guide/images/git/kc_roles.png
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/administration-guide/partials/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  modules/end-user-guide/images/git/github-keycloak-setup.png
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/configuring-github-oauth.adoc
  modules/end-user-guide/partials/assembly_configuring-oauth-authorization.adoc
  modules/end-user-guide/partials/proc_configuring-github-oauth.adoc
  modules/end-user-guide/partials/proc_managing-pull-requests-using-the-github-pr-plug-in.adoc
Labels: status/code-review, target/branch

#1883 Update incorrect names.
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-nuget-projects.adoc
  modules/end-user-guide/partials/proc_using-self-signed-certificates-in-python-projects.adoc
Labels: kind/enhancement, status/code-review

#1837 Document how to install the Kubernetes Image Puller from Che Operator + fixes
  antora-playbook.yml
  modules/administration-guide/examples/snip_che-installing-image-puller-using-che-operator-prerequisites.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-the-image-puller-operator.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-the-operator.adoc
  modules/administration-guide/pages/installing-image-puller-using-che-operator.adoc
  modules/administration-guide/partials/con_caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/partials/proc_defining-the-list-of-images-to-pull.adoc
  modules/administration-guide/partials/proc_defining-the-memory-parameters-for-the-image-puller.adoc
  modules/administration-guide/partials/proc_installing-image-puller-on-kubernetes-using-the-image-puller-operator.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-che-operator.adoc
Labels: kind/bug, status/code-review

#1867 feat(vscode-extensions): Add section about how to use Eclipse Che API
  modules/contributor-guide/partials/ref_che-theia-plug-in-api.adoc
Labels: kind/enhancement, status/code-review

#1876 feat(recommendations-plugin): Add the documentation for the recommendations plug-in
  modules/end-user-guide/partials/assembly_adding-a-vs-code-extension-to-a-workspace.adoc
  modules/end-user-guide/partials/proc_adding-the-vs-code-extension-using-recommendations.adoc
Labels: kind/enhancement, status/code-review

#1879 Follow-up on remove a non-functional procedure. (#1810)
  modules/end-user-guide/examples/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
Labels: status/code-review

#1878 Chery-pick of Remove a non-functional procedure. (#1810)
  modules/end-user-guide/examples/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
  modules/extensions/partials/assembly_eclipse-che4z.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-a-helm-chart.adoc
Labels: status/code-review, target/branch

#1882 Little fixes
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
  modules/installation-guide/partials/proc_logging-in-to-identity-provider.adoc
Labels: kind/bug, status/code-review

#1877 Remove yarn.lock and package.json, docker support for tools.
  .gitignore
  package.json
  tools/detect-unused-images.sh
  tools/linkchecker.sh
  tools/newtopic.sh
  tools/podmanhtmltest.sh
  tools/podmanlinkchecker.sh
  tools/podmanpreview.sh
  tools/preview.sh
  tools/substitutions.sh
  tools/validate_attributes_processing.sh
  tools/verify_xrefs.sh
  yarn.lock
Labels: status/code-review

#1893 Fix build error caused by typo in page-aliases
  modules/administration-guide/pages/installing-image-puller-using-che-operator.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1884 RHDEVDOCS-2511 Updating the contribute using a badge section
  linkcheckerrc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/end-user-guide/partials/proc_using-a-badge-to-link-to-workspaces.adoc
Labels: need-cherry-pick/7.26.x, status/code-review

#1892 Fix build error: level 0 sections can only be used when doctype is book
  modules/installation-guide/partials/proc_setting-up-the-keycloak-che-username-readonly-theme-for-the-eclipse-che-login-page.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1889 Add direct references to non-CRW available plugins
  devfile.yaml
Labels: status/code-review

#1896 Fix erroneous usage of non existent che-hostname attribute
  modules/end-user-guide/partials/proc_configuring_bitbucket_authentication.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1899 Backport to 7.26.x: PR 1896 Fix erroneous usage of non existent che-hostname attribute
  modules/end-user-guide/partials/proc_configuring_bitbucket_authentication.adoc
Labels: cherry-picked to 7.26.x

#1891 Fix asciidoc warnings - Cleanups for customizing the registries
  modules/administration-guide/examples/assembly_che-building-custom-registry-images.adoc
  modules/administration-guide/pages/building-custom-registry-images.adoc
  modules/administration-guide/pages/running-custom-registries.adoc
  modules/installation-guide/partials/proc_building-an-offline-devfile-registry-image.adoc
  modules/installation-guide/partials/proc_building-an-offline-plug-in-registry-image.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1898 Fix usage of attribute in id
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1901 Refresh che-docs container: vale version bump, add missing dependencies
  Dockerfile
Labels: status/code-review

#1906 Removing the misleading information about the official plugin registry, which does not exist anymore
  modules/contributor-guide/partials/con_che-theia-plug-in-registries.adoc
  modules/contributor-guide/partials/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
Labels: status/code-review

#1907 Update linkchecker exceptions and vale rules.
  .vale/styles/Vocab/Che/accept.txt
  linkcheckerrc
Labels: kind/enhancement, status/code-review

#1905 Ensure cloning links point to the proper repositories
  modules/administration-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/administration-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
Labels: status/code-review

#1908 Downstreaming fixes
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
Labels: kind/bug, status/code-review

#1903 making changes for adding a note in admin guide
  modules/administration-guide/examples/snip_che-memory-requirement-note.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
Labels: status/code-review

#1897 Fix leftover of prod-url-secure attribute
  .vale/styles/CheDocs/Attributes.yml
  antora-playbook.yml
  modules/administration-guide/partials/proc_configuring-bitbucket-server-oauth1.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1890 Fix links - Use xref statement for internal links
  .vale/fixtures/CheDocs/InternalLinks/.vale.ini
  .vale/fixtures/CheDocs/InternalLinks/testinvalid.adoc
  .vale/fixtures/CheDocs/InternalLinks/testvalid.adoc
  .vale/styles/CheDocs/InternalLinks.yml
  modules/administration-guide/partials/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  modules/contributor-guide/partials/con_che-extension-points.adoc
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/assembly_using-alternative-ides-in-che.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-concept-in-detail.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-lifecycle.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-camel-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-omnisharp-theia-plug-in-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-xml-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-yaml-language-server.adoc
  modules/hosted-che/partials/proc_contributing-to-github-projects-in-hosted-che.adoc
  modules/installation-guide/partials/proc_upgrading-the-chectl-management-tool.adoc
Labels: kind/bug, need-cherry-pick/7.26.x, status/code-review

#1895 How to enable Dev Workspace engine
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/enabling-dev-workspace-engine.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_enabling-dev-workspace-engine.adoc
Labels: kind/enhancement, kind/epic, status/code-review

#1910 Cherry picks
  .vale/fixtures/CheDocs/InternalLinks/.vale.ini
  .vale/fixtures/CheDocs/InternalLinks/testinvalid.adoc
  .vale/fixtures/CheDocs/InternalLinks/testvalid.adoc
  .vale/styles/CheDocs/Attributes.yml
  .vale/styles/CheDocs/InternalLinks.yml
  antora-playbook.yml
  linkcheckerrc
  modules/administration-guide/examples/assembly_che-building-custom-registry-images.adoc
  modules/administration-guide/examples/snip_che-build-a-custom-devfile-registry.adoc
  modules/administration-guide/examples/snip_che-build-a-custom-plug-in-registry.adoc
  modules/administration-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/administration-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/administration-guide/examples/snip_che-memory-requirement-note.adoc
  modules/administration-guide/examples/snip_customizing-the-plug-in-registry.adoc
  modules/administration-guide/pages/building-custom-registry-images.adoc
  modules/administration-guide/pages/running-custom-registries.adoc
  modules/administration-guide/partials/assembly_building-custom-registry-images.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/proc_building-a-custom-devfile-registry-image.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/administration-guide/partials/proc_configuring-bitbucket-server-oauth1.adoc
  modules/administration-guide/partials/proc_enabling-authentication-with-social-accounts-and-brokering.adoc
  modules/administration-guide/partials/proc_verification-custom-registries.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/contributor-guide/partials/con_che-extension-points.adoc
  modules/end-user-guide/partials/assembly_importing-kubernetes-applications-into-a-workspace.adoc
  modules/end-user-guide/partials/assembly_using-alternative-ides-in-che.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-concept-in-detail.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-lifecycle.adoc
  modules/end-user-guide/partials/proc_using-a-badge-to-link-to-workspaces.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-camel-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-omnisharp-theia-plug-in-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-xml-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-yaml-language-server.adoc
  modules/hosted-che/partials/proc_contributing-to-github-projects-in-hosted-che.adoc
  modules/installation-guide/examples/assembly_che-installing-che-in-a-restricted-environment.adoc
  modules/installation-guide/examples/proc_che-configuring-che-to-run-in-a-restricted-environment.adoc
  modules/installation-guide/examples/proc_che-preparing-a-private-registry.adoc
  modules/installation-guide/examples/snip_che-build-a-registry.adoc
  modules/installation-guide/examples/snip_che-build-an-offline-devfile-registry.adoc
  modules/installation-guide/examples/snip_che-build-an-offline-plug-in-registry.adoc
  modules/installation-guide/examples/snip_che-building-offline-registry-images.adoc
  modules/installation-guide/examples/snip_che-clone-the-devfile-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/installation-guide/examples/snip_che-clone-the-registry-repository.adoc
  modules/installation-guide/partials/assembly_building-offline-registry-images.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_building-a-registry-image.adoc
  modules/installation-guide/partials/proc_building-an-offline-devfile-registry-image.adoc
  modules/installation-guide/partials/proc_building-an-offline-plug-in-registry-image.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_upgrading-the-chectl-management-tool.adoc
Labels: status/code-review, target/branch

#1875 RHDEVDOCS-1278: Providing a custom IDE based on Eclipse Theia
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/support-for-theia-based-ides.adoc
  modules/end-user-guide/partials/con_support-for-theia-based-ides.adoc
Labels: status/code-review

#1902 che-17654 Improving the documentation guide for running more than one workspace at a time
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
Labels: kind/task, status/code-review

#1916 Increasing the Eclipse Che hosted by Red Hat usage time limit to 30 days
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: status/code-review

#1887 Configure labels and domains to work with router sharding
  modules/administration-guide/partials/proc_configuring-openshift-oauth-without-initial-user.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/configuring-labels-and-domains-for-routes.adoc
  modules/installation-guide/pages/configuring-labels-for-routes.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/proc_configuring-labels-and-domains-for-routes.adoc
  modules/installation-guide/partials/proc_configuring-labels-for-routes.adoc
Labels: status/code-review

#1912 feat(java-lombok): Add documentation how to enable Lombok in Java workspaces
  modules/extensions/images/lombok/lombok.png
  modules/extensions/nav.adoc
  modules/extensions/pages/java-lombok.adoc
  modules/extensions/partials/proc_java-lombok.adoc
Labels: kind/question, status/code-review

#1913 Update the step.
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
Labels: kind/enhancement, need-cherry-pick/7.24.x, status/code-review

#1918 fix
  modules/extensions/partials/proc_java-lombok.adoc
Labels: kind/bug, status/code-review

#1909 move implementation details from admin guide closer to code
  modules/administration-guide/partials/assembly_authenticating-to-the-che-server.adoc
  modules/administration-guide/partials/assembly_monitoring-che.adoc
  modules/administration-guide/partials/proc_authenticating-to-the-che-server-using-openid.adoc
  modules/administration-guide/partials/proc_extending-che-monitoring-metrics.adoc
Labels: kind/task, status/code-review

#1919 Fix id containing a dot
  modules/end-user-guide/partials/proc_investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
Labels: kind/bug, status/code-review

#1920 Fix - Followup on rename of making-a-workspace-portable-using-a-devfile
  modules/administration-guide/partials/proc_building-a-custom-devfile-registry-image.adoc
Labels: kind/bug, status/code-review

#1914 Update vale rules.
  .vale/styles/IBM/Terms.yml
  .vale/styles/Vocab/Che/accept.txt
  modules/contributor-guide/partials/assembly_testing-che-theia-plug-ins.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  modules/installation-guide/examples/system-variables.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: kind/enhancement, status/code-review

#1921 Fix - use attribute in id
  modules/installation-guide/partials/proc_creating-an-instance-of-the-che-operator.adoc
Labels: kind/bug, status/code-review

#1866 RHDEVDOCS-2510 Updating the che.openshift.io links to workspaces.openshift.com
  CONTRIBUTING.adoc
  README.md
  linkcheckerrc
  modules/contributor-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/partials/proc_allowing-users-to-define-workspace-deployment-labels-and-annotations.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-a-feature-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-with-a-publicly-accessible-standalone-devfile-using-http.adoc
  modules/end-user-guide/partials/proc_overriding-devfile-values-using-factory-parameters.adoc
Labels: status/code-review

#1922 Add a note about full CA chain requirement for Che
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: kind/bug, status/code-review

#1923 A new procedure + fixes
  modules/administration-guide/partials/assembly_running-custom-registries.adoc
  modules/administration-guide/partials/proc_adding-a-custom-plug-in-registry-in-an-existing-che-workspace.adoc
  modules/administration-guide/partials/proc_verification-custom-registries.adoc
Labels: kind/docs, kind/enhancement, kind/feature, status/code-review

#1927 GitHub Workflows reorganization.
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .github/workflows/build-pr-docs.yaml
  .github/workflows/che.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-netlify.yml
  .github/workflows/unused-images.yaml
  .github/workflows/vale-on-pr.yaml
  .github/workflows/vale-on-push.yaml
Labels: status/code-review

#1929 Fix htmltest errors
  .htmltest.yml
Labels: kind/bug, status/code-review

#1930 One job on push. Count vale errors.
  .github/workflows/build-and-validate-on-push.yaml
Labels: status/code-review

#1931 fix broken-ID
  modules/end-user-guide/partials/proc_downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface.adoc
Labels: kind/bug, status/code-review

#1863 Refactor devfile reference.
  .vale/styles/Vocab/Che/reject.txt
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: status/code-review

#1925 Added documentation section about using private container registries
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/using-private-container-registries.adoc
  modules/end-user-guide/partials/assembly_customizing-developer-environments.adoc
  modules/end-user-guide/partials/proc_using-private-container-registries.adoc
Labels: kind/task, status/code-review

#1932 Fix TOC overflow
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/publish-netlify.yml
  supplemental-ui/css/extra.css
Labels: kind/bug, status/code-review

#1933 disable Concurrent Builds in Jenkinsfile
  Jenkinsfile
Labels: kind/enhancement, status/code-review

#1934 Fix language errors in assembly_introduction-to-eclipse-che.adoc.
  .github/workflows/build-and-validate-on-pr.yaml
  .vale/styles/Vocab/Che/accept.txt
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review
