Repository eclipse-che/che-docs, pull requests merged in 2021-05, with the labels that each got.

#1971 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/enhancement, status/code-review

#1974 Fix inconsistent capitalization
  modules/end-user-guide/partials/proc_investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
Labels: status/code-review

#1973 WIP: missing unit
  modules/installation-guide/examples/system-variables.adoc
Labels: status/code-review

#1976 adding interval example
  modules/administration-guide/partials/proc_removing-initial-openshift-user.adoc
  modules/administration-guide/partials/proc_removing-user-data.adoc
  modules/end-user-guide/partials/assembly_workspaces-overview.adoc
  modules/installation-guide/partials/proc_configuring-a-che-workspace-with-a-persistent-volume-strategy.adoc
  modules/installation-guide/partials/proc_configuring-labels-and-domains-for-routes.adoc
  modules/installation-guide/partials/proc_configuring-labels-for-ingresses.adoc
  modules/installation-guide/partials/proc_configuring-storage-types.adoc
  modules/installation-guide/partials/proc_configuring-workspace-exposure-strategies-using-an-operator.adoc
  modules/installation-guide/partials/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  modules/installation-guide/partials/proc_enabling-dev-workspace-engine.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_running-more-than-one-workspace-at-a-time.adoc
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/enhancement, status/code-review

#1977 Add missed paragraphs about servers configuration property
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/proc_configuring-bitbucket-servers.adoc
  modules/administration-guide/partials/proc_configuring-gitlab-servers.adoc
Labels: kind/enhancement, status/code-review

#1980 Fix include statement
  modules/installation-guide/partials/assembly_upgrading-che-namespace-strategies-other-than-per-user.adoc
Labels: kind/bug, status/code-review

#1979 instead of sed to remove spaces, use tr to remove spaces AND quotes
  tools/environment_docs_gen.sh
Labels: kind/bug, status/code-review

#1986 che-19271 Adding a note about support of both product & project devfiles on Eclipse Che hosted by Red Hat
  modules/hosted-che/images/hosted-che/get-started-product-and-community-devfiles.png
  modules/hosted-che/partials/ref_about-hosted-che.adoc
Labels: kind/task, status/code-review

#1983 Removed mentions of namespace strategies other than per-user
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/pages/configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_installing-che-using-storage-classes.adoc
Labels: kind/task, status/code-review

#1984 Remove references to outdated parts of dashboard
  modules/end-user-guide/partials/assembly_adding-a-vs-code-extension-to-a-workspace.adoc
  modules/end-user-guide/partials/con_additional-tools-in-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
Labels: need-cherry-pick/7.28.x, status/code-review

#1987 Backport Remove references to outdated parts of dashboard
  modules/end-user-guide/partials/assembly_adding-a-vs-code-extension-to-a-workspace.adoc
  modules/end-user-guide/partials/con_additional-tools-in-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
Labels: status/code-review, target/branch

#1989 Add missing `attributes` option in the codeblocks.
  modules/installation-guide/partials/proc_installing-cert-manager.adoc
Labels: kind/task, need-cherry-pick/7.28.x, status/code-review

#1982 Refresh checluster-properties.adoc and system-variables.adoc
  antora-playbook.yml
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
  tools/checluster_docs_gen.sh
  tools/environment_docs_gen.sh
Labels: status/code-review

#1990 Add hyphen to compound adjective, change wording
  modules/administration-guide/partials/con_che-architecture-overview.adoc
Labels: kind/enhancement, status/code-review

#1997 Fix metadata
  modules/administration-guide/partials/assembly_managing-identities-and-authorizations.adoc
Labels: kind/bug, status/code-review

#1996 Enable upstream plugin registry changes in downstream
  modules/administration-guide/examples/snip_che-plug-in-tree.adoc
  modules/administration-guide/examples/snip_plugin-registry-build-output.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/partials/proc_publishing-metadata-for-a-vs-code-extension.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: status/code-review

#1994 review of a review
  modules/administration-guide/partials/proc_configuring-gitlab-servers.adoc
Labels: kind/docs, kind/enhancement, status/code-review

#1995 a little fix
  modules/installation-guide/partials/proc_installing-cert-manager.adoc
Labels: kind/bug, status/code-review

#1998 Enable upstream plugin registry changes in downstream (#1996)
  modules/administration-guide/examples/snip_che-plug-in-tree.adoc
  modules/administration-guide/examples/snip_plugin-registry-build-output.adoc
  modules/administration-guide/partials/proc_building-a-custom-plug-in-registry-image.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/partials/proc_publishing-metadata-for-a-vs-code-extension.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: status/code-review, target/branch

#1993 Fail build on asciidoctorjs warning
  .github/workflows/build-and-validate-on-pr.yaml
Labels: status/code-review

#1999 Fix typos
  modules/installation-guide/examples/che-pvc-strategies.adoc
  modules/installation-guide/pages/upgrading-che-namespace-strategies-other-than-per-user.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubespray-using-chectl.adoc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review

#2001 Review accept.txt, do not use it for capitalization unless necessary
  .vale/styles/Vocab/Che/accept.txt
Labels: status/code-review

#2002 Fix links after che-server repository move
  antora-playbook.yml
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/end-user-guide/partials/con_a-minimal-devfile.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
Labels: kind/bug, status/code-review

#2003 More robust links
  .vale/styles/CheDocs/Links.yml
  modules/administration-guide/examples/snip_plugin-registry-build-output.adoc
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/con_che-editor-plug-in.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_che-user-dashboard.adoc
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/contributor-guide/partials/con_che-theia-plug-in-registries.adoc
  modules/contributor-guide/partials/proc_adding-a-che-theia-plug-in-into-a-workspace.adoc
  modules/contributor-guide/partials/proc_adding-a-che-theia-plug-in-to-the-che-plug-in-registry.adoc
  modules/contributor-guide/partials/proc_building-a-che-theia-container-image-with-custom-branding.adoc
  modules/contributor-guide/partials/proc_defining-custom-branding-values-for-che-theia.adoc
  modules/contributor-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/contributor-guide/partials/ref_che-theia-plug-in-api.adoc
  modules/end-user-guide/pages/adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
  modules/end-user-guide/partials/con_a-minimal-devfile.adoc
  modules/end-user-guide/partials/con_che-theia-plug-in-concept-in-detail.adoc
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
  modules/end-user-guide/partials/con_support-for-theia-based-ides.adoc
  modules/end-user-guide/partials/proc_adding-a-vs-code-extension-to-the-che-plugin-registry.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-by-importing-the-source-code-of-a-project.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-the-default-branch-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-using-chectl-and-a-local-devfile.adoc
  modules/end-user-guide/partials/proc_publishing-metadata-for-a-vs-code-extension.adoc
  modules/end-user-guide/partials/proc_writing-a-devfile-for-your-project.adoc
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
  modules/glossary/partials/con_glossary.adoc
  modules/hosted-che/partials/proc_contributing-to-github-projects-in-hosted-che.adoc
  modules/installation-guide/partials/assembly_using-the-chectl-management-tool.adoc
  modules/installation-guide/partials/proc_configuring-labels-and-domains-for-routes.adoc
  modules/installation-guide/partials/proc_configuring-labels-for-ingresses.adoc
  modules/installation-guide/partials/proc_configuring-storage-types.adoc
  modules/installation-guide/partials/proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/bug, severity/blocker, status/code-review

#1985 Image puller: do not use an attribute for the ServiceAccount name, change download URL for che-operator.clusterserviceversion.yaml, images is not a placeholder
  antora-playbook.yml
  modules/administration-guide/examples/snip_che-getting-the-list-of-relevant-images.adoc
  modules/administration-guide/examples/snip_che-image-puller-dockerfile.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-che-operator.adoc
  modules/administration-guide/partials/proc_installing-image-puller-using-openshift-templates.adoc
Labels: status/code-review

#2005 Update contributing.adoc
  CONTRIBUTING.adoc
  devfile.yaml
Labels: kind/enhancement, status/code-review

#2006 The reference to che-theia-plugins.yaml is specific to upstream.
  modules/end-user-guide/partials/ref_che-theia-plug-in-metadata.adoc
Labels: status/code-review

#2009 Fix link for downstream
  modules/end-user-guide/partials/con_che-theia-task-types.adoc
Labels: kind/bug, status/code-review
