Repository eclipse-che/che-docs, pull requests merged in 2021-07, with the labels that each got.

#2024 fix: Configuring the number of workspaces that a user can create
  modules/installation-guide/examples/che-pvc-strategies.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/configuring-the-number-of-workspaces-a-user-can-run.adoc
  modules/installation-guide/pages/configuring-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/installation-guide/pages/configuring-the-number-of-workspaces-that-a-user-can-run.adoc
  modules/installation-guide/partials/assembly_advanced-configuration.adoc
  modules/installation-guide/partials/assembly_configuring-the-number-of-workspaces-a-user-can-run.adoc
  modules/installation-guide/partials/assembly_configuring-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/installation-guide/partials/assembly_configuring-the-number-of-workspaces-that-a-user-can-run.adoc
  modules/installation-guide/partials/con_persistent-volume-configuration.adoc
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
  modules/installation-guide/partials/proc_configuring-the-number-of-workspaces-a-user-can-run-using-configmap.adoc
  modules/installation-guide/partials/proc_configuring-the-number-of-workspaces-a-user-can-run-using-the-operator.adoc
  modules/installation-guide/partials/proc_using-configmap-to-configure-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/installation-guide/partials/proc_using-configmap-to-configure-the-number-of-workspaces-that-a-user-can-run.adoc
  modules/installation-guide/partials/proc_using-the-operator-to-configure-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/installation-guide/partials/proc_using-the-operator-to-configure-the-number-of-workspaces-that-a-user-can-run.adoc
Labels: kind/bug, need-cherry-pick/7.31.x, need-cherry-pick/7.32.x, status/code-review, team/che-qe

#2052 fix: replaced destroy with removed in modules/contributor-guide/partials/c…
  modules/contributor-guide/partials/con_che-extension-points.adoc
Labels: need-cherry-pick/7.30.x, need-cherry-pick/7.32.x, status/code-review

#2049 namepsace stragegies: Updated
  modules/installation-guide/partials/proc_configuring-namespace-strategies.adoc
Labels: need-cherry-pick/7.32.x, status/code-review

#2050 feat: Add Github PAT-based auth configuration example
  modules/end-user-guide/examples/snip_github-personal-access-token-secret.adoc
  modules/end-user-guide/partials/assembly_authenticating-on-scm-server-with-a-personal-access-token.adoc
  modules/end-user-guide/partials/proc_configuring_github_authentication.adoc
Labels: kind/task, status/code-review

#2057 fix: pvcClaimSize-update
  modules/installation-guide/examples/checluster-properties.adoc
Labels: kind/bug, kind/docs, kind/enhancement, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2056 feat: update doc accordingly to che-operator changes
  modules/installation-guide/partials/proc_switching-between-external-and-internal-communication.adoc
Labels: kind/task, status/code-review, team/che-qe

#2048 Fix: Improve installation guide for CodeReady Containers
  modules/installation-guide/partials/assembly_installing-che-on-codeready-containers.adoc
  modules/installation-guide/partials/proc_creating-a-project-in-openshift-web-console.adoc
  modules/installation-guide/partials/proc_installing-che-on-codeready-containers-using-chectl.adoc
  modules/installation-guide/partials/proc_using-chectl-to-install-che-on-codeready-containers.adoc
  modules/installation-guide/partials/proc_using-codeready-containers-to-set-up-openshift-4.adoc
  modules/installation-guide/partials/proc_using-openshift-web-console-to-install-che-on-codeready-containers.adoc
  modules/installation-guide/partials/proc_using-the-operator-to-configure-the-number-of-workspaces-that-a-user-can-create.adoc
Labels: kind/bug, kind/enhancement, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2058 Fix: update of the TLS-certificate importing procedure
  modules/end-user-guide/partials/proc_importing-certificates-to-browsers.adoc
Labels: kind/docs, kind/enhancement, need-cherry-pick/7.30.x, status/code-review, team/che-qe

#2059 Update Installing Che on OpenShift 4 using OperatorHub
  modules/installation-guide/partials/assembly_installing-che-on-openshift-4-using-operatorhub.adoc
  modules/installation-guide/partials/proc_creating-a-project-in-openshift-web-console.adoc
  modules/installation-guide/partials/proc_creating-an-instance-of-the-che-operator.adoc
  modules/installation-guide/partials/proc_installing-the-che-operator.adoc
Labels: kind/enhancement, need-cherry-pick/7.30.x, status/code-review

#2064 chore: Update mounting secrets and configmap into container
  modules/installation-guide/pages/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container.adoc
  modules/installation-guide/partials/assembly_mounting-secrets-as-file-or-env-variable-in-container.adoc
  modules/installation-guide/partials/assembly_mounting-secrets-or-a-configmap-as-file-or-env-variable-in-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-as-a-file-into-a-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-as-an-environment-variable-into-a-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-or-a-configmap-as-a-file-into-a-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-or-a-configmap-as-an-environment-variable-into-a-container.adoc
Labels: kind/task, status/code-review

#2063 feat: Enable Devworkspaces on k8s
  modules/installation-guide/partials/proc_enabling-dev-workspace-engine.adoc
Labels: kind/enhancement, kind/task, status/code-review, team/che-qe

#2066 fix: remarks
  modules/installation-guide/partials/assembly_mounting-secrets-or-a-configmap-as-file-or-env-variable-in-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-or-a-configmap-as-a-file-into-a-container.adoc
  modules/installation-guide/partials/proc_mounting-a-secret-or-a-configmap-as-an-environment-variable-into-a-container.adoc
  modules/installation-guide/partials/snip_mounting-a-secret-or-a-configmap-into-a-container.adoc
Labels: kind/task, status/code-review

#2065 feat: document image puller default image workflow
  modules/administration-guide/partials/proc_installing-image-puller-using-che-operator.adoc
  modules/extensions/partials/assembly_eclipse-che4z.adoc
  modules/installation-guide/partials/con_understanding-che-server-advanced-configuration-not-using-the-operator.adoc
Labels: kind/enhancement, kind/epic, status/code-review

#2061 fix: invalid links
  modules/administration-guide/partials/proc_configuring-che-to-use-external-identity-provider.adoc
Labels: kind/bug, kind/enhancement, need-cherry-pick/7.32.x, status/code-review

#2068 chore: Problematic language -- replace master w/ main
  modules/end-user-guide/partials/proc_testing-the-vs-code-extension-using-gist.adoc
  modules/end-user-guide/partials/ref_devfile-reference.adoc
Labels: kind/docs, status/code-review, team/che-qe, team/platform

#2071 fix: Prerequisites and Procedure
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool.adoc
Labels: kind/bug, need-cherry-pick/7.32.x, status/code-review

#2074 procedure: BitBucket links and info
  modules/administration-guide/partials/proc_configuring-bitbucket-servers.adoc
Labels: kind/docs, kind/enhancement, need-cherry-pick/7.32.x, status/code-review, team/che-qe
