Repository eclipse-che/che-docs, pull requests merged in 2021-10, with the labels that each got.

#2123 procedures:Bitbucket Phase one (update)
  modules/administration-guide/partials/proc_configuring-bitbucket-servers.adoc
  modules/end-user-guide/examples/snip_bitbucket-personal-access-token-secret.adoc
  modules/end-user-guide/partials/proc_configuring_bitbucket_authentication.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates-old.adoc
  modules/installation-guide/partials/proc_importing-untrusted-tls-certificates.adoc
Labels: kind/enhancement, status/code-review, team/platform

#2127 chore: run publication daily
  Jenkinsfile
Labels: status/code-review

#2129 chore: add workflow which updates Che variables
  .github/workflows/che-variables-update.yml
Labels: status/code-review

#2149 Update CODEOWNERS
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review
