Repository eclipse-che/che-docs, pull requests merged in 2021-09, with the labels that each got.

#2106 fix: Remove mentions of the Safari browser
  modules/end-user-guide/partials/proc_importing-certificates-to-browsers.adoc
Labels: kind/bug, status/code-review, need-cherry-pick/7.34.x

#2108 docs: refresh generated docs
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
Labels: status/code-review

#2103 docs: Drop single user support
  modules/administration-guide/partials/assembly_authenticating-users.adoc
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/con_authentication-modes.adoc
  modules/administration-guide/partials/con_che-keycloak.adoc
  modules/administration-guide/partials/con_che-postgresql.adoc
  modules/administration-guide/partials/con_che-server.adoc
  modules/administration-guide/partials/con_che-workspace-controller.adoc
  modules/administration-guide/partials/con_che-workspace-jwt-proxy.adoc
  modules/administration-guide/partials/proc_configuring-che-to-use-external-identity-provider.adoc
  modules/administration-guide/partials/proc_configuring-che-to-work-without-identity-provider.adoc
  modules/administration-guide/partials/proc_configuring-github-oauth.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/installation-guide/partials/assembly_installing-che-on-docker-desktop.adoc
  modules/installation-guide/partials/assembly_installing-che-on-minikube.adoc
  modules/installation-guide/partials/assembly_installing-che-on-minishift.adoc
  modules/installation-guide/partials/assembly_installing-che.adoc
  modules/installation-guide/partials/con_security-considerations.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubernetes_using_chectl_and_helm.adoc
  modules/installation-guide/partials/proc_installing-che-on-minikube-using-chectl.adoc
  modules/installation-guide/partials/proc_installing-che-on-minishift-using-chectl.adoc
Labels: status/code-review

#2112 fix: When setting the context, no additional bracket should be added
  modules/installation-guide/partials/assembly_configuring-the-number-of-workspaces-that-a-user-can-create.adoc
Labels: kind/bug, status/code-review

#2113 feat: Replacing a customg action with the official 'try-in-web-ide'
  .github/workflows/try-in-web-ide.yaml
  .github/workflows/try-pr-on-eclipse-che-hosted-by-red-hat.yaml
Labels: status/code-review

#2114 docs: Add documentation for Try in Web IDE Github action
  modules/hosted-che/examples/snip_github-action-yaml-example-activity-types.adoc
  modules/hosted-che/examples/snip_github-action-yaml-example.adoc
  modules/hosted-che/images/hosted-che/github-action-comment.png
  modules/hosted-che/images/hosted-che/github-action-status-check.png
  modules/hosted-che/nav.adoc
  modules/hosted-che/pages/try-in-web-ide-github-action.adoc
  modules/hosted-che/partials/assembly_try-in-web-ide-github-action.adoc
  modules/hosted-che/partials/proc_adding-the-action-to-a-github-repository-workflow.adoc
  modules/hosted-che/partials/proc_providing-a-devfile.adoc
  modules/hosted-che/partials/ref_about-try-in-web-ide-github-action.adoc
Labels: status/code-review

#2117 fix: release script fixes
  .github/workflows/release.yml
  make-release.sh
Labels: kind/bug, status/code-review

#2119 release: Bump version to 7.36.1
  antora.yml
  make-release.sh
Labels: status/code-review

#2115 chore: PostgreSQL migration proc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/migration-from-postgresql-9-to-postgresql-13.adoc
  modules/administration-guide/partials/proc_migration_from_postgresql_9_to_postgresql_13.adoc
Labels: status/code-review

#2104 docs: Update the documentation section for the IntelliJ-based IDEs
  .vale.ini
  .vale/styles/Vocab/Che/accept.txt
  modules/end-user-guide/examples/snip_che-configuring-a-workspace-to-use-intellij-idea-community.adoc
  modules/end-user-guide/images/jetbrains/activation-code.jpg
  modules/end-user-guide/images/jetbrains/jetbrains-account.jpg
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/building-images-for-ides-based-on-the-intellij-platform.adoc
  modules/end-user-guide/pages/configuring-a-workspace-to-use-an-ide-based-on-the-intellij-platform.adoc
  modules/end-user-guide/pages/configuring-an-existing-workspace-to-use-intellij-idea.adoc
  modules/end-user-guide/pages/provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/pages/provisioning-the-jetbrains-offline-activation-code.adoc
  modules/end-user-guide/pages/support-for-jetbrains-ides.adoc
  modules/end-user-guide/pages/using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/pages/using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/pages/using-jetbrains-webstorm.adoc
  modules/end-user-guide/partials/assembly_building-images-for-ides-based-on-the-intellij-platform.adoc
  modules/end-user-guide/partials/assembly_configuring-a-workspace-to-use-an-ide-based-on-the-intellij-platform.adoc
  modules/end-user-guide/partials/assembly_using-alternative-ides-in-che.adoc
  modules/end-user-guide/partials/con_support-for-jetbrains-ides.adoc
  modules/end-user-guide/partials/proc_building-an-image-for-an-ide-based-on-the-intellij-platform.adoc
  modules/end-user-guide/partials/proc_building-an-image-for-intellij-idea-community-or-pycharm-community.adoc
  modules/end-user-guide/partials/proc_configuring-a-workspace-to-use-a-custom-image-with-an-ide-based-on-the-intellij-platform.adoc
  modules/end-user-guide/partials/proc_configuring-a-workspace-to-use-intellij-idea-community.adoc
  modules/end-user-guide/partials/proc_configuring-a-workspace-to-use-pycharm-community.adoc
  modules/end-user-guide/partials/proc_configuring-an-existing-workspace-to-use-intellij-idea.adoc
  modules/end-user-guide/partials/proc_provisioning-jetbrains-activation-code-for-offline-use.adoc
  modules/end-user-guide/partials/proc_provisioning-the-jetbrains-offline-activation-code.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-community-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-intellij-idea-ultimate-edition.adoc
  modules/end-user-guide/partials/proc_using-jetbrains-webstorm.adoc
Labels: status/code-review, need-cherry-pick/7.34.x
