Repository eclipse-che/che-docs, pull requests merged in 2022-12, with the labels that each got.

#2511 docs: upstream changes for downstream docs repo updates
  modules/administration-guide/examples/snip_che-supported-platforms-cli.adoc
  modules/administration-guide/examples/snip_che-supported-platforms.adoc
  modules/administration-guide/pages/installing-che-on-openshift-using-cli.adoc
  modules/administration-guide/pages/supported-platforms.adoc
Labels: status/code-review, target/branch

#2513 chore: update RELEASE.adoc
  RELEASE.adoc
Labels: status/code-review, target/branch

#2516 chore: add content-type to snippets
  modules/administration-guide/examples/snip_che-architecture-overview-with-devworkspace-additional-resources.adoc
  modules/administration-guide/examples/snip_che-build-a-custom-plug-in-registry.adoc
  modules/administration-guide/examples/snip_che-che-server-additional-resources.adoc
  modules/administration-guide/examples/snip_che-clone-the-plug-in-registry-repository.adoc
  modules/administration-guide/examples/snip_che-cloning-image-puller-project.adoc
  modules/administration-guide/examples/snip_che-create-monitoring-namespace.adoc
  modules/administration-guide/examples/snip_che-dashboard-additional-resources.adoc
  modules/administration-guide/examples/snip_che-devfile-meta.adoc
  modules/administration-guide/examples/snip_che-devfile-registry-additional-resources.adoc
  modules/administration-guide/examples/snip_che-devworkspace-additional-resources.adoc
  modules/administration-guide/examples/snip_che-image-puller-dockerfile.adoc
  modules/administration-guide/examples/snip_che-installing-che.adoc
  modules/administration-guide/examples/snip_che-memory-requirement-note.adoc
  modules/administration-guide/examples/snip_che-postgresql-additional-resources.adoc
  modules/administration-guide/examples/snip_che-process-and-apply-image-puller-openshift-templates.adoc
  modules/administration-guide/examples/snip_che-supported-platforms-cli.adoc
  modules/administration-guide/examples/snip_che-supported-platforms.adoc
  modules/administration-guide/examples/snip_che-technology-preview.adoc
  modules/administration-guide/examples/snip_che-upgrading-the-chectl-management-tool.adoc
  modules/administration-guide/partials/snip_installing-che-in-a-restricted-environment-additional-resources.adoc
  modules/administration-guide/partials/snip_mounting-a-secret-or-a-configmap-into-a-container.adoc
  modules/administration-guide/partials/snip_preparing-images-for-a-restricted-environment.adoc
  modules/end-user-guide/examples/con_customizing-ide-selection-with-the-che-editor-file.adoc
  modules/end-user-guide/examples/proc_using-the-che-prod-editor-file-to-select-an-ide.adoc
  modules/end-user-guide/examples/snip_che-supported-languages.adoc
  modules/end-user-guide/examples/snip_che-table-of-supported-editors.adoc
  modules/end-user-guide/partials/snip_warning-about-applying-a-configmap-that-sets-environment-variables.adoc
Labels: status/code-review, target/branch

#2505 docs: explain specific features added on top of Visual Studio Code
  modules/end-user-guide/pages/developer-workspaces.adoc
Labels: status/code-review, target/branch

#2507 procedures: do not reference Che-Theia in Importing untrusted TLS certificates
  modules/administration-guide/pages/importing-untrusted-tls-certificates.adoc
Labels: status/code-review, target/branch

#2517 chore: use plugin rather than plug-in
  modules/administration-guide/examples/creating-a-telemetry-plugin/AnalyticsManagerSkeleton.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/Dockerfile.jvm
  modules/administration-guide/examples/creating-a-telemetry-plugin/Dockerfile.native
  modules/administration-guide/examples/creating-a-telemetry-plugin/MainConfiguration.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/TelemetryService.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/destroy.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/increaseDuration.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/isEnabled.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/main.go
  modules/administration-guide/examples/creating-a-telemetry-plugin/onActivity.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/onEvent.java
  modules/administration-guide/examples/creating-a-telemetry-plugin/plugin.yaml
  modules/administration-guide/examples/creating-a-telemetry-plugin/pom_snippet.xml
  modules/administration-guide/examples/creating-a-telemetry-plugin/project_scaffolding.sh
  modules/administration-guide/examples/creating-a-telemetry-plugin/settings.xml
  modules/administration-guide/examples/creating-a-telemetry-plugin/webserver.yaml
  modules/administration-guide/examples/snip_che-build-a-custom-plugin-registry.adoc
  modules/administration-guide/examples/snip_che-clone-the-plugin-registry-repository.adoc
  modules/administration-guide/examples/snip_che-technology-preview.adoc
  modules/administration-guide/images/creating-a-telemetry-plugin/devworkspace_telemetry_plugin.png
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/che-operator.adoc
  modules/administration-guide/pages/che-theia-workspaces.adoc
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
  modules/administration-guide/pages/dashboard.adoc
  modules/administration-guide/pages/gateway.adoc
  modules/administration-guide/pages/plugin-registry.adoc
  modules/administration-guide/pages/server-components.adoc
  modules/administration-guide/pages/the-woopra-telemetry-plugin.adoc
  modules/administration-guide/pages/user-workspaces.adoc
  modules/administration-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/examples/con_customizing-ide-selection-with-the-che-editor-file.adoc
  modules/end-user-guide/examples/proc_using-the-che-prod-editor-file-to-select-an-ide.adoc
  modules/end-user-guide/pages/adding-a-vscode-extension.adoc
  modules/end-user-guide/pages/troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/partials/ref_parameters-for-che-editor-yaml.adoc
  modules/extensions/examples/snip_che-authenticating-with-openshift-connector-from-a-local-instance.adoc
  modules/extensions/partials/assembly_openshift-connector-overview.adoc
  modules/extensions/partials/con_features-of-openshift-connector.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
  modules/extensions/partials/proc_creating-components-with-openshift-connector-in-che.adoc
  modules/extensions/partials/proc_installing-openshift-connector-in-che.adoc
  modules/hosted-che/partials/proc_providing-a-devfile.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: status/code-review, target/branch

#2508 procedures: more options for minikube
  modules/administration-guide/pages/installing-che-on-minikube.adoc
Labels: status/code-review, target/branch

#2518 docs: remove the admin guide section about editor branding and add a note as a replacement
  modules/administration-guide/images/branding/about-dark.png
  modules/administration-guide/images/branding/about-light.png
  modules/administration-guide/images/branding/welcome-dark.png
  modules/administration-guide/images/branding/welcome-light.png
  modules/administration-guide/images/contribute.svg
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/branding-che-theia.adoc
  modules/administration-guide/pages/branding.adoc
  modules/administration-guide/partials/proc_building-a-che-theia-container-image-with-custom-branding.adoc
  modules/administration-guide/partials/proc_defining-custom-branding-values-for-che-theia.adoc
  modules/administration-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/pages/selecting-a-workspace-ide.adoc
Labels: status/code-review, target/branch

#2520 chore: rename Dockerfile to Containerfile
  .github/workflows/container-build.yml
  Containerfile
Labels: status/code-review, target/branch

#2521 fix: Configuring networking with labels and domain
  modules/administration-guide/pages/configuring-ingresses.adoc
  modules/administration-guide/pages/configuring-routes.adoc
Labels: kind/bug, status/code-review, target/branch

#2524 fix: attribute in navtitle
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/pages/collecting-logs-using-chectl.adoc
  modules/administration-guide/pages/uninstalling-che.adoc
  modules/end-user-guide/partials/proc_using-a-git-provider-access-token.adoc
  modules/glossary/pages/che-glossary.adoc
Labels: kind/bug, status/code-review, target/branch

#2525 fix: attributes usage in generated docs
  tools/checluster_docs_gen.sh
Labels: kind/bug, status/code-review, target/branch

#2527 fix: use the prod-short attribute
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
Labels: kind/bug, status/code-review, target/branch

#2526 fix: typo
  modules/administration-guide/pages/collecting-logs-using-chectl.adoc
Labels: kind/bug, status/code-review, target/branch, backported to 7.56.x

#2529 chore: bump version to 7.58 in antora.yml
  antora.yml
Labels: status/code-review, target/branch

#2528 chore: bump publication builder branch to 7.58.x
  publication-builder-antora-playbook.yml
Labels: status/code-review, target/branch

#2530 chore: set prerelease to false in antora.yml
  antora.yml
Labels: status/code-review, target/branch

#2519 chore: Update GitHub actions to use Node 16 and Ubuntu to latest
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .github/workflows/container-build.yml
  .github/workflows/container-on-pull-request.yml
  .github/workflows/publish-netlify.yml
  .github/workflows/try-in-web-ide.yaml
  .github/workflows/vale.yml
Labels: status/code-review, target/branch
