Repository eclipse-che/che-docs, pull requests merged in 2022-01, with the labels that each got.

#2205 chore: update commit template to use...
  make-release.sh
Labels: status/code-review, target/branch

#2210 chore: new GitHub organization for Vale styles
  tools/get_vale_styles.sh
Labels: status/code-review

#2211 chore: flag master as a prerelease
  antora.yml
Labels: status/code-review

#2208 chore: Update release procedure
  .github/workflows/build-and-validate-on-push.yaml
  RELEASE.adoc
  antora-playbook-for-development.yml
  antora-playbook-for-publication.yml
  antora.yml
  make-release.sh
Labels: status/code-review, target/branch

#2212 chore: enable container update
  gulpfile.js
Labels: status/code-review

#2207 docs: split the User Guide into two parts
  modules/user-guide/nav.adoc
  modules/user-guide/pages/advanced-usage.adoc
  modules/user-guide/pages/user-onboarding.adoc
Labels: status/code-review, target/branch

#2214 docs: outline of User Onboarding in User Guide
  modules/user-guide/nav.adoc
  modules/user-guide/pages/advanced-use.adoc
  modules/user-guide/pages/projects-with-git.adoc
  modules/user-guide/pages/projects-without-git.adoc
Labels: status/code-review, target/branch

#2213 chore: Update Dockerfile.
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-container.yml
  .github/workflows/publish-netlify.yml
  .gitignore
  Dockerfile
  antora-playbook-for-development.yml
  gulpfile.js
  package.json
  supplemental-ui/.htaccess
  supplemental-ui/css/search.css
  supplemental-ui/js/search-ui.js
  supplemental-ui/partials/footer-content.hbs
  supplemental-ui/partials/head-meta.hbs
  supplemental-ui/partials/header-content.hbs
Labels: status/code-review, target/branch

#2215 fix: fix build errors and warnings
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .github/workflows/publish-netlify.yml
  .vale/styles/CheDocs/ConfigMap.yml
  RELEASE.adoc
  RELEASE.md
  antora-playbook-for-development.yml
  antora.yml
  make-release.sh
  modules/administration-guide/examples/snip_che-getting-the-list-of-relevant-images.adoc
  modules/administration-guide/partials/con_che-plug-in-registry.adoc
  modules/administration-guide/partials/proc_configuring-minikube-github-authentication.adoc
  modules/installation-guide/examples/checluster-properties.adoc
  modules/installation-guide/examples/system-variables.adoc
  supplemental-ui/.htaccess
  supplemental-ui/_headers
  supplemental-ui/css/search.css
  supplemental-ui/img/favicon.ico
  supplemental-ui/js/search-ui.js
  supplemental-ui/partials/footer-content.hbs
  supplemental-ui/partials/head-meta.hbs
  supplemental-ui/partials/header-content.hbs
  supplemental-ui/ui.yml
  tools/checluster_docs_gen.sh
  tools/environment_docs_gen.sh
  tools/get_vale_styles.sh
Labels: kind/bug, status/code-review

#2216 chore: location for eclipse-che/che-docs-vale-style
  tools/get_vale_styles.sh
Labels: status/code-review

#2217 chore: align master pr workflow on main
  .github/workflows/build-and-validate-on-pr.yaml
Labels: status/code-review

#2204 docs: rebranding of Che4z content to remove "CA" from product names
  modules/extensions/partials/assembly_eclipse-che4z.adoc
Labels: status/code-review

#2202 procedures: Setting up GitLab OAuth and Che with DevWorkspace engine enabled
  modules/administration-guide/partials/assembly_configuring-authorization.adoc
  modules/administration-guide/partials/proc_configuring-gitlab-oauth2-with-che-server-engine.adoc
  modules/administration-guide/partials/proc_configuring-gitlab-oauth2-with-devworkspace-engine.adoc
Labels: status/code-review, need-cherry-pick/7.42.x

#2220 fix: avoid multiple includes
  modules/administration-guide/partials/assembly_backing-up-a-che-instance-to-a-rest-backup-server-by-using-prod-cli.adoc
  modules/administration-guide/partials/assembly_backing-up-a-che-instance-to-amazon-s3-by-using-prod-cli.adoc
  modules/administration-guide/partials/assembly_backing-up-a-che-instance-to-an-sftp-backup-server-by-using-prod-cli.adoc
  modules/administration-guide/partials/proc_backing-up-a-che-instance-to-a-rest-backup-server-by-using-prod-cli-and-a-chebackupserverconfiguration-custom-object.adoc
  modules/administration-guide/partials/proc_backing-up-a-che-instance-to-amazon-s3-by-using-prod-cli-and-a-chebackupserverconfiguration-custom-object.adoc
  modules/administration-guide/partials/proc_backing-up-a-che-instance-to-an-sftp-backup-server-by-using-prod-cli-and-a-chebackupserverconfiguration-custom-object.adoc
Labels: kind/bug, status/code-review
