Repository eclipse-che/che-docs, pull requests merged in 2022-09, with the labels that each got.

#2434 fix: formatting, italicizing for configuring-routes procedure
  modules/administration-guide/pages/configuring-routes.adoc
Labels: kind/bug, status/code-review, target/branch

#2432 feat: add documentation about required network policy for multitentan…
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-network-policies.adoc
  modules/administration-guide/pages/configuring-networking.adoc
Labels: status/code-review, target/branch

#2415 chore: Script for getting an up-to-date list of avail. devfiles
  tools/devfiles-list.sh
Labels: kind/docs, status/code-review, target/branch

#2435 Review of PR 2410
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-oauth-1-for-a-bitbucket-server.adoc
  modules/administration-guide/pages/configuring-oauth-1-for-bitbucket.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-bitbucket.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-the-bitbucket-cloud.adoc
  modules/administration-guide/pages/oauth-for-github-gitlab-or-bitbucket.adoc
  modules/administration-guide/partials/proc_applying-an-application-link-secret-for-the-bitbucket-server.adoc
  modules/administration-guide/partials/proc_applying-an-oauth-consumer-secret-for-the-bitbucket-cloud.adoc
  modules/administration-guide/partials/proc_setting-up-an-application-link-on-the-bitbucket-server.adoc
  modules/administration-guide/partials/proc_setting-up-an-oauth-consumer-in-the-bitbucket-cloud.adoc
Labels: status/code-review, target/branch

#2410 chore: Add documentation pages for the Bitbucket SAAS OAuth flow
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-oauth-1-for-a-bitbucket-server.adoc
  modules/administration-guide/pages/configuring-oauth-1-for-bitbucket.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-the-bitbucket-cloud.adoc
  modules/administration-guide/pages/oauth-for-github-gitlab-or-bitbucket.adoc
  modules/administration-guide/partials/proc_applying-an-application-link-secret-for-the-bitbucket-server.adoc
  modules/administration-guide/partials/proc_applying-an-oauth-consumer-secret-for-the-bitbucket-cloud.adoc
  modules/administration-guide/partials/proc_setting-up-an-application-link-on-the-bitbucket-server.adoc
  modules/administration-guide/partials/proc_setting-up-an-oauth-consumer-in-the-bitbucket-cloud.adoc
Labels: status/code-review, target/branch

#2436 docs: in installing-che-in-a-restricted-environment, link configuring-network-policies
  modules/administration-guide/pages/configuring-network-policies.adoc
  modules/administration-guide/pages/installing-che-in-a-restricted-environment.adoc
Labels: status/code-review, target/branch

#2437 fix: rename identity provider attributes for the migration procedure
  antora.yml
  modules/administration-guide/attachments/migration/1-prepare.sh
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/examples/proc_che-manually-upgrading-che-7-41-to-7-49-on-openshift.adoc
Labels: kind/bug, status/code-review, target/branch

#2438 Add a configuration note to the GitHub OAuth page
  modules/administration-guide/partials/proc_applying-the-github-oauth-app-secret.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2439 chore: Remove `{identity-provider}` template
  antora.yml
  modules/administration-guide/pages/installing-che-on-minikube-keycloak-oidc.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: status/code-review, target/branch

#2440 chore - add Vale GitHub action
  .github/workflows/vale.yml
Labels: status/code-review, target/branch

#2441 fix: use underscores in user-replaced values
  modules/administration-guide/examples/checluster-properties.adoc
  modules/administration-guide/examples/snip_che-build-a-custom-plug-in-registry.adoc
  modules/administration-guide/examples/system-variables.adoc
  modules/administration-guide/pages/configuring-che-hostname.adoc
  modules/administration-guide/pages/importing-untrusted-tls-certificates.adoc
  modules/administration-guide/pages/installing-che-on-red-hat-openshift-local.adoc
  modules/administration-guide/pages/repairing-the-devworkspace-operator-on-openshift.adoc
  modules/administration-guide/pages/using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/administration-guide/pages/using-the-cli-to-configure-the-checluster-custom-resource.adoc
  modules/end-user-guide/pages/first-time-contributors.adoc
  modules/end-user-guide/pages/troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/partials/proc_using-a-git-provider-access-token.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
  modules/end-user-guide/partials/proc_viewing-che-theia-ide-logs-on-the-cli.adoc
Labels: kind/bug, status/code-review, target/branch

#2443 feat: Adopt rollback.sh script to work after any migration steps
  modules/administration-guide/attachments/migration/rollback.sh
Labels: status/code-review, target/branch

#2442 fix: CRW-3315
  modules/administration-guide/attachments/migration/1-prepare.sh
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/attachments/migration/rollback.sh
  modules/administration-guide/pages/installing-che-on-openshift-using-cli.adoc
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
Labels: kind/bug, status/code-review, target/branch

#2451 fix: context agnostic devfile example
  modules/administration-guide/examples/snip_che-a-workspace-example.adoc
  modules/administration-guide/partials/con_a-workspace-example.adoc
Labels: kind/bug, status/code-review, target/branch

#2450 chore: update container
  .github/workflows/container-on-pull-request.yml
  Dockerfile
  antora.yml
  tools/build-and-verify-container.sh
  tools/build.sh
  tools/create_architecture_diagrams.py
Labels: status/code-review, target/branch

#2447 fix: update the web console install procedure to account for downstream variation
  modules/administration-guide/examples/snip_che-web-console-installation-steps.adoc
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
Labels: kind/bug, status/code-review, target/branch

#2453 fix: Add step to ensure, that there is no Che instances before deploy…
  modules/administration-guide/pages/installing-che-on-openshift-using-cli.adoc
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
Labels: kind/bug, status/code-review, target/branch

#2449 fix: snippet showing how to configure the defaultNamespace template
  modules/administration-guide/pages/configuring-workspace-target-namespace.adoc
Labels: kind/bug, status/code-review, target/branch

#2456 fix: typo in an antora.yml value
  antora.yml
Labels: kind/bug, status/code-review, target/branch

#2412 fix: clarification of user-specific settings.xml in response to customer feedback
  modules/end-user-guide/pages/using-credentials-and-configurations-in-workspaces.adoc
Labels: kind/bug, status/code-review, target/branch

#2458 chore: remove unused snip
  modules/administration-guide/examples/snip_che-web-console-installation-steps.adoc
Labels: status/code-review, target/branch

#2314 fix: minor improvements to the pages about secrets and configmaps
  modules/end-user-guide/pages/mounting-configmaps.adoc
  modules/end-user-guide/pages/mounting-secrets.adoc
Labels: kind/bug, status/code-review, target/branch

#2459 chore: Backport migration and rollback scripts
  antora.yml
  modules/administration-guide/attachments/migration/1-prepare.sh
  modules/administration-guide/attachments/migration/2-migrate.sh
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/attachments/migration/rollback.sh
  modules/administration-guide/examples/proc_che-manually-upgrading-che-7-41-to-7-49-on-openshift.adoc
Labels: status/code-review, target/branch
