Repository eclipse-che/che-docs, pull requests merged in 2022-04, with the labels that each got.

#2272 fix: antora-to-plain-asciidoc: exit on error, run at build time, fixi…
  antora.yml
  gulpfile.js
  modules/administration-guide/pages/che-theia-workspaces.adoc
  tools/antora-to-plain-asciidoc.sh
Labels: kind/bug, status/code-review

#2273 fix: typo on metadata
  modules/end-user-guide/pages/navigating-openshift-web-console-from-che.adoc
Labels: kind/bug, status/code-review

#2270 docs: Administration guide - Calculating Che resource requirements
  modules/administration-guide/examples/snip_a-che-workspace-example.adoc
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/con_a-workspace-example.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/con_operator-requirements.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
Labels: status/code-review

#2277 docs: applying the suggestions
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/con_operator-requirements.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
Labels: status/code-review

#2276 fix: devworkspace operator metrics docs
  modules/administration-guide/partials/proc_collecting-dev-workspace-operator-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_viewing-dev-workspace-operator-metrics-on-grafana-dashboards.adoc
Labels: kind/bug, status/code-review

#2263 docs: Update docs on collecting logs using chectl
  modules/administration-guide/pages/collecting-logs-using-chectl.adoc
Labels: status/code-review

#2265 feat: Provides 'Adding a Visual Studio Code Extension' module
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/adding-a-vscode-extension.adoc
Labels: status/code-review

#2278 docs: Administration guide: Removing user data
  modules/administration-guide/pages/removing-user-data.adoc
Labels: status/code-review

#2282 fix: docs.github.com new URLs, mitigation for 403
  .htmltest.yml
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
  modules/hosted-che/partials/proc_adding-the-action-to-a-github-repository-workflow.adoc
  modules/hosted-che/partials/proc_contributing-to-github-projects-in-hosted-che.adoc
Labels: kind/bug, status/code-review

#2271 docs: accessing private Git repos
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-oauth-1-for-bitbucket.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-github.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-gitlab.adoc
  modules/administration-guide/pages/oauth-for-github-gitlab-or-bitbucket.adoc
  modules/administration-guide/partials/proc_applying-the-bitbucket-application-link-secret.adoc
  modules/administration-guide/partials/proc_applying-the-github-oauth-app-secret.adoc
  modules/administration-guide/partials/proc_applying-the-gitlab-authorized-application-secret.adoc
  modules/administration-guide/partials/proc_setting-up-the-bitbucket-application-link.adoc
  modules/administration-guide/partials/proc_setting-up-the-github-oauth-app.adoc
  modules/administration-guide/partials/proc_setting-up-the-gitlab-authorized-application.adoc
Labels: status/code-review

#2252 docs: user onboarding, starting a new workspace, URL parameters
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/basic-actions-you-can-perform-on-a-workspace.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc
  modules/end-user-guide/pages/user-onboarding.adoc
Labels: status/code-review

#2284 docs: Installation guide supported platforms
  antora.yml
  modules/administration-guide/examples/ref_che-supported-platforms-and-installation-methods.adoc
Labels: status/code-review

#2287 fix: ifeval
  modules/administration-guide/partials/proc_applying-the-bitbucket-application-link-secret.adoc
  modules/administration-guide/partials/proc_applying-the-github-oauth-app-secret.adoc
  modules/administration-guide/partials/proc_applying-the-gitlab-authorized-application-secret.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc
Labels: kind/bug, status/code-review

#2289 fix: prefer attributes to ifeval directives
  antora.yml
  modules/administration-guide/examples/proc_che-developing-grafana-dashboards.adoc
  modules/administration-guide/examples/proc_che-viewing-che-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/examples/proc_che-viewing-dev-workspace-operator-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/examples/ref_che-grafana-dashboards-for-che.adoc
  modules/administration-guide/examples/ref_che-grafana-dashboards-for-the-dev-workspace-operator.adoc
  modules/administration-guide/examples/snip_che-installing-che.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/pages/collecting-logs-using-chectl.adoc
  modules/administration-guide/pages/configuring-namespace-strategies.adoc
  modules/administration-guide/pages/importing-untrusted-tls-certificates.adoc
  modules/administration-guide/pages/installing-che.adoc
  modules/administration-guide/pages/monitoring-che.adoc
  modules/administration-guide/pages/monitoring-the-dev-workspace-operator.adoc
  modules/administration-guide/pages/understanding-the-checluster-custom-resource.adoc
  modules/administration-guide/pages/upgrading-che-using-the-cli-management-tool.adoc
  modules/administration-guide/pages/using-the-chectl-management-tool.adoc
  modules/administration-guide/partials/assembly_installing-che-in-cloud.adoc
  modules/administration-guide/partials/proc_applying-the-bitbucket-application-link-secret.adoc
  modules/administration-guide/partials/proc_applying-the-github-oauth-app-secret.adoc
  modules/administration-guide/partials/proc_applying-the-gitlab-authorized-application-secret.adoc
  modules/end-user-guide/examples/snip_che-supported-ides.adoc
  modules/end-user-guide/images/logs/logging-the-client-server-traffic-for-debug-adapters.png
  modules/end-user-guide/images/logs/viewing-intelephense-events-in-the-output-panel.png
  modules/end-user-guide/images/logs/viewing-logs-for-php-debug.png
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc
  modules/end-user-guide/partials/proc_logging-the-client-server-traffic-for-debug-adapters.adoc
  modules/end-user-guide/partials/proc_viewing-intelephense-events-in-the-output-panel.adoc
  modules/end-user-guide/partials/proc_viewing-logs-for-php-debug.adoc
  modules/extensions/examples/snip_che-authenticating-with-openshift-connector-from-a-local-instance.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
Labels: kind/bug, status/code-review

#2290 fix: use local contribute image
  modules/administration-guide/images/contribute.svg
  modules/administration-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
Labels: kind/bug, status/code-review

#2291 fix: use the imagedir attribute for links to images
  modules/administration-guide/examples/proc_che-developing-grafana-dashboards.adoc
  modules/administration-guide/examples/ref_che-grafana-dashboards-for-che.adoc
  modules/administration-guide/partials/proc_enabling-and-exposing-che-metrics.adoc
  modules/administration-guide/partials/proc_testing-che-theia-with-custom-branding.adoc
  modules/end-user-guide/pages/automatic-token-injection.adoc
  modules/end-user-guide/pages/navigating-openshift-web-console-from-che.adoc
  modules/end-user-guide/partials/proc_accessing-che-from-red-hat-applications-menu.adoc
  modules/end-user-guide/partials/proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc
  modules/end-user-guide/partials/proc_viewing-camel-logs-in-the-output-panel.adoc
Labels: kind/bug, status/code-review

#2292 fix: use examples for portability of using CLI management tool procedures
  modules/administration-guide/examples/proc_che-installing-the-chectl-management-tool-on-linux-or-macos.adoc
  modules/administration-guide/examples/proc_che-installing-the-chectl-management-tool-on-windows.adoc
  modules/administration-guide/examples/proc_che-upgrading-the-chectl-management-tool.adoc
  modules/administration-guide/pages/using-the-chectl-management-tool.adoc
Labels: kind/bug, status/code-review

#2294 fix: level 0 sections build error
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
Labels: kind/bug, status/code-review

#2295 fix: small typo and suggestion for installation docs
  modules/administration-guide/partials/proc_using-chectl-to-install-che-on-codeready-containers.adoc
Labels: kind/bug, status/code-review

#2275 fix: change git credential mounting docs to be devworkspace-specific
  modules/end-user-guide/examples/snip_che-git-credential-file-as-kubernetes-secret-into-the-file.adoc
  modules/end-user-guide/pages/git-credential-store.adoc
Labels: kind/bug, status/code-review

#2299 docs: Installing Che on OpenShift 4 using OperatorHub
  modules/administration-guide/partials/proc_creating-an-instance-of-the-che-operator.adoc
  modules/administration-guide/partials/proc_installing-the-che-operator.adoc
Labels: status/code-review

#2279 docs: update Monitoring Che docs
  modules/administration-guide/examples/proc_che-developing-grafana-dashboards.adoc
  modules/administration-guide/examples/proc_che-viewing-che-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/examples/proc_che-viewing-dev-workspace-operator-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/examples/prometheus-config.adoc
  modules/administration-guide/examples/ref_che-grafana-dashboards-for-che.adoc
  modules/administration-guide/images/monitoring/monitoring-che-che-cluster-cr.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-1.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-2.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-3.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-executors-panel-4.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-general-panel.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-requests-panel.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-tomcat-panel.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-1.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-2.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-3.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-trace-panel-4.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-users-panel.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-workspace-detailed-panel-2.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-workspace-detailed-panel.png
  modules/administration-guide/images/monitoring/monitoring-che-che-server-dashboard-workspace-panel.png
  modules/administration-guide/images/monitoring/monitoring-che-new-grafana-dashboard-queries.png
  modules/administration-guide/images/monitoring/monitoring-che-new-grafana-dashboard-visualization.png
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/installing-prometheus-and-grafana.adoc
  modules/administration-guide/pages/monitoring-che.adoc
  modules/administration-guide/pages/monitoring-the-dev-workspace-operator.adoc
  modules/administration-guide/pages/monitoring-with-prometheus-and-grafana.adoc
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_collecting-dev-workspace-operator-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_enabling-and-exposing-che-metrics.adoc
  modules/administration-guide/partials/proc_viewing-che-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/partials/proc_viewing-dev-workspace-operator-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/partials/ref_devworkspace-specific-metrics.adoc
  modules/administration-guide/partials/ref_grafana-dashboards-for-the-dev-workspace-operator.adoc
Labels: status/code-review

#2304 fix: use the imagedir attribute for links to images.
  modules/administration-guide/partials/proc_enabling-and-exposing-che-metrics.adoc
  modules/administration-guide/partials/proc_viewing-che-metrics-on-grafana-dashboards.adoc
Labels: kind/bug, status/code-review

#2303 Allow devs to choose between docker and podman when running preview script
  tools/runnerpreview.sh
Labels: status/code-review

#2302 docs: updating minikube and crc installation guides
  modules/administration-guide/pages/installing-che-on-minikube.adoc
  modules/administration-guide/partials/proc_using-chectl-to-install-che-on-codeready-containers.adoc
  modules/administration-guide/partials/proc_using-minikube-and-lxc.adoc
  modules/administration-guide/partials/proc_using-minikube-to-set-up-kubernetes.adoc
Labels: status/code-review

#2298 feat: new doc about selecting workspace IDEs...
  modules/end-user-guide/pages/selecting-an-ide.adoc
Labels: kind/enhancement, status/code-review

#2305 fix: 3-subscribe.sh script
  antora.yml
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/pages/upgrading-che-7-41-on-openshift.adoc
Labels: kind/bug, status/code-review

#2301 procedures: Configuring workspace target namespace, Provisioning namespaces
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-che.adoc
  modules/administration-guide/pages/configuring-namespace-provisioning.adoc
  modules/administration-guide/pages/configuring-namespace-strategies.adoc
  modules/administration-guide/pages/configuring-workspace-target-namespace.adoc
  modules/administration-guide/pages/configuring-workspaces-globally.adoc
  modules/administration-guide/pages/provisioning-namespaces-in-advance.adoc
Labels: status/code-review

#2306 fix: page-aliases
  modules/administration-guide/pages/uninstalling-che-on-openshift.adoc
Labels: kind/bug, status/code-review

#2308 fix: Adapt migration to the new product id
  antora.yml
  modules/administration-guide/attachments/migration/1-prepare.sh
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/attachments/migration/4-wait.sh
  modules/administration-guide/pages/upgrading-che-7-41-on-openshift.adoc
Labels: kind/bug, status/code-review

#2310 fix: link
  modules/administration-guide/examples/ref_che-supported-platforms-and-installation-methods.adoc
Labels: kind/bug, status/code-review

#2311 chore: remove keycloak
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: status/code-review

#2300 chore: added :description:
  modules/administration-guide/pages/advanced-configuration-options-for-the-che-server-component.adoc
  modules/administration-guide/pages/architecture-overview.adoc
  modules/administration-guide/pages/branding-che-theia.adoc
  modules/administration-guide/pages/branding.adoc
  modules/administration-guide/pages/caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/pages/che-operator.adoc
  modules/administration-guide/pages/che-server.adoc
  modules/administration-guide/pages/che-theia-workspaces.adoc
  modules/administration-guide/pages/checluster-custom-resource-fields-reference.adoc
  modules/administration-guide/pages/collecting-logs-using-chectl.adoc
  modules/administration-guide/pages/configuring-che-hostname.adoc
  modules/administration-guide/pages/configuring-che-to-run-in-a-restricted-environment.adoc
  modules/administration-guide/pages/configuring-che.adoc
  modules/administration-guide/pages/configuring-ingresses.adoc
Labels: status/code-review
