Repository eclipse-che/che-docs, pull requests merged in 2022-03, with the labels that each got.

#2230 docs: set telemetry backend-base version to 0.0.32
  modules/extensions/examples/telemetry/pom_snippet.xml
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
Labels: status/code-review

#2235 fix: all xref pointing to real page name rather than page-aliases.
  modules/administration-guide/pages/che-operator.adoc
  modules/administration-guide/pages/che-server.adoc
  modules/administration-guide/pages/dashboard.adoc
  modules/administration-guide/pages/devfile-registries.adoc
  modules/administration-guide/pages/gateway.adoc
  modules/administration-guide/pages/plug-in-registry.adoc
  modules/administration-guide/pages/postgresql.adoc
  modules/administration-guide/pages/server-components.adoc
  modules/administration-guide/pages/user-workspaces.adoc
  modules/administration-guide/partials/assembly_calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/assembly_managing-identities-and-authorizations.adoc
  modules/administration-guide/partials/assembly_retrieving-che-logs.adoc
  modules/administration-guide/partials/assembly_understanding-che-workspaces-architecture-with-che-server.adoc
  modules/administration-guide/partials/con_che-dashboard.adoc
  modules/administration-guide/partials/con_che-postgresql.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/con_dashboard.adoc
  modules/administration-guide/partials/con_devfile-registries.adoc
  modules/administration-guide/partials/con_plug-in-registry.adoc
  modules/administration-guide/partials/con_postgresql.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-with-initial-user.adoc
  modules/administration-guide/partials/proc_configuring-openshift-oauth-without-initial-user.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/contributor-guide/partials/proc_developing-che-theia-plug-ins-using-che.adoc
  modules/end-user-guide/pages/support-for-theia-based-ides.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-a-code-sample.adoc
  modules/end-user-guide/partials/assembly_creating-a-workspace-from-a-template-devfile.adoc
  modules/end-user-guide/partials/proc_adding-language-support-plug-in-to-the-che-workspace.adoc
  modules/end-user-guide/partials/proc_changing-the-configuration-of-an-existing-workspace.adoc
  modules/end-user-guide/partials/proc_che-including-kubernetes-applications-in-a-workspace-devfile-definition.adoc
  modules/end-user-guide/partials/proc_creating-a-workspace-from-user-dashboard-quick-add.adoc
  modules/end-user-guide/partials/proc_importing-the-source-code-of-a-project-into-a-workspace.adoc
  modules/end-user-guide/partials/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-open-button.adoc
  modules/end-user-guide/partials/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-recent-workspaces.adoc
  modules/end-user-guide/partials/proc_running-an-existing-workspace-from-the-user-dashboard-using-the-run-button.adoc
  modules/end-user-guide/partials/proc_using-private-container-registries.adoc
  modules/extensions/partials/assembly_telemetry-overview.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
  modules/installation-guide/nav.adoc
  modules/installation-guide/pages/checluster-custom-resource-fields-reference.adoc
  modules/installation-guide/pages/understanding-the-checluster-custom-resource.adoc
  modules/installation-guide/partials/assembly_installing-che-locally.adoc
  modules/installation-guide/partials/assembly_installing-che-on-openshift-4-using-operatorhub.adoc
  modules/installation-guide/partials/assembly_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_installing-che-on-kubernetes_using_chectl.adoc
  modules/installation-guide/partials/proc_installing-che-using-the-che-operator-in-openshift-4-web-console.adoc
  modules/installation-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/installation-guide/partials/proc_using-chectl-to-install-che-on-codeready-containers.adoc
  modules/overview/partials/assembly_introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review

#2236 docs: Updating hosted-che guide
  modules/hosted-che/images/hosted-che/getting-started-devfile.png
  modules/hosted-che/images/hosted-che/unblock_third_party_cookies.png
  modules/hosted-che/partials/proc_adding-the-action-to-a-github-repository-workflow.adoc
  modules/hosted-che/partials/proc_creating-a-workspace-from-template-in-hosted-che.adoc
  modules/hosted-che/partials/proc_creating-a-workspace-from-the-user-dashboard.adoc
  modules/hosted-che/partials/proc_providing-a-devfile.adoc
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: status/code-review

#2231 docs: creating a devworkspace telemetry plug-in
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/AnalyticsManagerSkeleton.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/Dockerfile.jvm
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/Dockerfile.native
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/MainConfiguration.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/TelemetryService.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/destroy.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/increaseDuration.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/isEnabled.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/main.go
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/onActivity.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/onEvent.java
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/plugin.yaml
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/pom_snippet.xml
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/project_scaffolding.sh
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/settings.xml
  modules/extensions/examples/creating-a-telemetry-plug-in-for-devworkspaces/webserver.yaml
  modules/extensions/images/creating-a-telemetry-plug-in-for-devworkspaces/devworkspace_telemetry_plugin.png
  modules/extensions/nav.adoc
  modules/extensions/pages/creating-a-telemetry-plugin-for-devworkspaces.adoc
  modules/extensions/partials/assembly_telemetry-overview.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin-for-devworkspaces.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
Labels: status/code-review

#2240 fix: replace end-user by user in the content
  modules/administration-guide/partials/con_dashboard.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/customizing-workspaces-components.adoc
  modules/end-user-guide/pages/first-time-contributors.adoc
  modules/end-user-guide/pages/investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
  modules/end-user-guide/pages/troubleshooting-che.adoc
  modules/end-user-guide/pages/troubleshooting-network-problems.adoc
  modules/end-user-guide/pages/troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/pages/using-developer-workspaces.adoc
  modules/hosted-che/partials/ref_about-try-in-web-ide-github-action.adoc
Labels: kind/bug, status/code-review

#2247 fix: fix metadata for conversion to plain AsciiDoc
  .vale/styles/PlainAsciiDoc/.vale.ini
  .vale/styles/PlainAsciiDoc/AnchorInXref.yml
  .vale/styles/PlainAsciiDoc/AnchorsInCrossGuideLink.yml
  .vale/styles/PlainAsciiDoc/AnchorsInLink.yml
  .vale/styles/PlainAsciiDoc/CrossGuideContext.yml
  .vale/styles/PlainAsciiDoc/LinkToFileName.yml
  .vale/styles/PlainAsciiDoc/XrefToFileName.yml
  antora.yml
  modules/administration-guide/examples/con_che-understanding-network-connectivity-in-restricted-environments.adoc
  modules/administration-guide/examples/proc_che-configuring-che-to-run-in-a-restricted-environment.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/pages/configuring-che-to-run-in-a-restricted-environment.adoc
  modules/administration-guide/pages/configuring-namespace-strategies.adoc
  modules/administration-guide/pages/dashboard.adoc
  modules/administration-guide/pages/devfile-registries.adoc
  modules/administration-guide/pages/installing-che-in-a-restricted-environment.adoc
  modules/administration-guide/pages/installing-che-locally.adoc
  modules/administration-guide/pages/installing-che.adoc
  modules/administration-guide/pages/preparing-a-restricted-environment.adoc
  modules/administration-guide/pages/upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/administration-guide/pages/upgrading-che.adoc
  modules/administration-guide/partials/proc_mounting-a-secret-or-a-configmap-as-a-file-into-a-container.adoc
  modules/administration-guide/partials/proc_mounting-a-secret-or-a-configmap-as-an-environment-variable-into-a-container.adoc
  modules/administration-guide/partials/proc_upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/administration-guide/partials/proc_upgrading-the-chectl-management-tool.adoc
  modules/administration-guide/partials/proc_using-chectl-to-install-che-on-codeready-containers.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
  modules/end-user-guide/examples/che-adding-a-git-project-into-a-workspace-using-a-devfile.adoc
  modules/end-user-guide/pages/git-credential-store.adoc
  modules/end-user-guide/pages/investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
  modules/end-user-guide/pages/secret-as-a-file.adoc
  modules/end-user-guide/pages/secret-as-a-variable.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-camel-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-eclipse-jdt-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-netcoredebugoutput-plug-in.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-omnisharp-theia-plug-in-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-xml-language-server.adoc
  modules/end-user-guide/partials/proc_verifying-the-state-of-the-yaml-language-server.adoc
  modules/extensions/partials/assembly_telemetry-overview.adoc
  modules/extensions/partials/proc_authenticating-with-openshift-connector-from-che.adoc
  modules/extensions/partials/proc_creating-components-with-openshift-connector-in-che.adoc
  modules/extensions/partials/proc_installing-openshift-connector-in-che.adoc
  modules/hosted-che/partials/proc_adding-the-action-to-a-github-repository-workflow.adoc
  modules/hosted-che/partials/proc_creating-a-workspace-from-the-user-dashboard.adoc
  tools/antora-to-plain-asciidoc.sh
Labels: kind/bug, status/code-review

#2239 chore: Update call-publication-builder.yaml and CODEOWNERS
  .github/CODEOWNERS
  .github/workflows/call-publication-builder.yaml
Labels: status/code-review, target/branch

#2229 chore: Add initial Devfile v2 devfile flow
  .gitignore
  .vscode/extensions.json
  devfile.yaml
Labels: status/code-review, target/branch

#2246 docs: move telemetry docs to Administration Guide
  modules/administration-guide/examples/creating-a-telemetry-plug-in/AnalyticsManagerSkeleton.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/Dockerfile.jvm
  modules/administration-guide/examples/creating-a-telemetry-plug-in/Dockerfile.native
  modules/administration-guide/examples/creating-a-telemetry-plug-in/MainConfiguration.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/TelemetryService.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/destroy.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/increaseDuration.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/isEnabled.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/main.go
  modules/administration-guide/examples/creating-a-telemetry-plug-in/onActivity.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/onEvent.java
  modules/administration-guide/examples/creating-a-telemetry-plug-in/plugin.yaml
  modules/administration-guide/examples/creating-a-telemetry-plug-in/pom_snippet.xml
  modules/administration-guide/examples/creating-a-telemetry-plug-in/project_scaffolding.sh
  modules/administration-guide/examples/creating-a-telemetry-plug-in/settings.xml
  modules/administration-guide/examples/creating-a-telemetry-plug-in/webserver.yaml
  modules/administration-guide/images/creating-a-telemetry-plug-in/devworkspace_telemetry_plugin.png
  modules/administration-guide/images/telemetry/telemetry_diagram.png
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/che-theia-workspaces.adoc
  modules/administration-guide/pages/configuring-observability.adoc
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
  modules/administration-guide/pages/the-woopra-telemetry-plugin.adoc
  modules/extensions/examples/telemetry/AnalyticsManagerSkeleton.java
  modules/extensions/examples/telemetry/MainConfiguration.java
  modules/extensions/examples/telemetry/che_cluster_with_custom_plugin.yaml
  modules/extensions/examples/telemetry/destroy.java
  modules/extensions/examples/telemetry/increaseDuration.java
  modules/extensions/examples/telemetry/isEnabled.java
  modules/extensions/examples/telemetry/main.go
  modules/extensions/examples/telemetry/onActivity.java
  modules/extensions/examples/telemetry/onEvent.java
  modules/extensions/examples/telemetry/pom_snippet.xml
  modules/extensions/examples/telemetry/sample_meta.yaml
  modules/extensions/examples/telemetry/settings.xml
  modules/extensions/examples/telemetry/webserver.yaml
  modules/extensions/images/telemetry/custom_telemetry_plugin.png
  modules/extensions/nav.adoc
  modules/extensions/pages/creating-a-telemetry-plugin-for-devworkspaces.adoc
  modules/extensions/pages/creating-a-telemetry-plugin.adoc
  modules/extensions/pages/telemetry.adoc
  modules/extensions/pages/the-woopra-telemetry-plugin.adoc
  modules/extensions/partials/proc_creating-a-telemetry-plugin.adoc
Labels: status/code-review

#2248 docs: Benefits of reviewing pull and merge requests in Eclipse Che
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/benefits-of-pull-requests-review-in-che.adoc
  modules/end-user-guide/pages/using-developer-workspaces.adoc
Labels: status/code-review

#2253 chore: remove references to installation guide, unless in page-aliases
  modules/administration-guide/pages/advanced-configuration-options-for-the-che-server-component.adoc
  modules/administration-guide/pages/checluster-custom-resource-fields-reference.adoc
  modules/administration-guide/pages/configuring-che-hostname.adoc
  modules/administration-guide/pages/configuring-che-to-run-in-a-restricted-environment.adoc
  modules/administration-guide/pages/configuring-che.adoc
  modules/administration-guide/pages/configuring-ingresses.adoc
  modules/administration-guide/pages/configuring-namespace-strategies.adoc
  modules/administration-guide/pages/configuring-routes.adoc
  modules/administration-guide/pages/configuring-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/administration-guide/pages/configuring-workspaces-nodeselector.adoc
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
  modules/administration-guide/pages/deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc
  modules/administration-guide/pages/importing-untrusted-tls-certificates.adoc
  modules/administration-guide/pages/installing-che-in-a-restricted-environment.adoc
  modules/administration-guide/pages/installing-che-using-storage-classes.adoc
  modules/administration-guide/pages/installing-che.adoc
  modules/administration-guide/pages/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container.adoc
  modules/administration-guide/pages/supported-platforms.adoc
  modules/administration-guide/pages/understanding-the-checluster-custom-resource.adoc
  modules/administration-guide/pages/uninstalling-che-after-chectl-installation.adoc
  modules/administration-guide/pages/uninstalling-che-after-operatorhub-installation-using-openshift-cli.adoc
  modules/administration-guide/pages/uninstalling-che-after-operatorhub-installation-using-openshift-web-console.adoc
  modules/administration-guide/pages/uninstalling-che.adoc
  modules/administration-guide/pages/upgrading-che-using-operatorhub.adoc
  modules/administration-guide/pages/upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/administration-guide/pages/upgrading-che-using-the-cli-management-tool.adoc
  modules/administration-guide/pages/upgrading-che.adoc
  modules/administration-guide/pages/using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/administration-guide/pages/using-the-cli-to-configure-the-checluster-custom-resource.adoc
  modules/administration-guide/pages/using-the-openshift-web-console-to-configure-the-checluster-custom-resource-during-installation.adoc
  modules/administration-guide/pages/using-the-openshift-web-console-to-configure-the-checluster-custom-resource.adoc
  modules/administration-guide/partials/proc_building-an-offline-devfile-registry-image.adoc
  modules/administration-guide/partials/proc_building-an-offline-plug-in-registry-image.adoc
  modules/administration-guide/partials/proc_creating-an-instance-of-the-che-operator.adoc
  tools/newtopic.sh
Labels: status/code-review

#2250 docs: Adding 'Integrating with Kubernetes' user guide
  modules/end-user-guide/images/installation/che-red-hat-application-menu-che-odp.png
  modules/end-user-guide/images/integration/token-injection.png
  modules/end-user-guide/images/navigation/navigating-openshift-web-console-from-che-dashboard.png
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/automatic-token-injection.adoc
  modules/end-user-guide/pages/integrating-with-kubernetes.adoc
  modules/end-user-guide/pages/navigating-che-from-openshift-developer-perspective.adoc
  modules/end-user-guide/pages/navigating-openshift-web-console-from-che.adoc
  modules/end-user-guide/partials/proc_accessing-che-from-red-hat-applications-menu.adoc
Labels: status/code-review

#2258 docs: Administration guide: caching images for faster workspace start
  modules/administration-guide/examples/snip_che-getting-the-list-of-relevant-images.adoc
  modules/administration-guide/examples/snip_che-list-of-images-for-faster-workspace-start.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/caching-images-for-faster-workspace-start.adoc
  modules/administration-guide/pages/defining-the-list-of-images-to-pull.adoc
  modules/administration-guide/pages/defining-the-memory-parameters-for-the-image-puller.adoc
  modules/administration-guide/pages/installing-image-puller-on-kubernetes-using-the-image-puller-operator.adoc
  modules/administration-guide/pages/installing-image-puller-using-che-operator.adoc
Labels: status/code-review
