Repository eclipse-che/che-docs, pull requests merged in 2022-08, with the labels that each got.

#2406 fix: importing untrusted tls certificates language review
  modules/administration-guide/pages/importing-untrusted-tls-certificates.adoc
Labels: kind/bug, status/code-review, target/branch

#2416 fix: parent context
  modules/end-user-guide/partials/proc_using-a-git-provider-access-token.adoc
  modules/hosted-che/partials/ref_hosted-che-faq-and-troubleshooting.adoc
Labels: kind/bug, kind/docs, status/code-review, target/branch

#2418 docs: add a new step to the procedure
  modules/end-user-guide/pages/enabling-maven-artifact-repositories.adoc
Labels: status/code-review, target/branch

#2417 fix: minor update to the snip of support IDEs
  modules/end-user-guide/examples/snip_che-table-of-supported-editors.adoc
Labels: kind/bug, status/code-review, target/branch

#2419 docs: procedure to repair the DevWorkspace Operator
  antora.yml
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
  modules/administration-guide/pages/devfile-registries.adoc
  modules/administration-guide/pages/repairing-the-devworkspace-operator-on-openshift.adoc
  modules/end-user-guide/pages/customizing-workspace-components.adoc
Labels: status/code-review, target/branch

#2420 procedure: adding java 8 command for enabling maven artifact repositories
  modules/end-user-guide/pages/enabling-maven-artifact-repositories.adoc
Labels: status/code-review, target/branch

#2411 fix: update the procedures for setting the limits for the numbers of workspaces kept and running
  modules/administration-guide/examples/snip_che-default-namespace.adoc
  modules/administration-guide/examples/snip_che-enabling-users-to-run-multiple-workspaces-simultaneously.adoc
  modules/administration-guide/examples/snip_che-limiting-the-number-of-workspaces-that-a-user-can-keep.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-the-number-of-workspaces-that-a-user-can-create.adoc
  modules/administration-guide/pages/configuring-workspaces-globally.adoc
  modules/administration-guide/pages/enabling-users-to-run-multiple-workspaces-simultaneously.adoc
  modules/administration-guide/pages/limiting-the-number-of-workspaces-that-a-user-can-keep.adoc
Labels: kind/bug, status/code-review, target/branch

#2424 chore: add missing steps in the release procedure
  RELEASE.adoc
Labels: status/code-review, target/branch

#2425 chore: normalized metadata for user guide (present, sorted)
  modules/end-user-guide/pages/adding-a-vscode-extension.adoc
  modules/end-user-guide/pages/adopting-che.adoc
  modules/end-user-guide/pages/authenticating-to-a-git-server-from-a-workspace.adoc
  modules/end-user-guide/pages/automatic-token-injection.adoc
  modules/end-user-guide/pages/basic-actions-you-can-perform-on-a-workspace.adoc
  modules/end-user-guide/pages/benefits-of-pull-requests-review-in-che.adoc
  modules/end-user-guide/pages/creating-image-pull-secrets.adoc
  modules/end-user-guide/pages/customizing-workspace-components.adoc
  modules/end-user-guide/pages/developer-workspaces.adoc
  modules/end-user-guide/pages/enabling-artifact-repositories-in-a-restricted-environment.adoc
  modules/end-user-guide/pages/enabling-go-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-gradle-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-maven-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-npm-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-nuget-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-python-artifact-repositories.adoc
  modules/end-user-guide/pages/first-time-contributors.adoc
  modules/end-user-guide/pages/integrating-with-kubernetes.adoc
  modules/end-user-guide/pages/investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
  modules/end-user-guide/pages/mounting-configmaps.adoc
  modules/end-user-guide/pages/mounting-secrets.adoc
  modules/end-user-guide/pages/navigating-che-from-openshift-developer-perspective.adoc
  modules/end-user-guide/pages/navigating-openshift-web-console-from-che.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/requesting-persistent-storage-for-workspaces.adoc
  modules/end-user-guide/pages/selecting-a-workspace-ide.adoc
  modules/end-user-guide/pages/selecting-an-ide-by-using-a-url-parameter.adoc
  modules/end-user-guide/pages/specifying-an-in-browser-ide-for-a-git-repository-by-using-che-editor.yaml.adoc
  modules/end-user-guide/pages/starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc
  modules/end-user-guide/pages/supported-languages.adoc
  modules/end-user-guide/pages/troubleshooting-che.adoc
  modules/end-user-guide/pages/troubleshooting-network-problems.adoc
  modules/end-user-guide/pages/troubleshooting-slow-workspaces.adoc
  modules/end-user-guide/pages/url-parameter-concatenation.adoc
  modules/end-user-guide/pages/url-parameter-for-starting-duplicate-workspaces.adoc
  modules/end-user-guide/pages/url-parameter-for-the-devfile-file-name.adoc
  modules/end-user-guide/pages/url-parameter-for-the-devfile-file-path.adoc
  modules/end-user-guide/pages/url-parameter-for-the-workspace-ide.adoc
  modules/end-user-guide/pages/user-onboarding.adoc
  modules/end-user-guide/pages/using-credentials-and-configurations-in-workspaces.adoc
  modules/end-user-guide/pages/using-git-credentials.adoc
  modules/end-user-guide/pages/viewing-che-workspaces-logs.adoc
Labels: status/code-review, target/branch

#2423 fix: typos
  .gitignore
  modules/administration-guide/pages/limiting-the-number-of-workspaces-that-a-user-can-keep.adoc
Labels: kind/bug, status/code-review, target/branch

#2428 chore: add @max-cx to CODEOWNERS
  .github/CODEOWNERS
Labels: status/code-review, target/branch

#2422 fix: users migration from 7.41.2 to 7.49.0 on OpenShift
  modules/administration-guide/attachments/migration/1-prepare.sh
  modules/administration-guide/attachments/migration/2-migrate.sh
Labels: kind/bug, status/code-review, target/branch

#2426 chore: adding Asciidoctor configuration to handle display in IDEs
  .asciidoctor/docinfo-footer.html
  .asciidoctor/docinfo.html
  .asciidoctorconfig
Labels: status/code-review, target/branch

#2430 chore: declare required extensions for JetBrains IDE.
  .htmltest.yml
  .idea/externalDependencies.xml
  README.md
  modules/hosted-che/partials/proc_providing-a-devfile.adoc
Labels: status/code-review, target/branch

#2408 feat: How to deploy Eclipse Che on mininkube with Keycloak as OIDC pr…
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/installing-che-on-minikube-keycloak-oidc.adoc
Labels: status/code-review, target/branch
