Repository eclipse-che/che-docs, pull requests merged in 2022-06, with the labels that each got.

#2346 fix: Increase pod wait timeout
  modules/administration-guide/attachments/migration/4-wait.sh
Labels: kind/bug, status/code-review

#2345 fix: attributes around upgrading from prev to next version
  antora.yml
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
  modules/administration-guide/pages/installing-image-puller-on-openshift-using-the-web-console.adoc
  modules/administration-guide/pages/specifying-the-update-approval-strategy.adoc
  modules/administration-guide/pages/upgrading-che-7-41-on-openshift.adoc
  modules/administration-guide/pages/upgrading-che-using-the-cli-management-tool-in-restricted-environment.adoc
  modules/administration-guide/pages/upgrading-che-using-the-web-console.adoc
  modules/administration-guide/pages/upgrading-che.adoc
Labels: kind/bug, status/code-review

#2347 fix: Patch CheCluster after DS is deployed
  modules/administration-guide/attachments/migration/3-subscribe.sh
Labels: kind/bug, status/code-review

#2343 fix: modularizing selecting an ide
  modules/end-user-guide/examples/con_customizing-ide-selection-with-the-che-editor-file.adoc
  modules/end-user-guide/examples/proc_using-the-che-prod-editor-file-to-select-an-ide.adoc
  modules/end-user-guide/examples/snip_che-editor-key-values.adoc
  modules/end-user-guide/pages/selecting-an-ide.adoc
  modules/end-user-guide/partials/proc_using-a-custom-plug-in-registry-for-your-ide.adoc
  modules/end-user-guide/partials/proc_using-a-web-reference-for-your-ide.adoc
  modules/end-user-guide/partials/proc_using-an-embedded-editor-definition-for-your-ide.adoc
  modules/end-user-guide/partials/proc_using-url-parameters-to-select-an-ide.adoc
Labels: kind/bug, status/code-review

#2349 fix: metadata
  modules/end-user-guide/pages/selecting-an-ide.adoc
Labels: kind/bug, status/code-review

#2351 feat: Add rollback script for migration guide
  antora.yml
  modules/administration-guide/attachments/migration/2-migrate.sh
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/attachments/migration/rollback.sh
  modules/administration-guide/pages/upgrading-che-7-41-on-openshift.adoc
Labels: status/code-review

#2332 fix: configuring the admin user, removing user data
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-the-administrative-user.adoc
  modules/administration-guide/pages/managing-workloads-using-the-che-server-api.adoc
  modules/administration-guide/pages/removing-user-data.adoc
Labels: kind/bug, status/code-review

#2350 fix: snip update
  modules/end-user-guide/examples/snip_che-supported-ides.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
Labels: kind/bug, status/code-review

#2352 procedures: artifact repos
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/customizing-workspace-components.adoc
  modules/end-user-guide/pages/enabling-artifact-repositories-in-a-restricted-environment.adoc
  modules/end-user-guide/pages/enabling-go-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-gradle-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-maven-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-npm-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-nuget-artifact-repositories.adoc
  modules/end-user-guide/pages/enabling-python-artifact-repositories.adoc
  modules/end-user-guide/partials/snip_warning-about-applying-a-configmap-that-sets-environment-variables.adoc
Labels: status/code-review

#2361 fix: Remove ConsoleLink during migration
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/attachments/migration/rollback.sh
Labels: kind/bug, status/code-review

#2363 Fix JetBrains IDEs identifiers
  modules/end-user-guide/examples/snip_che-editor-key-values.adoc
Labels: kind/bug, status/code-review

#2359 fix: CRW-3051 fix refs to redhat/java --...
  modules/end-user-guide/pages/adding-a-vscode-extension.adoc
Labels: kind/bug, status/code-review

#2367 fix: fixed broken link + small intro edit
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
Labels: kind/bug, status/code-review

#2364 chore: add devfile v2, use Code - OSS
  .che/che-editor.yaml
  .gitignore
  .theia/settings.json
  .vscode/extensions.json
  README.md
  devfilev2.yaml
Labels: status/code-review

#2369 fix: Add startingCSV to subscriptions
  antora.yml
  modules/administration-guide/attachments/migration/3-subscribe.sh
  modules/administration-guide/attachments/migration/rollback.sh
  modules/administration-guide/pages/upgrading-che-7-41-on-openshift.adoc
Labels: kind/bug, status/code-review

#2370 chore: update Dockerfile, add container-build workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-and-validate-on-push.yaml
  .github/workflows/call-publication-builder.yaml
  .github/workflows/container-build.yml
  .htmltest.yml
  CONTRIBUTING.adoc
  Dockerfile
  RELEASE.adoc
  antora-playbook-for-development.yml
  code_review_checklist.adoc
  linkcheckerrc
  modules/hosted-che/partials/proc_providing-a-devfile.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  tools/validate_language_changes.sh
Labels: status/code-review, target/branch

#2372 fix: netlify preview
  .github/workflows/publish-netlify.yml
Labels: kind/bug, status/code-review, target/branch

#2373 fix: Publish preview on netlify
  .github/workflows/preview-sticky-comment.yml
  .github/workflows/publish-netlify.yml
Labels: kind/bug, status/code-review, target/branch

#2374 chore: preview comment
  .github/workflows/publish-netlify.yml
Labels: status/code-review, target/branch

#2375 chore: add link to test on development instance
  .github/workflows/try-in-web-ide.yaml
Labels: status/code-review, target/branch

#2376 chore: navigate the preview link
  .github/workflows/publish-netlify.yml
Labels: status/code-review, target/branch

#2358 Draft: CRW-3052 update to newer prometheus and grafana images
  modules/administration-guide/pages/installing-prometheus-and-grafana.adoc
Labels: status/code-review

#2377 chore: fix typo
  .github/workflows/preview-sticky-comment.yml
  tools/get_vale_styles.sh
Labels: kind/bug, status/code-review, target/branch

#2378 chore: remove obsolete configuration files
  .dockerignore
  .htmltest.yml
  .pre-commit-config.yaml
  linkcheckerrc
  modules/administration-guide/partials/proc_defining-custom-branding-values-for-che-theia.adoc
  modules/hosted-che/partials/ref_about-hosted-che.adoc
  package.json
  proc_upgrading-a-local-installation-of-antora.adoc
  tools/get_vale_styles.sh
Labels: status/code-review, target/branch

#2380 chore: update `che-docs` container
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .github/workflows/container-build.yml
  Dockerfile
  devfile.yaml
  devfilev2.yaml
  gulpfile.js
  tools/runnerpreview.sh
Labels: status/code-review, target/branch

#2381 chore: more container updates
  .github/workflows/container-build.yml
  Dockerfile
Labels: status/code-review, target/branch

#2379 fix: add extra steps for monitoring docs
  modules/administration-guide/examples/snip_che-create-monitoring-namespace.adoc
  modules/administration-guide/pages/configuring-observability.adoc
  modules/administration-guide/pages/installing-prometheus-and-grafana.adoc
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_collecting-dev-workspace-operator-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_viewing-che-metrics-on-grafana-dashboards.adoc
  modules/administration-guide/partials/proc_viewing-dev-workspace-operator-metrics-on-grafana-dashboards.adoc
Labels: kind/bug, status/code-review, target/branch

#2386 fix: search in development playbook
  antora-playbook-for-development.yml
  supplemental-ui/css/search.css
  supplemental-ui/js/search-ui.js
  supplemental-ui/partials/header-content.hbs
Labels: kind/bug, status/code-review, target/branch
