Repository eclipse-che/che-docs, pull requests merged in 2022-11, with the labels that each got.

#2478 fix: rhdevdocs-4518 updated supported languages page
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/adopting-che.adoc
  modules/end-user-guide/pages/stack-samples.adoc
  modules/end-user-guide/pages/supported-languages.adoc
Labels: kind/bug, status/code-review, target/branch

#2479 chore: version 7.56.0 in main branch
  antora.yml
Labels: status/code-review, target/branch

#2480 chore: Address deprecation warnings in GitHub workflow
  .github/dependabot.yml
  .github/workflows/build-and-validate-on-pr.yaml
  .github/workflows/build-and-validate-on-push.yaml
  .github/workflows/container-build.yml
  .github/workflows/container-on-pull-request.yml
  .github/workflows/preview-sticky-comment.yml
  .github/workflows/publish-netlify.yml
  .github/workflows/vale.yml
Labels: status/code-review, target/branch

#2484 feat: Remove auto-generated che-server advanced configuration options
  antora.yml
  modules/administration-guide/pages/advanced-configuration-options-for-the-che-server-component.adoc
  modules/administration-guide/partials/con_understanding-che-server-advanced-configuration.adoc
Labels: status/code-review, target/branch

#2485 feat: update the container to prepare for Antora to Pantheon conversion
  Dockerfile
Labels: status/code-review, target/branch

#2488 fix: missing local gulp
  Dockerfile
  antora-assembler.yml
Labels: kind/bug, status/code-review, target/branch

#2489 feat: Antora assembler
  CONTRIBUTING.adoc
  antora-assembler.yml
  antora-playbook-for-development.yml
  modules/administration-guide/pages/creating-a-telemetry-plugin.adoc
  modules/administration-guide/pages/defining-the-list-of-images-to-pull.adoc
  modules/end-user-guide/examples/snip_che-supported-languages.adoc
  modules/extensions/partials/proc_installing-openshift-connector-in-che.adoc
  tools/checluster_docs_gen.sh
  tools/environment_docs_gen.sh
  tools/validate_language_changes.sh
Labels: status/code-review, target/branch

#2476 VS Code is the new default IDE, Theia is deprecated
  modules/end-user-guide/examples/snip_che-table-of-supported-editors.adoc
  modules/end-user-guide/pages/selecting-a-workspace-ide.adoc
  modules/end-user-guide/pages/starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc
  modules/end-user-guide/pages/url-parameter-for-the-workspace-ide.adoc
Labels: status/code-review, target/branch

#2494 chore: #21804 update che server config to use .spec.properties.server.properties for cheLogLevel and customCheProperties.CHE_LOGS_APPENDERS_IMPL, as CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB is obsolete
  modules/administration-guide/partials/con_understanding-che-server-advanced-configuration.adoc
Labels: kind/task, status/code-review, target/branch

#2497 chore: (workaround) keep the latest podman container built on Fedora 36
  Dockerfile
Labels: status/code-review, target/branch

#2496 feat: support stable release for minikube and kubectl
  modules/administration-guide/pages/installing-che-on-minikube-keycloak-oidc.adoc
  modules/administration-guide/pages/installing-che-on-minikube.adoc
Labels: status/code-review, target/branch

#2498 fix: typo
  modules/administration-guide/pages/installing-che-on-minikube-keycloak-oidc.adoc
Labels: kind/bug, status/code-review, target/branch

#2499 docs: Use Visual Studio Code in the example in Calculating requirements
  antora.yml
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/partials/con_a-workspace-example.adoc
  modules/administration-guide/partials/con_controller-requirements.adoc
  modules/administration-guide/partials/con_operator-requirements.adoc
  modules/administration-guide/partials/proc_workspaces-requirements.adoc
Labels: status/code-review, target/branch

#2491 procedures: uninstalling che process update (rhdevdocs-4450)
  modules/administration-guide/examples/snip_che-note-uninstalling-in-minikube-cluster.adoc
  modules/administration-guide/pages/uninstalling-che.adoc
Labels: status/code-review, target/branch

#2501 docs: configuring the Open VSX registry URL
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-the-open-vsx-registry-url.adoc
Labels: status/code-review, target/branch

#2502 docs: update of defining the list of images to pull (rhdevdocs-4580)
  modules/administration-guide/pages/defining-the-list-of-images-to-pull.adoc
Labels: status/code-review, target/branch

#2506 docs: updated glossary page with che-code (rhdevdocs-4580)
  modules/glossary/partials/con_glossary.adoc
Labels: status/code-review, target/branch
