Repository eclipse-che/che-docs, pull requests merged in 2023-03, with the labels that each got.

#2561 feat: Remove PostgreSQL component
  antora.yml
  modules/administration-guide/examples/snip_che-postgresql-additional-resources.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/architecture-overview.adoc
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
  modules/administration-guide/pages/che-operator.adoc
  modules/administration-guide/pages/che-server.adoc
  modules/administration-guide/pages/checluster-custom-resource-fields-reference.adoc
  modules/administration-guide/pages/installing-che-using-storage-classes.adoc
  modules/administration-guide/pages/postgresql.adoc
  modules/administration-guide/pages/server-components.adoc
  modules/administration-guide/pages/understanding-the-checluster-custom-resource.adoc
  modules/administration-guide/partials/snip_mounting-a-secret-or-a-configmap-into-a-container.adoc
  tools/checluster_docs_gen.sh
  tools/create_architecture_diagrams.py
Labels: status/code-review, target/branch

#2566 Add info about starting a workspace from raw devfile location
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/starting-a-new-workspace-from-a-devfile-url.adoc
  modules/end-user-guide/pages/user-onboarding.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2560 feat: Azure DevOps Service OAuth2
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-microsoft-azure-devops-services.adoc
  modules/administration-guide/pages/configuring-oauth-for-git-providers.adoc
  modules/administration-guide/pages/importing-untrusted-tls-certificates.adoc
  modules/administration-guide/partials/proc_applying-the-microsoft-azure-devops-services-oauth-app-secret.adoc
  modules/administration-guide/partials/proc_setting-up-the-github-oauth-app.adoc
  modules/administration-guide/partials/proc_setting-up-the-microsoft-azure-devops-services-oauth-app.adoc
  modules/end-user-guide/pages/authenticating-to-a-git-server-from-a-workspace.adoc
  modules/end-user-guide/pages/enabling-maven-artifact-repositories.adoc
  modules/end-user-guide/pages/using-a-git-provider-access-token.adoc
Labels: status/code-review, target/branch

#2571 chore: remove +'s from url in Setting up the Microsoft Azure DevOps Services OAuth App
  modules/administration-guide/partials/proc_setting-up-the-microsoft-azure-devops-services-oauth-app.adoc
Labels: status/code-review, target/branch

#2564 fix: update RELEASE.adoc
  RELEASE.adoc
Labels: kind/bug, status/code-review, target/branch

#2568 docs: troubleshooting webview loading error (rhdevdocs-4803)
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/troubleshooting-che.adoc
  modules/end-user-guide/pages/troubleshooting-webview-loading-error.adoc
Labels: status/code-review, target/branch

#2558 fix: removed eclipse theia from table of supported editors (rhdevdocs-4580)
  modules/end-user-guide/examples/snip_che-table-of-supported-editors.adoc
Labels: kind/bug, status/code-review, target/branch

#2552 docs: Rewriting pages about editors
  modules/administration-guide/partials/proc_adding-or-removing-extensions-in-the-embedded-open-vsx-registry-instance.adoc
  modules/administration-guide/partials/proc_selecting-an-open-vsx-registry-instance.adoc
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/customizing-workspace-components.adoc
  modules/end-user-guide/pages/defining-a-common-ide.adoc
  modules/end-user-guide/pages/ides-in-workspaces.adoc
  modules/end-user-guide/pages/microsoft-visual-studio-code-open-source-ide.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/selecting-a-workspace-ide.adoc
  modules/end-user-guide/pages/selecting-an-in-browser-ide-for-all-workspaces-that-clone-the-same-git-repository.adoc
  modules/end-user-guide/pages/selecting-an-in-browser-ide-for-one-new-workspace.adoc
  modules/end-user-guide/pages/url-parameter-for-the-ide.adoc
  modules/end-user-guide/pages/url-parameter-for-the-workspace-ide.adoc
  modules/end-user-guide/partials/proc_automating-installation-of-microsoft-visual-studio-code-extensions-at-workspace-startup.adoc
  modules/end-user-guide/partials/proc_setting-up-che-editor-yaml.adoc
  modules/end-user-guide/partials/ref_parameters-for-che-editor-yaml.adoc
Labels: status/code-review, target/branch

#2572 chore: update product version values in antora.yml to Che 7.62
  antora.yml
Labels: status/code-review, target/branch

#2578 docs: fixing units in the resource requirments
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
Labels: kind/bug, status/code-review, target/branch

#2574 docs: Removing obsolete info about administrative user. Updating GDPR procedure
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-the-administrative-user.adoc
  modules/administration-guide/pages/removing-user-data-in-compliance-with-the-gdpr.adoc
Labels: status/code-review, target/branch

#2562 fix: removing che theia from troubleshooting slow workspaces (rhdevdocs-4580)
  modules/end-user-guide/pages/troubleshooting-slow-workspaces.adoc
Labels: kind/bug, status/code-review, target/branch
