Repository eclipse-che/che-docs, pull requests merged in 2023-05, with the labels that each got.

#2596 Update proc_requesting-persistent-storage-in-a-pvc.adoc
  modules/end-user-guide/partials/proc_requesting-persistent-storage-in-a-pvc.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2599 fix: splitting the Collecting Dev Workspace Operator metrics procedure into upstream and downstream versions
  modules/administration-guide/examples/snip_che-create-a-role-and-rolebinding-for-prometheus-to-view-metrics.adoc
  modules/administration-guide/pages/architecture-overview.adoc
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_collecting-dev-workspace-operator-metrics-with-prometheus.adoc
Labels: kind/bug, status/code-review, target/branch

#2590 feat: Allow for the customization of user roles in Che
  modules/administration-guide/examples/snip_che-configuring-cluster-roles-for-users.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-cluster-roles-for-users.adoc
Labels: status/code-review, target/branch

#2602 chore: update version to Che 7.64
  publication-builder-antora-playbook.yml
Labels: status/code-review, target/branch

#2603 fix: remove an xref that causes a ccutil error
  modules/end-user-guide/partials/proc_setting-up-che-editor-yaml.adoc
Labels: kind/bug, status/code-review, target/branch

#2600 chore: RHDEVDOCS-5317 update to OCP 4.12 as...
  antora.yml
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
  modules/administration-guide/pages/installing-image-puller-on-openshift-using-the-web-console.adoc
  modules/administration-guide/pages/repairing-the-devworkspace-operator-on-openshift.adoc
  modules/administration-guide/partials/proc_setting-up-the-microsoft-azure-devops-services-oauth-app.adoc
Labels: status/code-review, target/branch

#2594 fix: small typo in dashboard docs
  modules/administration-guide/pages/dashboard.adoc
Labels: kind/bug, status/code-review, target/branch

#2607 chore: update version to Che 7.65
  publication-builder-antora-playbook.yml
Labels: status/code-review, target/branch

#2606 chore: update version to Che 7.65
  antora.yml
Labels: status/code-review, target/branch

#2610 fix: a minor patch to add to https://github.com/eclipse-che/che-docs/pull/2609
  modules/administration-guide/partials/proc_applying-an-application-link-secret-for-the-bitbucket-server.adoc
Labels: kind/bug, status/code-review, target/branch

#2608 chore: update version to Che 7.65
  antora.yml
Labels: status/code-review, target/branch
