Repository eclipse-che/che-docs, pull requests merged in 2023-02, with the labels that each got.

#2510 docs: manage workspaces with kubectl
  modules/end-user-guide/pages/managing-workspaces-with-apis.adoc
  modules/end-user-guide/partials/proc_creating-workspaces.adoc
  modules/end-user-guide/partials/proc_listing-workspaces.adoc
  modules/end-user-guide/partials/proc_removing-workspaces.adoc
  modules/end-user-guide/partials/proc_restarting-workspaces.adoc
  modules/end-user-guide/partials/proc_starting-stopped-workspaces.adoc
  modules/end-user-guide/partials/proc_stopping-workspaces.adoc
Labels: status/code-review, target/branch

#2545 docs: merge .../che-docs/pull/2510 into main
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/managing-workspaces-with-apis.adoc
  modules/end-user-guide/partials/proc_creating-workspaces.adoc
  modules/end-user-guide/partials/proc_listing-workspaces.adoc
  modules/end-user-guide/partials/proc_removing-workspaces.adoc
  modules/end-user-guide/partials/proc_starting-stopped-workspaces.adoc
  modules/end-user-guide/partials/proc_stopping-workspaces.adoc
Labels: status/code-review, target/branch

#2546 chore: remove the missing_anchors test from tools/detect-unused-content.sh
  tools/detect-unused-content.sh
Labels: status/code-review, target/branch

#2549 fix: correct the version value in RELEASE.adoc
  RELEASE.adoc
Labels: kind/bug, status/code-review, target/branch

#2550 fix: bitbucket_consumer_key -> bitbucket-consumer-key
  modules/administration-guide/partials/proc_applying-an-application-link-secret-for-the-bitbucket-server.adoc
  modules/administration-guide/partials/proc_setting-up-an-application-link-on-the-bitbucket-server.adoc
Labels: kind/bug, status/code-review, target/branch

#2548 feat: Configure disable subdomain isolation
  modules/administration-guide/partials/proc_applying-the-github-oauth-app-secret.adoc
Labels: status/code-review, target/branch

#2551 core: use che-code/latest as a default editor
  modules/end-user-guide/examples/snip_che-table-of-supported-editors.adoc
Labels: status/code-review, target/branch

#2554 Add instructions how to configure Bitbucket Server oAuth2
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-oauth-2-for-a-bitbucket-server.adoc
  modules/administration-guide/pages/oauth-for-github-gitlab-or-bitbucket.adoc
  modules/administration-guide/partials/proc_applying-an-oauth-2-application-link-secret-for-the-bitbucket-server.adoc
  modules/administration-guide/partials/proc_setting-up-an-oauth-2-application-link-on-the-bitbucket-server.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2557 fix: review and edit PR 2555 > docs: Updating GDPR user removal flow, and procedure for obtaining user ID
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/managing-identities-and-authorizations.adoc
  modules/administration-guide/pages/removing-user-data-in-compliance-with-the-gdpr.adoc
  modules/administration-guide/pages/removing-user-data.adoc
  modules/end-user-guide/pages/using-a-git-provider-access-token.adoc
Labels: kind/bug, status/code-review, target/branch

#2556 fix: removed Che-Theia workspaces page (rhdevdocs-4580)
  modules/administration-guide/images/telemetry/telemetry_diagram.png
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/che-theia-workspaces.adoc
  modules/administration-guide/pages/configuring-observability.adoc
Labels: kind/bug, status/code-review, target/branch

#2544 docs: NFS not supported warning (rhdevdocs-4580)
  modules/administration-guide/pages/configuring-storage.adoc
Labels: status/code-review, target/branch

#2559 Add Jana (deerskindoll) to CODEOWNERS.
  .github/CODEOWNERS
Labels: kind/enhancement, status/code-review, target/branch
