Repository eclipse-che/che-docs, pull requests merged in 2023-04, with the labels that each got.

#2573 docs: Add 'Open OpenShift Console' item
  modules/end-user-guide/pages/microsoft-visual-studio-code-open-source-ide.adoc
Labels: status/code-review, target/branch

#2584 chore: include the include statement and a blank upstream-example file
  modules/administration-guide/examples/snip_che-example-devfile-disclaimer.adoc
  modules/administration-guide/pages/calculating-che-resource-requirements.adoc
Labels: status/code-review, target/branch

#2588 fix: replace "insiders" with "latest" in example code block
  modules/end-user-guide/partials/proc_creating-workspaces.adoc
Labels: kind/bug, status/code-review, target/branch

#2587 Update the using-a-git-provider-access-token.adoc to omit scm-userid
  modules/end-user-guide/pages/using-a-git-provider-access-token.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2589 fix: added link to default devfile.yaml (rhdevdocs-5057)
  modules/end-user-guide/examples/snip_che-ide-default-yaml-file.adoc
  modules/end-user-guide/pages/url-parameter-for-the-ide.adoc
Labels: kind/bug, status/code-review, target/branch

#2583 fix: added xrefs (rhdevdocs-5057)
  modules/administration-guide/partials/proc_selecting-an-open-vsx-registry-instance.adoc
  modules/end-user-guide/partials/proc_setting-up-che-editor-yaml.adoc
Labels: kind/bug, status/code-review, target/branch

#2593 fix: replace namespace and app name with placeholders for #2586
  modules/administration-guide/partials/proc_collecting-che-metrics-with-prometheus.adoc
  modules/administration-guide/partials/proc_collecting-dev-workspace-operator-metrics-with-prometheus.adoc
Labels: kind/bug, status/code-review, target/branch
