Repository eclipse-che/che-docs, pull requests merged in 2023-07, with the labels that each got.

#2616 fix: patch the docs regarding the swap of the default VSX registry instance (from the public to the embedded)
  modules/administration-guide/examples/snip_che-default-vsx-registry.adoc
  modules/administration-guide/examples/snip_che-non-default-vsx-registry-instance.adoc
  modules/administration-guide/pages/extensions-for-microsoft-visual-studio-code-open-source.adoc
  modules/administration-guide/partials/proc_adding-or-removing-extensions-in-the-embedded-open-vsx-registry-instance.adoc
  modules/administration-guide/partials/proc_selecting-an-open-vsx-registry-instance.adoc
  modules/end-user-guide/partials/proc_automating-installation-of-microsoft-visual-studio-code-extensions-at-workspace-startup.adoc
Labels: kind/bug, status/code-review, target/branch

#2612 docs: url parameter for workspace image (rhdevdocs-5255)
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/url-parameter-for-container-image.adoc
Labels: status/code-review, target/branch

#2622 docs: Adding a note about GitHub Enterprise Cloud PAT requirement
  modules/end-user-guide/pages/using-a-git-provider-access-token.adoc
Labels: status/code-review, target/branch

#2627 chore: update of the "Configuring networking" page
  modules/administration-guide/examples/proc_che-configuring-ingresses.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/adding-labels-and-annotations.adoc
  modules/administration-guide/pages/configuring-networking.adoc
  modules/administration-guide/partials/proc_configuring-routes.adoc
Labels: status/code-review, target/branch

#2621 fix: Installing Eclipse Che in disconnected cluster
  antora.yml
  modules/administration-guide/attachments/restricted-environment/prepare-restricted-environment.sh
  modules/administration-guide/pages/installing-che-in-a-restricted-environment.adoc
  modules/administration-guide/partials/snip_preparing-images-for-a-restricted-environment.adoc
Labels: kind/bug, status/code-review, target/branch

#2628 Remove not relevant PR step item
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status/code-review, target/branch

#2626 fix: Configuring storage classes
  modules/administration-guide/pages/installing-che-using-storage-classes.adoc
  modules/end-user-guide/partials/proc_requesting-persistent-storage-in-a-pvc.adoc
Labels: kind/bug, status/code-review, target/branch

#2630 fix: Remove https://mattermost.eclipse.org/eclipse/channels/eclipse-c…
  CONTRIBUTING.adoc
  RELEASE.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: kind/bug, status/code-review, target/branch

#2625 feat: Deploying Che with self-signed certificate
  modules/administration-guide/examples/snip_che-xref-configuring-che-with-self-signed-certificate.adoc
  modules/administration-guide/nav.adoc
  modules/administration-guide/pages/configuring-che-with-self-signed-certificate.adoc
  modules/administration-guide/pages/configuring-networking.adoc
  modules/administration-guide/pages/installing-che-on-minikube-keycloak-oidc.adoc
  modules/administration-guide/pages/installing-che-on-minikube.adoc
Labels: status/code-review, target/branch

#2629 fix: OAuth2 secret configuration for Azure DevOps
  modules/administration-guide/partials/proc_applying-the-microsoft-azure-devops-services-oauth-app-secret.adoc
  modules/administration-guide/partials/proc_setting-up-the-microsoft-azure-devops-services-oauth-app.adoc
Labels: kind/bug, status/code-review, target/branch

#2631 Add mattermost link to IgnoredURLs
  .htmltest.yml
  CONTRIBUTING.adoc
  RELEASE.adoc
  modules/overview/pages/introduction-to-eclipse-che.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2633 fix: Add missed download link to prepare-restricted-environment.sh scipt
  modules/administration-guide/partials/snip_preparing-images-for-a-restricted-environment.adoc
Labels: kind/bug, status/code-review, target/branch

#2634 fix: update application name field (rhdevdocs-5546)
  modules/administration-guide/partials/proc_setting-up-the-github-oauth-app.adoc
Labels: kind/bug, status/code-review, target/branch

#2620 procedures: Add caution against installing operators in separate namespaces
  antora.yml
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
Labels: status/code-review, target/branch

#2632 Exclude the `scm-username` annotation from the PAT instruction
  modules/end-user-guide/pages/using-a-git-provider-access-token.adoc
Labels: status/code-review, target/branch

#2636 docs: Removing docs related to the verbose mode
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/investigating-failures-at-a-workspace-start-using-the-verbose-mode.adoc
  modules/end-user-guide/pages/troubleshooting-che.adoc
Labels: status/code-review, target/branch

#2597 docs : change customCheProperties to extraProperties
  modules/administration-guide/partials/con_understanding-che-server-advanced-configuration.adoc
Labels: status/code-review, target/branch

#2637 doc: adding `Important` note for Azure OAuth Third-Party access requirements
  modules/administration-guide/partials/proc_setting-up-the-microsoft-azure-devops-services-oauth-app.adoc
Labels: status/code-review, target/branch
