Repository eclipse-che/che-docs, pull requests merged in 2024-02, with the labels that each got.

#2678 chore: Vale errors fix
  .vale.ini
  code_review_checklist.adoc
  modules/administration-guide/examples/snip_che-upgrading-the-chectl-management-tool.adoc
  modules/administration-guide/pages/configuring-storage-sizes.adoc
  modules/administration-guide/pages/user-workspaces.adoc
  modules/end-user-guide/pages/authenticating-to-a-git-server-from-a-workspace.adoc
  modules/end-user-guide/pages/requesting-persistent-storage-for-workspaces.adoc
  modules/end-user-guide/pages/using-a-git-provider-access-token.adoc
  modules/end-user-guide/pages/using-credentials-and-configurations-in-workspaces.adoc
  modules/end-user-guide/partials/proc_requesting-persistent-storage-in-a-pvc.adoc
Labels: kind/bug, status/code-review, target/branch

#2681 Vale errors only in the GitHub action
  .github/workflows/vale.yml
Labels: status/code-review, target/branch

#2683 Update configuring-a-user-namespace.adoc
  modules/administration-guide/pages/configuring-a-user-namespace.adoc
Labels: kind/enhancement, status/code-review, target/branch

#2682 fix: missing monospace
  modules/administration-guide/pages/defining-the-list-of-images-to-pull.adoc
Labels: kind/bug, status/code-review, target/branch

#2684 chore: bump up to 7.81.x
  antora.yml
Labels: status/code-review, target/branch

#2689 chore: IgnoreURLs update
  .htmltest.yml
Labels: kind/bug, status/code-review, target/branch

#2690 Fix outdated workspace nodeSelector documentation
  modules/administration-guide/pages/configuring-workspaces-nodeselector.adoc
Labels: kind/bug, status/code-review, target/branch

#2691 fix: Ensure that internal devfile registry is enabled in airgap env
  modules/administration-guide/attachments/restricted-environment/prepare-restricted-environment.sh
Labels: kind/bug, status/code-review, target/branch

#2687 feat: Explain how users can override the editor's container image
  modules/end-user-guide/nav.adoc
  modules/end-user-guide/pages/optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc
  modules/end-user-guide/pages/url-parameter-for-the-ide-image.adoc
Labels: status/code-review, target/branch

#2688 docs: Adding caution for WTO, DWO, Dev Space installation
  modules/administration-guide/pages/installing-che-on-openshift-using-the-web-console.adoc
Labels: status/code-review, target/branch
